-- =============================================================================
-- Purpose          : Compare the Oracle database with every object explicitly
--                    defined by the ADVENTUREWORKS2022 DDL scripts.
-- Execution order  : 00; run before setup and again after DDL execution.
-- Connection user  : SYSTEM, or another account with access to ALL_USERS,
--                    ALL_OBJECTS, and ALL_CONSTRAINTS.
-- Objects inspected: ADVENTUREWORKS2022 user/schema, tables, named constraints,
--                    managed indexes, functions, procedures, and views.
-- Notes            : Read-only. Oracle identity sequences and constraint-backed
--                    indexes are implicit implementation objects and therefore
--                    are not listed as independently expected DDL objects.
-- =============================================================================

SET PAGESIZE 1000
SET LINESIZE 220
SET FEEDBACK ON

COLUMN OBJECT_NAME FORMAT A75
COLUMN OBJECT_TYPE FORMAT A15
COLUMN CREATED_OR_NOT FORMAT A15

PROMPT ========================================================================
PROMPT ADVENTUREWORKS2022 DDL OBJECT CREATION STATUS
PROMPT ========================================================================

WITH
expected_tables AS (
  SELECT COLUMN_VALUE AS OBJECT_NAME
  FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'PERSON_PERSON', 'PERSON_PERSONPHONE', 'PERSON_PHONENUMBERTYPE',
    'PERSON_ADDRESS', 'PERSON_STATEPROVINCE', 'PERSON_BUSINESSENTITYADDRESS',
    'PERSON_COUNTRYREGION', 'PERSON_EMAILADDRESS', 'HUMANRESOURCES_EMPLOYEE',
    'HUMANRESOURCES_DEPARTMENT', 'HUMANRESOURCES_EMPLOYEEDEPARTMENTHISTORY',
    'HUMANRESOURCES_SHIFT', 'PERSON_ADDRESSTYPE', 'SALES_CUSTOMER',
    'HUMANRESOURCES_JOBCANDIDATE', 'PRODUCTION_PRODUCT',
    'PRODUCTION_PRODUCTDESCRIPTION', 'PRODUCTION_PRODUCTMODEL',
    'PRODUCTION_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE', 'SALES_SALESTERRITORY',
    'SALES_SALESPERSON', 'SALES_SALESORDERHEADER', 'SALES_STORE',
    'PERSON_BUSINESSENTITYCONTACT', 'PERSON_CONTACTTYPE', 'PURCHASING_VENDOR',
    'DBO_AWBUILDVERSION', 'DBO_DATABASELOG', 'DBO_ERRORLOG',
    'HUMANRESOURCES_EMPLOYEEPAYHISTORY', 'PERSON_BUSINESSENTITY',
    'PERSON_PASSWORD', 'PRODUCTION_BILLOFMATERIALS', 'PRODUCTION_CULTURE',
    'PRODUCTION_DOCUMENT', 'PRODUCTION_ILLUSTRATION', 'PRODUCTION_LOCATION',
    'PRODUCTION_PRODUCTCATEGORY', 'PRODUCTION_PRODUCTCOSTHISTORY',
    'PRODUCTION_PRODUCTDOCUMENT', 'PRODUCTION_PRODUCTINVENTORY',
    'PRODUCTION_PRODUCTLISTPRICEHISTORY',
    'PRODUCTION_PRODUCTMODELILLUSTRATION', 'PRODUCTION_PRODUCTPHOTO',
    'PRODUCTION_PRODUCTPRODUCTPHOTO', 'PRODUCTION_PRODUCTREVIEW',
    'PRODUCTION_PRODUCTSUBCATEGORY', 'PRODUCTION_SCRAPREASON',
    'PRODUCTION_TRANSACTIONHISTORY', 'PRODUCTION_TRANSACTIONHISTORYARCHIVE',
    'PRODUCTION_UNITMEASURE', 'PRODUCTION_WORKORDER',
    'PRODUCTION_WORKORDERROUTING', 'PURCHASING_PRODUCTVENDOR',
    'PURCHASING_PURCHASEORDERDETAIL', 'PURCHASING_PURCHASEORDERHEADER',
    'PURCHASING_SHIPMETHOD', 'SALES_COUNTRYREGIONCURRENCY',
    'SALES_CREDITCARD', 'SALES_CURRENCY', 'SALES_CURRENCYRATE',
    'SALES_PERSONCREDITCARD', 'SALES_SALESORDERDETAIL',
    'SALES_SALESORDERHEADERSALESREASON', 'SALES_SALESPERSONQUOTAHISTORY',
    'SALES_SALESREASON', 'SALES_SALESTAXRATE', 'SALES_SALESTERRITORYHISTORY',
    'SALES_SHOPPINGCARTITEM', 'SALES_SPECIALOFFER',
    'SALES_SPECIALOFFERPRODUCT'
  ))
),
expected_constraints AS (
  SELECT COLUMN_VALUE AS OBJECT_NAME
  FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'AK_ADDRESS_ROWGUID', 'AK_ADDRESSTYPE_NAME', 'AK_ADDRESSTYPE_ROWGUID',
    'AK_BUSINESSENTITY_ROWGUID', 'AK_BUSINESSENTITYADDRESS_ROWGUID',
    'AK_BUSINESSENTITYCONTACT_ROWGUID', 'AK_CONTACTTYPE_NAME',
    'AK_COUNTRYREGION_NAME', 'AK_CREDITCARD_CARDNUMBER', 'AK_CULTURE_NAME',
    'AK_CURRENCY_NAME',
    'AK_CURRENCYRATE_CURRENCYRATEDATE_FROMCURRENCYCODE_TOCURRENCYCODE',
    'AK_CUSTOMER_ACCOUNTNUMBER', 'AK_CUSTOMER_ROWGUID', 'AK_DEPARTMENT_NAME',
    'AK_DOCUMENT_DOCUMENTLEVEL_DOCUMENTNODE', 'AK_DOCUMENT_ROWGUID',
    'AK_EMPLOYEE_LOGINID', 'AK_EMPLOYEE_NATIONALIDNUMBER',
    'AK_EMPLOYEE_ROWGUID', 'AK_LOCATION_NAME', 'AK_PERSON_ROWGUID',
    'AK_PRODUCT_NAME', 'AK_PRODUCT_PRODUCTNUMBER', 'AK_PRODUCT_ROWGUID',
    'AK_PRODUCTCATEGORY_NAME', 'AK_PRODUCTCATEGORY_ROWGUID',
    'AK_PRODUCTDESCRIPTION_ROWGUID', 'AK_PRODUCTMODEL_NAME',
    'AK_PRODUCTMODEL_ROWGUID', 'AK_PRODUCTSUBCATEGORY_NAME',
    'AK_PRODUCTSUBCATEGORY_ROWGUID', 'AK_SALESORDERDETAIL_ROWGUID',
    'AK_SALESORDERHEADER_ROWGUID', 'AK_SALESORDERHEADER_SALESORDERNUMBER',
    'AK_SALESPERSON_ROWGUID', 'AK_SALESPERSONQUOTAHISTORY_ROWGUID',
    'AK_SALESTAXRATE_ROWGUID', 'AK_SALESTAXRATE_STATEPROVINCEID_TAXTYPE',
    'AK_SALESTERRITORY_NAME', 'AK_SALESTERRITORY_ROWGUID',
    'AK_SALESTERRITORYHISTORY_ROWGUID', 'AK_SCRAPREASON_NAME',
    'AK_SHIFT_NAME', 'AK_SHIFT_STARTTIME_ENDTIME', 'AK_SHIPMETHOD_NAME',
    'AK_SHIPMETHOD_ROWGUID', 'AK_SPECIALOFFER_ROWGUID',
    'AK_SPECIALOFFERPRODUCT_ROWGUID', 'AK_STATEPROVINCE_NAME',
    'AK_STATEPROVINCE_ROWGUID',
    'AK_STATEPROVINCE_STATEPROVINCECODE_COUNTRYREGIONCODE',
    'AK_STORE_ROWGUID', 'AK_UNITMEASURE_NAME', 'AK_VENDOR_ACCOUNTNUMBER',
    'CK_BILLOFMATERIALS_BOMLEVEL', 'CK_BILLOFMATERIALS_ENDDATE',
    'CK_BILLOFMATERIALS_PERASSEMBLYQTY',
    'CK_BILLOFMATERIALS_PRODUCTASSEMBLYID', 'CK_DOCUMENT_STATUS',
    'CK_EMPLOYEE_BIRTHDATE', 'CK_EMPLOYEE_GENDER', 'CK_EMPLOYEE_HIREDATE',
    'CK_EMPLOYEE_MARITALSTATUS', 'CK_EMPLOYEE_SICKLEAVEHOURS',
    'CK_EMPLOYEE_VACATIONHOURS', 'CK_EMPLOYEEDEPARTMENTHISTORY_ENDDATE',
    'CK_EMPLOYEEPAYHISTORY_PAYFREQUENCY', 'CK_EMPLOYEEPAYHISTORY_RATE',
    'CK_LOCATION_AVAILABILITY', 'CK_LOCATION_COSTRATE',
    'CK_PERSON_EMAILPROMOTION', 'CK_PERSON_PERSONTYPE', 'CK_PRODUCT_CLASS',
    'CK_PRODUCT_DAYSTOMANUFACTURE', 'CK_PRODUCT_LISTPRICE',
    'CK_PRODUCT_PRODUCTLINE', 'CK_PRODUCT_REORDERPOINT',
    'CK_PRODUCT_SAFETYSTOCKLEVEL', 'CK_PRODUCT_SELLENDDATE',
    'CK_PRODUCT_STANDARDCOST', 'CK_PRODUCT_STYLE', 'CK_PRODUCT_WEIGHT',
    'CK_PRODUCTCOSTHISTORY_ENDDATE', 'CK_PRODUCTCOSTHISTORY_STANDARDCOST',
    'CK_PRODUCTINVENTORY_BIN', 'CK_PRODUCTINVENTORY_SHELF',
    'CK_PRODUCTLISTPRICEHISTORY_ENDDATE',
    'CK_PRODUCTLISTPRICEHISTORY_LISTPRICE', 'CK_PRODUCTREVIEW_RATING',
    'CK_PRODUCTVENDOR_AVERAGELEADTIME', 'CK_PRODUCTVENDOR_LASTRECEIPTCOST',
    'CK_PRODUCTVENDOR_MAXORDERQTY', 'CK_PRODUCTVENDOR_MINORDERQTY',
    'CK_PRODUCTVENDOR_ONORDERQTY', 'CK_PRODUCTVENDOR_STANDARDPRICE',
    'CK_PURCHASEORDERDETAIL_ORDERQTY', 'CK_PURCHASEORDERDETAIL_RECEIVEDQTY',
    'CK_PURCHASEORDERDETAIL_REJECTEDQTY', 'CK_PURCHASEORDERDETAIL_UNITPRICE',
    'CK_PURCHASEORDERHEADER_FREIGHT', 'CK_PURCHASEORDERHEADER_SHIPDATE',
    'CK_PURCHASEORDERHEADER_STATUS', 'CK_PURCHASEORDERHEADER_SUBTOTAL',
    'CK_PURCHASEORDERHEADER_TAXAMT', 'CK_SALESORDERDETAIL_ORDERQTY',
    'CK_SALESORDERDETAIL_UNITPRICE', 'CK_SALESORDERDETAIL_UNITPRICEDISCOUNT',
    'CK_SALESORDERHEADER_DUEDATE', 'CK_SALESORDERHEADER_FREIGHT',
    'CK_SALESORDERHEADER_SHIPDATE', 'CK_SALESORDERHEADER_STATUS',
    'CK_SALESORDERHEADER_SUBTOTAL', 'CK_SALESORDERHEADER_TAXAMT',
    'CK_SALESPERSON_BONUS', 'CK_SALESPERSON_COMMISSIONPCT',
    'CK_SALESPERSON_SALESLASTYEAR', 'CK_SALESPERSON_SALESQUOTA',
    'CK_SALESPERSON_SALESYTD', 'CK_SALESPERSONQUOTAHISTORY_SALESQUOTA',
    'CK_SALESTAXRATE_TAXTYPE', 'CK_SALESTERRITORY_COSTLASTYEAR',
    'CK_SALESTERRITORY_COSTYTD', 'CK_SALESTERRITORY_SALESLASTYEAR',
    'CK_SALESTERRITORY_SALESYTD', 'CK_SALESTERRITORYHISTORY_ENDDATE',
    'CK_SHIPMETHOD_SHIPBASE', 'CK_SHIPMETHOD_SHIPRATE',
    'CK_SHOPPINGCARTITEM_QUANTITY', 'CK_SPECIALOFFER_DISCOUNTPCT',
    'CK_SPECIALOFFER_ENDDATE', 'CK_SPECIALOFFER_MAXQTY',
    'CK_SPECIALOFFER_MINQTY', 'CK_TRANSACTIONHISTORY_TRANSACTIONTYPE',
    'CK_TRANSACTIONHISTORYARCHIVE_TRANSACTIONTYPE', 'CK_VENDOR_CREDITRATING',
    'CK_WORKORDER_ENDDATE', 'CK_WORKORDER_ORDERQTY',
    'CK_WORKORDER_SCRAPPEDQTY', 'CK_WORKORDERROUTING_ACTUALCOST',
    'CK_WORKORDERROUTING_ACTUALENDDATE',
    'CK_WORKORDERROUTING_ACTUALRESOURCEHRS',
    'CK_WORKORDERROUTING_PLANNEDCOST',
    'CK_WORKORDERROUTING_SCHEDULEDENDDATE',
    'FK_ADDRESS_STATEPROVINCE_STATEPROVINCEID',
    'FK_BILLOFMATERIALS_PRODUCT_COMPONENTID',
    'FK_BILLOFMATERIALS_PRODUCT_PRODUCTASSEMBLYID',
    'FK_BILLOFMATERIALS_UNITMEASURE_UNITMEASURECODE',
    'FK_BUSINESSENTITYADDRESS_ADDRESS_ADDRESSID',
    'FK_BUSINESSENTITYADDRESS_ADDRESSTYPE_ADDRESSTYPEID',
    'FK_BUSINESSENTITYADDRESS_BUSINESSENTITY_BUSINESSENTITYID',
    'FK_BUSINESSENTITYCONTACT_BUSINESSENTITY_BUSINESSENTITYID',
    'FK_BUSINESSENTITYCONTACT_CONTACTTYPE_CONTACTTYPEID',
    'FK_BUSINESSENTITYCONTACT_PERSON_PERSONID',
    'FK_COUNTRYREGIONCURRENCY_COUNTRYREGION_COUNTRYREGIONCODE',
    'FK_COUNTRYREGIONCURRENCY_CURRENCY_CURRENCYCODE',
    'FK_CURRENCYRATE_CURRENCY_FROMCURRENCYCODE',
    'FK_CURRENCYRATE_CURRENCY_TOCURRENCYCODE', 'FK_CUSTOMER_PERSON_PERSONID',
    'FK_CUSTOMER_SALESTERRITORY_TERRITORYID',
    'FK_CUSTOMER_STORE_STOREID', 'FK_DOCUMENT_EMPLOYEE_OWNER',
    'FK_EMAILADDRESS_PERSON_BUSINESSENTITYID',
    'FK_EMPLOYEE_PERSON_BUSINESSENTITYID',
    'FK_EMPLOYEEDEPARTMENTHISTORY_DEPARTMENT_DEPARTMENTID',
    'FK_EMPLOYEEDEPARTMENTHISTORY_EMPLOYEE_BUSINESSENTITYID',
    'FK_EMPLOYEEDEPARTMENTHISTORY_SHIFT_SHIFTID',
    'FK_EMPLOYEEPAYHISTORY_EMPLOYEE_BUSINESSENTITYID',
    'FK_JOBCANDIDATE_EMPLOYEE_BUSINESSENTITYID',
    'FK_PASSWORD_PERSON_BUSINESSENTITYID',
    'FK_PERSON_BUSINESSENTITY_BUSINESSENTITYID',
    'FK_PERSONCREDITCARD_CREDITCARD_CREDITCARDID',
    'FK_PERSONCREDITCARD_PERSON_BUSINESSENTITYID',
    'FK_PERSONPHONE_PERSON_BUSINESSENTITYID',
    'FK_PERSONPHONE_PHONENUMBERTYPE_PHONENUMBERTYPEID',
    'FK_PRODUCT_PRODUCTMODEL_PRODUCTMODELID',
    'FK_PRODUCT_PRODUCTSUBCATEGORY_PRODUCTSUBCATEGORYID',
    'FK_PRODUCT_UNITMEASURE_SIZEUNITMEASURECODE',
    'FK_PRODUCT_UNITMEASURE_WEIGHTUNITMEASURECODE',
    'FK_PRODUCTCOSTHISTORY_PRODUCT_PRODUCTID',
    'FK_PRODUCTDOCUMENT_DOCUMENT_DOCUMENTNODE',
    'FK_PRODUCTDOCUMENT_PRODUCT_PRODUCTID',
    'FK_PRODUCTINVENTORY_LOCATION_LOCATIONID',
    'FK_PRODUCTINVENTORY_PRODUCT_PRODUCTID',
    'FK_PRODUCTLISTPRICEHISTORY_PRODUCT_PRODUCTID',
    'FK_PRODUCTMODELILLUSTRATION_ILLUSTRATION_ILLUSTRATIONID',
    'FK_PRODUCTMODELILLUSTRATION_PRODUCTMODEL_PRODUCTMODELID',
    'FK_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE_CULTURE_CULTUREID',
    'FK_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE_PRODUCTDESCRIPTION_PRODUCTDESCRIPTIONID',
    'FK_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE_PRODUCTMODEL_PRODUCTMODELID',
    'FK_PRODUCTPRODUCTPHOTO_PRODUCT_PRODUCTID',
    'FK_PRODUCTPRODUCTPHOTO_PRODUCTPHOTO_PRODUCTPHOTOID',
    'FK_PRODUCTREVIEW_PRODUCT_PRODUCTID',
    'FK_PRODUCTSUBCATEGORY_PRODUCTCATEGORY_PRODUCTCATEGORYID',
    'FK_PRODUCTVENDOR_PRODUCT_PRODUCTID',
    'FK_PRODUCTVENDOR_UNITMEASURE_UNITMEASURECODE',
    'FK_PRODUCTVENDOR_VENDOR_BUSINESSENTITYID',
    'FK_PURCHASEORDERDETAIL_PRODUCT_PRODUCTID',
    'FK_PURCHASEORDERDETAIL_PURCHASEORDERHEADER_PURCHASEORDERID',
    'FK_PURCHASEORDERHEADER_EMPLOYEE_EMPLOYEEID',
    'FK_PURCHASEORDERHEADER_SHIPMETHOD_SHIPMETHODID',
    'FK_PURCHASEORDERHEADER_VENDOR_VENDORID',
    'FK_SALESORDERDETAIL_SALESORDERHEADER_SALESORDERID',
    'FK_SALESORDERDETAIL_SPECIALOFFERPRODUCT_SPECIALOFFERIDPRODUCTID',
    'FK_SALESORDERHEADER_ADDRESS_BILLTOADDRESSID',
    'FK_SALESORDERHEADER_ADDRESS_SHIPTOADDRESSID',
    'FK_SALESORDERHEADER_CREDITCARD_CREDITCARDID',
    'FK_SALESORDERHEADER_CURRENCYRATE_CURRENCYRATEID',
    'FK_SALESORDERHEADER_CUSTOMER_CUSTOMERID',
    'FK_SALESORDERHEADER_SALESPERSON_SALESPERSONID',
    'FK_SALESORDERHEADER_SALESTERRITORY_TERRITORYID',
    'FK_SALESORDERHEADER_SHIPMETHOD_SHIPMETHODID',
    'FK_SALESORDERHEADERSALESREASON_SALESORDERHEADER_SALESORDERID',
    'FK_SALESORDERHEADERSALESREASON_SALESREASON_SALESREASONID',
    'FK_SALESPERSON_EMPLOYEE_BUSINESSENTITYID',
    'FK_SALESPERSON_SALESTERRITORY_TERRITORYID',
    'FK_SALESPERSONQUOTAHISTORY_SALESPERSON_BUSINESSENTITYID',
    'FK_SALESTAXRATE_STATEPROVINCE_STATEPROVINCEID',
    'FK_SALESTERRITORY_COUNTRYREGION_COUNTRYREGIONCODE',
    'FK_SALESTERRITORYHISTORY_SALESPERSON_BUSINESSENTITYID',
    'FK_SALESTERRITORYHISTORY_SALESTERRITORY_TERRITORYID',
    'FK_SHOPPINGCARTITEM_PRODUCT_PRODUCTID',
    'FK_SPECIALOFFERPRODUCT_PRODUCT_PRODUCTID',
    'FK_SPECIALOFFERPRODUCT_SPECIALOFFER_SPECIALOFFERID',
    'FK_STATEPROVINCE_COUNTRYREGION_COUNTRYREGIONCODE',
    'FK_STATEPROVINCE_SALESTERRITORY_TERRITORYID',
    'FK_STORE_BUSINESSENTITY_BUSINESSENTITYID',
    'FK_STORE_SALESPERSON_SALESPERSONID',
    'FK_TRANSACTIONHISTORY_PRODUCT_PRODUCTID',
    'FK_VENDOR_BUSINESSENTITY_BUSINESSENTITYID',
    'FK_WORKORDER_PRODUCT_PRODUCTID',
    'FK_WORKORDER_SCRAPREASON_SCRAPREASONID',
    'FK_WORKORDERROUTING_LOCATION_LOCATIONID',
    'FK_WORKORDERROUTING_WORKORDER_WORKORDERID',
    'IX_ADDRESS_ADDRESSLINE1_ADDRESSLINE2_CITY_STATEPROVINCEID_POSTALCODE',
    'PK_ADDRESS_ADDRESSID', 'PK_ADDRESSTYPE_ADDRESSTYPEID',
    'PK_AWBUILDVERSION_SYSTEMINFORMATIONID',
    'PK_BILLOFMATERIALS_BILLOFMATERIALSID',
    'PK_BUSINESSENTITY_BUSINESSENTITYID',
    'PK_BUSINESSENTITYADDRESS_BUSINESSENTITYID_ADDRESSID_ADDRESSTYPEID',
    'PK_BUSINESSENTITYCONTACT_BUSINESSENTITYID_PERSONID_CONTACTTYPEID',
    'PK_CONTACTTYPE_CONTACTTYPEID', 'PK_COUNTRYREGION_COUNTRYREGIONCODE',
    'PK_COUNTRYREGIONCURRENCY_COUNTRYREGIONCODE_CURRENCYCODE',
    'PK_CREDITCARD_CREDITCARDID', 'PK_CULTURE_CULTUREID',
    'PK_CURRENCY_CURRENCYCODE', 'PK_CURRENCYRATE_CURRENCYRATEID',
    'PK_CUSTOMER_CUSTOMERID', 'PK_DATABASELOG_DATABASELOGID',
    'PK_DEPARTMENT_DEPARTMENTID', 'PK_DOCUMENT_DOCUMENTNODE',
    'PK_EMAILADDRESS_BUSINESSENTITYID_EMAILADDRESSID',
    'PK_EMPLOYEE_BUSINESSENTITYID',
    'PK_EMPLOYEEDEPARTMENTHISTORY_BUSINESSENTITYID_STARTDATE_DEPARTMENTID',
    'PK_EMPLOYEEPAYHISTORY_BUSINESSENTITYID_RATECHANGEDATE',
    'PK_ERRORLOG_ERRORLOGID', 'PK_ILLUSTRATION_ILLUSTRATIONID',
    'PK_JOBCANDIDATE_JOBCANDIDATEID', 'PK_LOCATION_LOCATIONID',
    'PK_PASSWORD_BUSINESSENTITYID', 'PK_PERSON_BUSINESSENTITYID',
    'PK_PERSONCREDITCARD_BUSINESSENTITYID_CREDITCARDID',
    'PK_PERSONPHONE_BUSINESSENTITYID_PHONENUMBER_PHONENUMBERTYPEID',
    'PK_PHONENUMBERTYPE_PHONENUMBERTYPEID', 'PK_PRODUCT_PRODUCTID',
    'PK_PRODUCTCATEGORY_PRODUCTCATEGORYID',
    'PK_PRODUCTCOSTHISTORY_PRODUCTID_STARTDATE',
    'PK_PRODUCTDESCRIPTION_PRODUCTDESCRIPTIONID',
    'PK_PRODUCTDOCUMENT_PRODUCTID_DOCUMENTNODE',
    'PK_PRODUCTINVENTORY_PRODUCTID_LOCATIONID',
    'PK_PRODUCTLISTPRICEHISTORY_PRODUCTID_STARTDATE',
    'PK_PRODUCTMODEL_PRODUCTMODELID',
    'PK_PRODUCTMODELILLUSTRATION_PRODUCTMODELID_ILLUSTRATIONID',
    'PK_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE_PRODUCTMODELID_PRODUCTDESCRIPTIONID_CULTUREID',
    'PK_PRODUCTPHOTO_PRODUCTPHOTOID',
    'PK_PRODUCTPRODUCTPHOTO_PRODUCTID_PRODUCTPHOTOID',
    'PK_PRODUCTREVIEW_PRODUCTREVIEWID',
    'PK_PRODUCTSUBCATEGORY_PRODUCTSUBCATEGORYID',
    'PK_PRODUCTVENDOR_PRODUCTID_BUSINESSENTITYID',
    'PK_PURCHASEORDERDETAIL_PURCHASEORDERID_PURCHASEORDERDETAILID',
    'PK_PURCHASEORDERHEADER_PURCHASEORDERID',
    'PK_SALESORDERDETAIL_SALESORDERID_SALESORDERDETAILID',
    'PK_SALESORDERHEADER_SALESORDERID',
    'PK_SALESORDERHEADERSALESREASON_SALESORDERID_SALESREASONID',
    'PK_SALESPERSON_BUSINESSENTITYID',
    'PK_SALESPERSONQUOTAHISTORY_BUSINESSENTITYID_QUOTADATE',
    'PK_SALESREASON_SALESREASONID', 'PK_SALESTAXRATE_SALESTAXRATEID',
    'PK_SALESTERRITORY_TERRITORYID',
    'PK_SALESTERRITORYHISTORY_BUSINESSENTITYID_STARTDATE_TERRITORYID',
    'PK_SCRAPREASON_SCRAPREASONID', 'PK_SHIFT_SHIFTID',
    'PK_SHIPMETHOD_SHIPMETHODID', 'PK_SHOPPINGCARTITEM_SHOPPINGCARTITEMID',
    'PK_SPECIALOFFER_SPECIALOFFERID',
    'PK_SPECIALOFFERPRODUCT_SPECIALOFFERID_PRODUCTID',
    'PK_STATEPROVINCE_STATEPROVINCEID', 'PK_STORE_BUSINESSENTITYID',
    'PK_TRANSACTIONHISTORY_TRANSACTIONID',
    'PK_TRANSACTIONHISTORYARCHIVE_TRANSACTIONID',
    'PK_UNITMEASURE_UNITMEASURECODE', 'PK_VENDOR_BUSINESSENTITYID',
    'PK_WORKORDER_WORKORDERID',
    'PK_WORKORDERROUTING_WORKORDERID_PRODUCTID_OPERATIONSEQUENCE'
  ))
),
expected_indexes AS (
  SELECT COLUMN_VALUE AS OBJECT_NAME
  FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'IX_AW_01', 'IX_AW_02', 'IX_AW_03', 'IX_AW_04', 'IX_AW_05',
    'IX_AW_06', 'IX_AW_07', 'IX_AW_08', 'IX_AW_09', 'IX_AW_10',
    'IX_AW_11', 'IX_AW_12', 'IX_AW_13', 'IX_AW_14', 'IX_AW_15',
    'IX_AW_16', 'IX_AW_17', 'IX_AW_18', 'IX_AW_19', 'IX_AW_20'
  ))
),
expected_functions AS (
  SELECT COLUMN_VALUE AS OBJECT_NAME
  FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'DBO_UFNGETACCOUNTINGSTARTDATE', 'DBO_UFNGETACCOUNTINGENDDATE',
    'DBO_UFNLEADINGZEROS', 'DBO_UFNGETDOCUMENTSTATUSTEXT',
    'DBO_UFNGETPURCHASEORDERSTATUSTEXT',
    'DBO_UFNGETSALESORDERSTATUSTEXT', 'DBO_UFNGETSTOCK'
  ))
),
expected_procedures AS (
  SELECT COLUMN_VALUE AS OBJECT_NAME
  FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'DBO_USPGETBILLOFMATERIALS', 'DBO_USPGETEMPLOYEEMANAGERS'
  ))
),
expected_views AS (
  SELECT COLUMN_VALUE AS OBJECT_NAME
  FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'PERSON_VSTATEPROVINCECOUNTRYREGION',
    'PRODUCTION_VPRODUCTANDDESCRIPTION', 'HUMANRESOURCES_VEMPLOYEE',
    'SALES_VINDIVIDUALCUSTOMER', 'SALES_VSALESPERSON'
  ))
),
expected_objects AS (
  SELECT 'ADVENTUREWORKS2022' AS OBJECT_NAME, 'USER' AS OBJECT_TYPE FROM DUAL
  UNION ALL
  SELECT 'ADVENTUREWORKS2022', 'SCHEMA' FROM DUAL
  UNION ALL
  SELECT OBJECT_NAME, 'TABLE' FROM expected_tables
  UNION ALL
  SELECT OBJECT_NAME, 'CONSTRAINT' FROM expected_constraints
  UNION ALL
  SELECT OBJECT_NAME, 'INDEX' FROM expected_indexes
  UNION ALL
  SELECT OBJECT_NAME, 'FUNCTION' FROM expected_functions
  UNION ALL
  SELECT OBJECT_NAME, 'PROCEDURE' FROM expected_procedures
  UNION ALL
  SELECT OBJECT_NAME, 'VIEW' FROM expected_views
)
SELECT E.OBJECT_NAME,
       E.OBJECT_TYPE,
       CASE
         WHEN E.OBJECT_TYPE IN ('USER', 'SCHEMA')
          AND EXISTS (
            SELECT 1 FROM ALL_USERS U
            WHERE U.USERNAME = E.OBJECT_NAME
          )
         THEN 'YES'
         WHEN E.OBJECT_TYPE = 'CONSTRAINT'
          AND EXISTS (
            SELECT 1 FROM ALL_CONSTRAINTS C
            WHERE C.OWNER = 'ADVENTUREWORKS2022'
              AND C.CONSTRAINT_NAME = E.OBJECT_NAME
          )
         THEN 'YES'
         WHEN E.OBJECT_TYPE NOT IN ('USER', 'SCHEMA', 'CONSTRAINT')
          AND EXISTS (
            SELECT 1 FROM ALL_OBJECTS O
            WHERE O.OWNER = 'ADVENTUREWORKS2022'
              AND O.OBJECT_NAME = E.OBJECT_NAME
              AND O.OBJECT_TYPE = E.OBJECT_TYPE
          )
         THEN 'YES'
         ELSE 'NO'
       END AS CREATED_OR_NOT
FROM expected_objects E
ORDER BY CASE E.OBJECT_TYPE
           WHEN 'USER' THEN 1
           WHEN 'SCHEMA' THEN 2
           WHEN 'TABLE' THEN 3
           WHEN 'CONSTRAINT' THEN 4
           WHEN 'INDEX' THEN 5
           WHEN 'FUNCTION' THEN 6
           WHEN 'PROCEDURE' THEN 7
           WHEN 'VIEW' THEN 8
           ELSE 9
         END,
         E.OBJECT_NAME;
