-- =============================================================================
-- Purpose          : Add relational and business-rule constraints to the
--                    AdventureWorks2022 source tables.
-- Execution order  : 03 of 07; run after 02_create_tables.sql.
-- Connection user  : SYSTEM; CURRENT_SCHEMA is set to ADVENTUREWORKS2022.
-- Objects affected : Foreign keys, alternate keys, and portable check
--                    constraints across all source domains.
-- Notes            : Primary keys are created with their tables. SQL Server-
--                    specific checks that cannot be represented faithfully in
--                    Oracle XE 21c remain intentionally omitted.
-- =============================================================================

ALTER SESSION SET CURRENT_SCHEMA = ADVENTUREWORKS2022;

-- Foreign-key relationships

ALTER TABLE HUMANRESOURCES_EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_PERSON_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES PERSON_PERSON (BUSINESSENTITYID);

ALTER TABLE HUMANRESOURCES_EMPLOYEEDEPARTMENTHISTORY ADD CONSTRAINT FK_EMPLOYEEDEPARTMENTHISTORY_DEPARTMENT_DEPARTMENTID
  FOREIGN KEY (DEPARTMENTID) REFERENCES HUMANRESOURCES_DEPARTMENT (DEPARTMENTID);

ALTER TABLE HUMANRESOURCES_EMPLOYEEDEPARTMENTHISTORY ADD CONSTRAINT FK_EMPLOYEEDEPARTMENTHISTORY_EMPLOYEE_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES HUMANRESOURCES_EMPLOYEE (BUSINESSENTITYID);

ALTER TABLE HUMANRESOURCES_EMPLOYEEDEPARTMENTHISTORY ADD CONSTRAINT FK_EMPLOYEEDEPARTMENTHISTORY_SHIFT_SHIFTID
  FOREIGN KEY (SHIFTID) REFERENCES HUMANRESOURCES_SHIFT (SHIFTID);

ALTER TABLE HUMANRESOURCES_EMPLOYEEPAYHISTORY ADD CONSTRAINT FK_EMPLOYEEPAYHISTORY_EMPLOYEE_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES HUMANRESOURCES_EMPLOYEE (BUSINESSENTITYID);

ALTER TABLE HUMANRESOURCES_JOBCANDIDATE ADD CONSTRAINT FK_JOBCANDIDATE_EMPLOYEE_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES HUMANRESOURCES_EMPLOYEE (BUSINESSENTITYID);

ALTER TABLE PERSON_ADDRESS ADD CONSTRAINT FK_ADDRESS_STATEPROVINCE_STATEPROVINCEID
  FOREIGN KEY (STATEPROVINCEID) REFERENCES PERSON_STATEPROVINCE (STATEPROVINCEID);

ALTER TABLE PERSON_BUSINESSENTITYADDRESS ADD CONSTRAINT FK_BUSINESSENTITYADDRESS_ADDRESS_ADDRESSID
  FOREIGN KEY (ADDRESSID) REFERENCES PERSON_ADDRESS (ADDRESSID);

ALTER TABLE PERSON_BUSINESSENTITYADDRESS ADD CONSTRAINT FK_BUSINESSENTITYADDRESS_ADDRESSTYPE_ADDRESSTYPEID
  FOREIGN KEY (ADDRESSTYPEID) REFERENCES PERSON_ADDRESSTYPE (ADDRESSTYPEID);

ALTER TABLE PERSON_BUSINESSENTITYADDRESS ADD CONSTRAINT FK_BUSINESSENTITYADDRESS_BUSINESSENTITY_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES PERSON_BUSINESSENTITY (BUSINESSENTITYID);

ALTER TABLE PERSON_BUSINESSENTITYCONTACT ADD CONSTRAINT FK_BUSINESSENTITYCONTACT_BUSINESSENTITY_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES PERSON_BUSINESSENTITY (BUSINESSENTITYID);

ALTER TABLE PERSON_BUSINESSENTITYCONTACT ADD CONSTRAINT FK_BUSINESSENTITYCONTACT_CONTACTTYPE_CONTACTTYPEID
  FOREIGN KEY (CONTACTTYPEID) REFERENCES PERSON_CONTACTTYPE (CONTACTTYPEID);

ALTER TABLE PERSON_BUSINESSENTITYCONTACT ADD CONSTRAINT FK_BUSINESSENTITYCONTACT_PERSON_PERSONID
  FOREIGN KEY (PERSONID) REFERENCES PERSON_PERSON (BUSINESSENTITYID);

ALTER TABLE PERSON_EMAILADDRESS ADD CONSTRAINT FK_EMAILADDRESS_PERSON_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES PERSON_PERSON (BUSINESSENTITYID);

ALTER TABLE PERSON_PASSWORD ADD CONSTRAINT FK_PASSWORD_PERSON_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES PERSON_PERSON (BUSINESSENTITYID);

ALTER TABLE PERSON_PERSON ADD CONSTRAINT FK_PERSON_BUSINESSENTITY_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES PERSON_BUSINESSENTITY (BUSINESSENTITYID);

ALTER TABLE PERSON_PERSONPHONE ADD CONSTRAINT FK_PERSONPHONE_PERSON_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES PERSON_PERSON (BUSINESSENTITYID);

ALTER TABLE PERSON_PERSONPHONE ADD CONSTRAINT FK_PERSONPHONE_PHONENUMBERTYPE_PHONENUMBERTYPEID
  FOREIGN KEY (PHONENUMBERTYPEID) REFERENCES PERSON_PHONENUMBERTYPE (PHONENUMBERTYPEID);

ALTER TABLE PERSON_STATEPROVINCE ADD CONSTRAINT FK_STATEPROVINCE_COUNTRYREGION_COUNTRYREGIONCODE
  FOREIGN KEY (COUNTRYREGIONCODE) REFERENCES PERSON_COUNTRYREGION (COUNTRYREGIONCODE);

ALTER TABLE PERSON_STATEPROVINCE ADD CONSTRAINT FK_STATEPROVINCE_SALESTERRITORY_TERRITORYID
  FOREIGN KEY (TERRITORYID) REFERENCES SALES_SALESTERRITORY (TERRITORYID);

ALTER TABLE PRODUCTION_BILLOFMATERIALS ADD CONSTRAINT FK_BILLOFMATERIALS_PRODUCT_COMPONENTID
  FOREIGN KEY (COMPONENTID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE PRODUCTION_BILLOFMATERIALS ADD CONSTRAINT FK_BILLOFMATERIALS_PRODUCT_PRODUCTASSEMBLYID
  FOREIGN KEY (PRODUCTASSEMBLYID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE PRODUCTION_BILLOFMATERIALS ADD CONSTRAINT FK_BILLOFMATERIALS_UNITMEASURE_UNITMEASURECODE
  FOREIGN KEY (UNITMEASURECODE) REFERENCES PRODUCTION_UNITMEASURE (UNITMEASURECODE);

ALTER TABLE PRODUCTION_DOCUMENT ADD CONSTRAINT FK_DOCUMENT_EMPLOYEE_OWNER
  FOREIGN KEY (OWNER) REFERENCES HUMANRESOURCES_EMPLOYEE (BUSINESSENTITYID);

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT FK_PRODUCT_PRODUCTMODEL_PRODUCTMODELID
  FOREIGN KEY (PRODUCTMODELID) REFERENCES PRODUCTION_PRODUCTMODEL (PRODUCTMODELID);

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT FK_PRODUCT_PRODUCTSUBCATEGORY_PRODUCTSUBCATEGORYID
  FOREIGN KEY (PRODUCTSUBCATEGORYID) REFERENCES PRODUCTION_PRODUCTSUBCATEGORY (PRODUCTSUBCATEGORYID);

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT FK_PRODUCT_UNITMEASURE_SIZEUNITMEASURECODE
  FOREIGN KEY (SIZEUNITMEASURECODE) REFERENCES PRODUCTION_UNITMEASURE (UNITMEASURECODE);

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT FK_PRODUCT_UNITMEASURE_WEIGHTUNITMEASURECODE
  FOREIGN KEY (WEIGHTUNITMEASURECODE) REFERENCES PRODUCTION_UNITMEASURE (UNITMEASURECODE);

ALTER TABLE PRODUCTION_PRODUCTCOSTHISTORY ADD CONSTRAINT FK_PRODUCTCOSTHISTORY_PRODUCT_PRODUCTID
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE PRODUCTION_PRODUCTDOCUMENT ADD CONSTRAINT FK_PRODUCTDOCUMENT_DOCUMENT_DOCUMENTNODE
  FOREIGN KEY (DOCUMENTNODE) REFERENCES PRODUCTION_DOCUMENT (DOCUMENTNODE);

ALTER TABLE PRODUCTION_PRODUCTDOCUMENT ADD CONSTRAINT FK_PRODUCTDOCUMENT_PRODUCT_PRODUCTID
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE PRODUCTION_PRODUCTINVENTORY ADD CONSTRAINT FK_PRODUCTINVENTORY_LOCATION_LOCATIONID
  FOREIGN KEY (LOCATIONID) REFERENCES PRODUCTION_LOCATION (LOCATIONID);

ALTER TABLE PRODUCTION_PRODUCTINVENTORY ADD CONSTRAINT FK_PRODUCTINVENTORY_PRODUCT_PRODUCTID
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE PRODUCTION_PRODUCTLISTPRICEHISTORY ADD CONSTRAINT FK_PRODUCTLISTPRICEHISTORY_PRODUCT_PRODUCTID
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE PRODUCTION_PRODUCTMODELILLUSTRATION ADD CONSTRAINT FK_PRODUCTMODELILLUSTRATION_ILLUSTRATION_ILLUSTRATIONID
  FOREIGN KEY (ILLUSTRATIONID) REFERENCES PRODUCTION_ILLUSTRATION (ILLUSTRATIONID);

ALTER TABLE PRODUCTION_PRODUCTMODELILLUSTRATION ADD CONSTRAINT FK_PRODUCTMODELILLUSTRATION_PRODUCTMODEL_PRODUCTMODELID
  FOREIGN KEY (PRODUCTMODELID) REFERENCES PRODUCTION_PRODUCTMODEL (PRODUCTMODELID);

ALTER TABLE PRODUCTION_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE ADD CONSTRAINT FK_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE_CULTURE_CULTUREID
  FOREIGN KEY (CULTUREID) REFERENCES PRODUCTION_CULTURE (CULTUREID);

ALTER TABLE PRODUCTION_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE ADD CONSTRAINT FK_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE_PRODUCTDESCRIPTION_PRODUCTDESCRIPTIONID
  FOREIGN KEY (PRODUCTDESCRIPTIONID) REFERENCES PRODUCTION_PRODUCTDESCRIPTION (PRODUCTDESCRIPTIONID);

ALTER TABLE PRODUCTION_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE ADD CONSTRAINT FK_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE_PRODUCTMODEL_PRODUCTMODELID
  FOREIGN KEY (PRODUCTMODELID) REFERENCES PRODUCTION_PRODUCTMODEL (PRODUCTMODELID);

ALTER TABLE PRODUCTION_PRODUCTPRODUCTPHOTO ADD CONSTRAINT FK_PRODUCTPRODUCTPHOTO_PRODUCT_PRODUCTID
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE PRODUCTION_PRODUCTPRODUCTPHOTO ADD CONSTRAINT FK_PRODUCTPRODUCTPHOTO_PRODUCTPHOTO_PRODUCTPHOTOID
  FOREIGN KEY (PRODUCTPHOTOID) REFERENCES PRODUCTION_PRODUCTPHOTO (PRODUCTPHOTOID);

ALTER TABLE PRODUCTION_PRODUCTREVIEW ADD CONSTRAINT FK_PRODUCTREVIEW_PRODUCT_PRODUCTID
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE PRODUCTION_PRODUCTSUBCATEGORY ADD CONSTRAINT FK_PRODUCTSUBCATEGORY_PRODUCTCATEGORY_PRODUCTCATEGORYID
  FOREIGN KEY (PRODUCTCATEGORYID) REFERENCES PRODUCTION_PRODUCTCATEGORY (PRODUCTCATEGORYID);

ALTER TABLE PRODUCTION_TRANSACTIONHISTORY ADD CONSTRAINT FK_TRANSACTIONHISTORY_PRODUCT_PRODUCTID
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE PRODUCTION_WORKORDER ADD CONSTRAINT FK_WORKORDER_PRODUCT_PRODUCTID
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE PRODUCTION_WORKORDER ADD CONSTRAINT FK_WORKORDER_SCRAPREASON_SCRAPREASONID
  FOREIGN KEY (SCRAPREASONID) REFERENCES PRODUCTION_SCRAPREASON (SCRAPREASONID);

ALTER TABLE PRODUCTION_WORKORDERROUTING ADD CONSTRAINT FK_WORKORDERROUTING_LOCATION_LOCATIONID
  FOREIGN KEY (LOCATIONID) REFERENCES PRODUCTION_LOCATION (LOCATIONID);

ALTER TABLE PRODUCTION_WORKORDERROUTING ADD CONSTRAINT FK_WORKORDERROUTING_WORKORDER_WORKORDERID
  FOREIGN KEY (WORKORDERID) REFERENCES PRODUCTION_WORKORDER (WORKORDERID);

ALTER TABLE PURCHASING_PRODUCTVENDOR ADD CONSTRAINT FK_PRODUCTVENDOR_PRODUCT_PRODUCTID
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE PURCHASING_PRODUCTVENDOR ADD CONSTRAINT FK_PRODUCTVENDOR_UNITMEASURE_UNITMEASURECODE
  FOREIGN KEY (UNITMEASURECODE) REFERENCES PRODUCTION_UNITMEASURE (UNITMEASURECODE);

ALTER TABLE PURCHASING_PRODUCTVENDOR ADD CONSTRAINT FK_PRODUCTVENDOR_VENDOR_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES PURCHASING_VENDOR (BUSINESSENTITYID);

ALTER TABLE PURCHASING_PURCHASEORDERDETAIL ADD CONSTRAINT FK_PURCHASEORDERDETAIL_PRODUCT_PRODUCTID
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE PURCHASING_PURCHASEORDERDETAIL ADD CONSTRAINT FK_PURCHASEORDERDETAIL_PURCHASEORDERHEADER_PURCHASEORDERID
  FOREIGN KEY (PURCHASEORDERID) REFERENCES PURCHASING_PURCHASEORDERHEADER (PURCHASEORDERID);

ALTER TABLE PURCHASING_PURCHASEORDERHEADER ADD CONSTRAINT FK_PURCHASEORDERHEADER_EMPLOYEE_EMPLOYEEID
  FOREIGN KEY (EMPLOYEEID) REFERENCES HUMANRESOURCES_EMPLOYEE (BUSINESSENTITYID);

ALTER TABLE PURCHASING_PURCHASEORDERHEADER ADD CONSTRAINT FK_PURCHASEORDERHEADER_SHIPMETHOD_SHIPMETHODID
  FOREIGN KEY (SHIPMETHODID) REFERENCES PURCHASING_SHIPMETHOD (SHIPMETHODID);

ALTER TABLE PURCHASING_PURCHASEORDERHEADER ADD CONSTRAINT FK_PURCHASEORDERHEADER_VENDOR_VENDORID
  FOREIGN KEY (VENDORID) REFERENCES PURCHASING_VENDOR (BUSINESSENTITYID);

ALTER TABLE PURCHASING_VENDOR ADD CONSTRAINT FK_VENDOR_BUSINESSENTITY_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES PERSON_BUSINESSENTITY (BUSINESSENTITYID);

ALTER TABLE SALES_COUNTRYREGIONCURRENCY ADD CONSTRAINT FK_COUNTRYREGIONCURRENCY_COUNTRYREGION_COUNTRYREGIONCODE
  FOREIGN KEY (COUNTRYREGIONCODE) REFERENCES PERSON_COUNTRYREGION (COUNTRYREGIONCODE);

ALTER TABLE SALES_COUNTRYREGIONCURRENCY ADD CONSTRAINT FK_COUNTRYREGIONCURRENCY_CURRENCY_CURRENCYCODE
  FOREIGN KEY (CURRENCYCODE) REFERENCES SALES_CURRENCY (CURRENCYCODE);

ALTER TABLE SALES_CURRENCYRATE ADD CONSTRAINT FK_CURRENCYRATE_CURRENCY_FROMCURRENCYCODE
  FOREIGN KEY (FROMCURRENCYCODE) REFERENCES SALES_CURRENCY (CURRENCYCODE);

ALTER TABLE SALES_CURRENCYRATE ADD CONSTRAINT FK_CURRENCYRATE_CURRENCY_TOCURRENCYCODE
  FOREIGN KEY (TOCURRENCYCODE) REFERENCES SALES_CURRENCY (CURRENCYCODE);

ALTER TABLE SALES_CUSTOMER ADD CONSTRAINT FK_CUSTOMER_PERSON_PERSONID
  FOREIGN KEY (PERSONID) REFERENCES PERSON_PERSON (BUSINESSENTITYID);

ALTER TABLE SALES_CUSTOMER ADD CONSTRAINT FK_CUSTOMER_SALESTERRITORY_TERRITORYID
  FOREIGN KEY (TERRITORYID) REFERENCES SALES_SALESTERRITORY (TERRITORYID);

ALTER TABLE SALES_CUSTOMER ADD CONSTRAINT FK_CUSTOMER_STORE_STOREID
  FOREIGN KEY (STOREID) REFERENCES SALES_STORE (BUSINESSENTITYID);

ALTER TABLE SALES_PERSONCREDITCARD ADD CONSTRAINT FK_PERSONCREDITCARD_CREDITCARD_CREDITCARDID
  FOREIGN KEY (CREDITCARDID) REFERENCES SALES_CREDITCARD (CREDITCARDID);

ALTER TABLE SALES_PERSONCREDITCARD ADD CONSTRAINT FK_PERSONCREDITCARD_PERSON_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES PERSON_PERSON (BUSINESSENTITYID);

ALTER TABLE SALES_SALESORDERDETAIL ADD CONSTRAINT FK_SALESORDERDETAIL_SALESORDERHEADER_SALESORDERID
  FOREIGN KEY (SALESORDERID) REFERENCES SALES_SALESORDERHEADER (SALESORDERID);

ALTER TABLE SALES_SALESORDERDETAIL ADD CONSTRAINT FK_SALESORDERDETAIL_SPECIALOFFERPRODUCT_SPECIALOFFERIDPRODUCTID
  FOREIGN KEY (SPECIALOFFERID, PRODUCTID) REFERENCES SALES_SPECIALOFFERPRODUCT (SPECIALOFFERID, PRODUCTID);

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT FK_SALESORDERHEADER_ADDRESS_BILLTOADDRESSID
  FOREIGN KEY (BILLTOADDRESSID) REFERENCES PERSON_ADDRESS (ADDRESSID);

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT FK_SALESORDERHEADER_ADDRESS_SHIPTOADDRESSID
  FOREIGN KEY (SHIPTOADDRESSID) REFERENCES PERSON_ADDRESS (ADDRESSID);

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT FK_SALESORDERHEADER_CREDITCARD_CREDITCARDID
  FOREIGN KEY (CREDITCARDID) REFERENCES SALES_CREDITCARD (CREDITCARDID);

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT FK_SALESORDERHEADER_CURRENCYRATE_CURRENCYRATEID
  FOREIGN KEY (CURRENCYRATEID) REFERENCES SALES_CURRENCYRATE (CURRENCYRATEID);

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT FK_SALESORDERHEADER_CUSTOMER_CUSTOMERID
  FOREIGN KEY (CUSTOMERID) REFERENCES SALES_CUSTOMER (CUSTOMERID);

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT FK_SALESORDERHEADER_SALESPERSON_SALESPERSONID
  FOREIGN KEY (SALESPERSONID) REFERENCES SALES_SALESPERSON (BUSINESSENTITYID);

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT FK_SALESORDERHEADER_SALESTERRITORY_TERRITORYID
  FOREIGN KEY (TERRITORYID) REFERENCES SALES_SALESTERRITORY (TERRITORYID);

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT FK_SALESORDERHEADER_SHIPMETHOD_SHIPMETHODID
  FOREIGN KEY (SHIPMETHODID) REFERENCES PURCHASING_SHIPMETHOD (SHIPMETHODID);

ALTER TABLE SALES_SALESORDERHEADERSALESREASON ADD CONSTRAINT FK_SALESORDERHEADERSALESREASON_SALESORDERHEADER_SALESORDERID
  FOREIGN KEY (SALESORDERID) REFERENCES SALES_SALESORDERHEADER (SALESORDERID);

ALTER TABLE SALES_SALESORDERHEADERSALESREASON ADD CONSTRAINT FK_SALESORDERHEADERSALESREASON_SALESREASON_SALESREASONID
  FOREIGN KEY (SALESREASONID) REFERENCES SALES_SALESREASON (SALESREASONID);

ALTER TABLE SALES_SALESPERSON ADD CONSTRAINT FK_SALESPERSON_EMPLOYEE_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES HUMANRESOURCES_EMPLOYEE (BUSINESSENTITYID);

ALTER TABLE SALES_SALESPERSON ADD CONSTRAINT FK_SALESPERSON_SALESTERRITORY_TERRITORYID
  FOREIGN KEY (TERRITORYID) REFERENCES SALES_SALESTERRITORY (TERRITORYID);

ALTER TABLE SALES_SALESPERSONQUOTAHISTORY ADD CONSTRAINT FK_SALESPERSONQUOTAHISTORY_SALESPERSON_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES SALES_SALESPERSON (BUSINESSENTITYID);

ALTER TABLE SALES_SALESTAXRATE ADD CONSTRAINT FK_SALESTAXRATE_STATEPROVINCE_STATEPROVINCEID
  FOREIGN KEY (STATEPROVINCEID) REFERENCES PERSON_STATEPROVINCE (STATEPROVINCEID);

ALTER TABLE SALES_SALESTERRITORY ADD CONSTRAINT FK_SALESTERRITORY_COUNTRYREGION_COUNTRYREGIONCODE
  FOREIGN KEY (COUNTRYREGIONCODE) REFERENCES PERSON_COUNTRYREGION (COUNTRYREGIONCODE);

ALTER TABLE SALES_SALESTERRITORYHISTORY ADD CONSTRAINT FK_SALESTERRITORYHISTORY_SALESPERSON_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES SALES_SALESPERSON (BUSINESSENTITYID);

ALTER TABLE SALES_SALESTERRITORYHISTORY ADD CONSTRAINT FK_SALESTERRITORYHISTORY_SALESTERRITORY_TERRITORYID
  FOREIGN KEY (TERRITORYID) REFERENCES SALES_SALESTERRITORY (TERRITORYID);

ALTER TABLE SALES_SHOPPINGCARTITEM ADD CONSTRAINT FK_SHOPPINGCARTITEM_PRODUCT_PRODUCTID
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE SALES_SPECIALOFFERPRODUCT ADD CONSTRAINT FK_SPECIALOFFERPRODUCT_PRODUCT_PRODUCTID
  FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTION_PRODUCT (PRODUCTID);

ALTER TABLE SALES_SPECIALOFFERPRODUCT ADD CONSTRAINT FK_SPECIALOFFERPRODUCT_SPECIALOFFER_SPECIALOFFERID
  FOREIGN KEY (SPECIALOFFERID) REFERENCES SALES_SPECIALOFFER (SPECIALOFFERID);

ALTER TABLE SALES_STORE ADD CONSTRAINT FK_STORE_BUSINESSENTITY_BUSINESSENTITYID
  FOREIGN KEY (BUSINESSENTITYID) REFERENCES PERSON_BUSINESSENTITY (BUSINESSENTITYID);

ALTER TABLE SALES_STORE ADD CONSTRAINT FK_STORE_SALESPERSON_SALESPERSONID
  FOREIGN KEY (SALESPERSONID) REFERENCES SALES_SALESPERSON (BUSINESSENTITYID);


-- Alternate keys converted from SQL Server unique indexes

ALTER TABLE HUMANRESOURCES_DEPARTMENT ADD CONSTRAINT AK_DEPARTMENT_NAME UNIQUE (NAME);

ALTER TABLE HUMANRESOURCES_EMPLOYEE ADD CONSTRAINT AK_EMPLOYEE_LOGINID UNIQUE (LOGINID);

ALTER TABLE HUMANRESOURCES_EMPLOYEE ADD CONSTRAINT AK_EMPLOYEE_NATIONALIDNUMBER UNIQUE (NATIONALIDNUMBER);

ALTER TABLE HUMANRESOURCES_EMPLOYEE ADD CONSTRAINT AK_EMPLOYEE_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE HUMANRESOURCES_SHIFT ADD CONSTRAINT AK_SHIFT_NAME UNIQUE (NAME);

ALTER TABLE HUMANRESOURCES_SHIFT ADD CONSTRAINT AK_SHIFT_STARTTIME_ENDTIME UNIQUE (STARTTIME, ENDTIME);

ALTER TABLE PERSON_ADDRESS ADD CONSTRAINT AK_ADDRESS_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PERSON_ADDRESS ADD CONSTRAINT IX_ADDRESS_ADDRESSLINE1_ADDRESSLINE2_CITY_STATEPROVINCEID_POSTALCODE UNIQUE (ADDRESSLINE1, ADDRESSLINE2, CITY, STATEPROVINCEID, POSTALCODE);

ALTER TABLE PERSON_ADDRESSTYPE ADD CONSTRAINT AK_ADDRESSTYPE_NAME UNIQUE (NAME);

ALTER TABLE PERSON_ADDRESSTYPE ADD CONSTRAINT AK_ADDRESSTYPE_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PERSON_BUSINESSENTITY ADD CONSTRAINT AK_BUSINESSENTITY_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PERSON_BUSINESSENTITYADDRESS ADD CONSTRAINT AK_BUSINESSENTITYADDRESS_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PERSON_BUSINESSENTITYCONTACT ADD CONSTRAINT AK_BUSINESSENTITYCONTACT_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PERSON_CONTACTTYPE ADD CONSTRAINT AK_CONTACTTYPE_NAME UNIQUE (NAME);

ALTER TABLE PERSON_COUNTRYREGION ADD CONSTRAINT AK_COUNTRYREGION_NAME UNIQUE (NAME);

ALTER TABLE PERSON_PERSON ADD CONSTRAINT AK_PERSON_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PERSON_STATEPROVINCE ADD CONSTRAINT AK_STATEPROVINCE_NAME UNIQUE (NAME);

ALTER TABLE PERSON_STATEPROVINCE ADD CONSTRAINT AK_STATEPROVINCE_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PERSON_STATEPROVINCE ADD CONSTRAINT AK_STATEPROVINCE_STATEPROVINCECODE_COUNTRYREGIONCODE UNIQUE (STATEPROVINCECODE, COUNTRYREGIONCODE);

ALTER TABLE PRODUCTION_CULTURE ADD CONSTRAINT AK_CULTURE_NAME UNIQUE (NAME);

ALTER TABLE PRODUCTION_DOCUMENT ADD CONSTRAINT AK_DOCUMENT_DOCUMENTLEVEL_DOCUMENTNODE UNIQUE (DOCUMENTLEVEL, DOCUMENTNODE);

ALTER TABLE PRODUCTION_DOCUMENT ADD CONSTRAINT AK_DOCUMENT_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PRODUCTION_LOCATION ADD CONSTRAINT AK_LOCATION_NAME UNIQUE (NAME);

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT AK_PRODUCT_NAME UNIQUE (NAME);

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT AK_PRODUCT_PRODUCTNUMBER UNIQUE (PRODUCTNUMBER);

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT AK_PRODUCT_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PRODUCTION_PRODUCTCATEGORY ADD CONSTRAINT AK_PRODUCTCATEGORY_NAME UNIQUE (NAME);

ALTER TABLE PRODUCTION_PRODUCTCATEGORY ADD CONSTRAINT AK_PRODUCTCATEGORY_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PRODUCTION_PRODUCTDESCRIPTION ADD CONSTRAINT AK_PRODUCTDESCRIPTION_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PRODUCTION_PRODUCTMODEL ADD CONSTRAINT AK_PRODUCTMODEL_NAME UNIQUE (NAME);

ALTER TABLE PRODUCTION_PRODUCTMODEL ADD CONSTRAINT AK_PRODUCTMODEL_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PRODUCTION_PRODUCTSUBCATEGORY ADD CONSTRAINT AK_PRODUCTSUBCATEGORY_NAME UNIQUE (NAME);

ALTER TABLE PRODUCTION_PRODUCTSUBCATEGORY ADD CONSTRAINT AK_PRODUCTSUBCATEGORY_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PRODUCTION_SCRAPREASON ADD CONSTRAINT AK_SCRAPREASON_NAME UNIQUE (NAME);

ALTER TABLE PRODUCTION_UNITMEASURE ADD CONSTRAINT AK_UNITMEASURE_NAME UNIQUE (NAME);

ALTER TABLE PURCHASING_SHIPMETHOD ADD CONSTRAINT AK_SHIPMETHOD_NAME UNIQUE (NAME);

ALTER TABLE PURCHASING_SHIPMETHOD ADD CONSTRAINT AK_SHIPMETHOD_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE PURCHASING_VENDOR ADD CONSTRAINT AK_VENDOR_ACCOUNTNUMBER UNIQUE (ACCOUNTNUMBER);

ALTER TABLE SALES_CREDITCARD ADD CONSTRAINT AK_CREDITCARD_CARDNUMBER UNIQUE (CARDNUMBER);

ALTER TABLE SALES_CURRENCY ADD CONSTRAINT AK_CURRENCY_NAME UNIQUE (NAME);

ALTER TABLE SALES_CURRENCYRATE ADD CONSTRAINT AK_CURRENCYRATE_CURRENCYRATEDATE_FROMCURRENCYCODE_TOCURRENCYCODE UNIQUE (CURRENCYRATEDATE, FROMCURRENCYCODE, TOCURRENCYCODE);

ALTER TABLE SALES_CUSTOMER ADD CONSTRAINT AK_CUSTOMER_ACCOUNTNUMBER UNIQUE (ACCOUNTNUMBER);

ALTER TABLE SALES_CUSTOMER ADD CONSTRAINT AK_CUSTOMER_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE SALES_SALESORDERDETAIL ADD CONSTRAINT AK_SALESORDERDETAIL_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT AK_SALESORDERHEADER_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT AK_SALESORDERHEADER_SALESORDERNUMBER UNIQUE (SALESORDERNUMBER);

ALTER TABLE SALES_SALESPERSON ADD CONSTRAINT AK_SALESPERSON_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE SALES_SALESPERSONQUOTAHISTORY ADD CONSTRAINT AK_SALESPERSONQUOTAHISTORY_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE SALES_SALESTAXRATE ADD CONSTRAINT AK_SALESTAXRATE_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE SALES_SALESTAXRATE ADD CONSTRAINT AK_SALESTAXRATE_STATEPROVINCEID_TAXTYPE UNIQUE (STATEPROVINCEID, TAXTYPE);

ALTER TABLE SALES_SALESTERRITORY ADD CONSTRAINT AK_SALESTERRITORY_NAME UNIQUE (NAME);

ALTER TABLE SALES_SALESTERRITORY ADD CONSTRAINT AK_SALESTERRITORY_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE SALES_SALESTERRITORYHISTORY ADD CONSTRAINT AK_SALESTERRITORYHISTORY_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE SALES_SPECIALOFFER ADD CONSTRAINT AK_SPECIALOFFER_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE SALES_SPECIALOFFERPRODUCT ADD CONSTRAINT AK_SPECIALOFFERPRODUCT_ROWGUID UNIQUE (ROWGUID);

ALTER TABLE SALES_STORE ADD CONSTRAINT AK_STORE_ROWGUID UNIQUE (ROWGUID);


-- Portable check constraints

-- Oracle check constraints cannot reference SYSDATE. The stable lower bound is
-- retained; the dynamic minimum-age rule is validated by the seed checks.
ALTER TABLE HUMANRESOURCES_EMPLOYEE ADD CONSTRAINT CK_EMPLOYEE_BIRTHDATE CHECK (BIRTHDATE >= DATE '1930-01-01');

ALTER TABLE HUMANRESOURCES_EMPLOYEE ADD CONSTRAINT CK_EMPLOYEE_GENDER CHECK (upper(GENDER)='F' OR upper(GENDER)='M');

-- Oracle check constraints cannot reference SYSDATE. The stable lower bound is
-- retained; the no-future-hire-date rule is validated by the seed checks.
ALTER TABLE HUMANRESOURCES_EMPLOYEE ADD CONSTRAINT CK_EMPLOYEE_HIREDATE CHECK (HIREDATE >= DATE '1996-07-01');

ALTER TABLE HUMANRESOURCES_EMPLOYEE ADD CONSTRAINT CK_EMPLOYEE_MARITALSTATUS CHECK (upper(MARITALSTATUS)='S' OR upper(MARITALSTATUS)='M');

ALTER TABLE HUMANRESOURCES_EMPLOYEE ADD CONSTRAINT CK_EMPLOYEE_SICKLEAVEHOURS CHECK (SICKLEAVEHOURS>=(0) AND SICKLEAVEHOURS<=(120));

ALTER TABLE HUMANRESOURCES_EMPLOYEE ADD CONSTRAINT CK_EMPLOYEE_VACATIONHOURS CHECK (VACATIONHOURS>=(-40) AND VACATIONHOURS<=(240));

ALTER TABLE HUMANRESOURCES_EMPLOYEEDEPARTMENTHISTORY ADD CONSTRAINT CK_EMPLOYEEDEPARTMENTHISTORY_ENDDATE CHECK (ENDDATE>=STARTDATE OR ENDDATE IS NULL);

ALTER TABLE HUMANRESOURCES_EMPLOYEEPAYHISTORY ADD CONSTRAINT CK_EMPLOYEEPAYHISTORY_PAYFREQUENCY CHECK (PAYFREQUENCY=(2) OR PAYFREQUENCY=(1));

ALTER TABLE HUMANRESOURCES_EMPLOYEEPAYHISTORY ADD CONSTRAINT CK_EMPLOYEEPAYHISTORY_RATE CHECK (RATE>=(6.50) AND RATE<=(200.00));

ALTER TABLE PERSON_PERSON ADD CONSTRAINT CK_PERSON_EMAILPROMOTION CHECK (EMAILPROMOTION>=(0) AND EMAILPROMOTION<=(2));

ALTER TABLE PERSON_PERSON ADD CONSTRAINT CK_PERSON_PERSONTYPE CHECK (PERSONTYPE IS NULL OR (upper(PERSONTYPE)='GC' OR upper(PERSONTYPE)='SP' OR upper(PERSONTYPE)='EM' OR upper(PERSONTYPE)='I' OR upper(PERSONTYPE)='VC' OR upper(PERSONTYPE)='SC'));

ALTER TABLE PRODUCTION_BILLOFMATERIALS ADD CONSTRAINT CK_BILLOFMATERIALS_BOMLEVEL CHECK (PRODUCTASSEMBLYID IS NULL AND BOMLEVEL=(0) AND PERASSEMBLYQTY=(1.00) OR PRODUCTASSEMBLYID IS NOT NULL AND BOMLEVEL>=(1));

ALTER TABLE PRODUCTION_BILLOFMATERIALS ADD CONSTRAINT CK_BILLOFMATERIALS_ENDDATE CHECK (ENDDATE>STARTDATE OR ENDDATE IS NULL);

ALTER TABLE PRODUCTION_BILLOFMATERIALS ADD CONSTRAINT CK_BILLOFMATERIALS_PERASSEMBLYQTY CHECK (PERASSEMBLYQTY>=(1.00));

ALTER TABLE PRODUCTION_BILLOFMATERIALS ADD CONSTRAINT CK_BILLOFMATERIALS_PRODUCTASSEMBLYID CHECK (PRODUCTASSEMBLYID<>COMPONENTID);

ALTER TABLE PRODUCTION_DOCUMENT ADD CONSTRAINT CK_DOCUMENT_STATUS CHECK (STATUS>=(1) AND STATUS<=(3));

ALTER TABLE PRODUCTION_LOCATION ADD CONSTRAINT CK_LOCATION_AVAILABILITY CHECK (AVAILABILITY>=(0.00));

ALTER TABLE PRODUCTION_LOCATION ADD CONSTRAINT CK_LOCATION_COSTRATE CHECK (COSTRATE>=(0.00));

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT CK_PRODUCT_CLASS CHECK (upper(CLASS)='H' OR upper(CLASS)='M' OR upper(CLASS)='L' OR CLASS IS NULL);

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT CK_PRODUCT_DAYSTOMANUFACTURE CHECK (DAYSTOMANUFACTURE>=(0));

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT CK_PRODUCT_LISTPRICE CHECK (LISTPRICE>=(0.00));

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT CK_PRODUCT_PRODUCTLINE CHECK (upper(PRODUCTLINE)='R' OR upper(PRODUCTLINE)='M' OR upper(PRODUCTLINE)='T' OR upper(PRODUCTLINE)='S' OR PRODUCTLINE IS NULL);

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT CK_PRODUCT_REORDERPOINT CHECK (REORDERPOINT>(0));

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT CK_PRODUCT_SAFETYSTOCKLEVEL CHECK (SAFETYSTOCKLEVEL>(0));

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT CK_PRODUCT_SELLENDDATE CHECK (SELLENDDATE>=SELLSTARTDATE OR SELLENDDATE IS NULL);

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT CK_PRODUCT_STANDARDCOST CHECK (STANDARDCOST>=(0.00));

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT CK_PRODUCT_STYLE CHECK (upper(STYLE)='U' OR upper(STYLE)='M' OR upper(STYLE)='W' OR STYLE IS NULL);

ALTER TABLE PRODUCTION_PRODUCT ADD CONSTRAINT CK_PRODUCT_WEIGHT CHECK (WEIGHT>(0.00));

ALTER TABLE PRODUCTION_PRODUCTCOSTHISTORY ADD CONSTRAINT CK_PRODUCTCOSTHISTORY_ENDDATE CHECK (ENDDATE>=STARTDATE OR ENDDATE IS NULL);

ALTER TABLE PRODUCTION_PRODUCTCOSTHISTORY ADD CONSTRAINT CK_PRODUCTCOSTHISTORY_STANDARDCOST CHECK (STANDARDCOST>=(0.00));

ALTER TABLE PRODUCTION_PRODUCTINVENTORY ADD CONSTRAINT CK_PRODUCTINVENTORY_BIN CHECK (BIN>=(0) AND BIN<=(100));

ALTER TABLE PRODUCTION_PRODUCTINVENTORY ADD CONSTRAINT CK_PRODUCTINVENTORY_SHELF CHECK (REGEXP_LIKE(SHELF, '^[A-Za-z]$') OR SHELF = 'N/A');

ALTER TABLE PRODUCTION_PRODUCTLISTPRICEHISTORY ADD CONSTRAINT CK_PRODUCTLISTPRICEHISTORY_ENDDATE CHECK (ENDDATE>=STARTDATE OR ENDDATE IS NULL);

ALTER TABLE PRODUCTION_PRODUCTLISTPRICEHISTORY ADD CONSTRAINT CK_PRODUCTLISTPRICEHISTORY_LISTPRICE CHECK (LISTPRICE>(0.00));

ALTER TABLE PRODUCTION_PRODUCTREVIEW ADD CONSTRAINT CK_PRODUCTREVIEW_RATING CHECK (RATING>=(1) AND RATING<=(5));

ALTER TABLE PRODUCTION_TRANSACTIONHISTORY ADD CONSTRAINT CK_TRANSACTIONHISTORY_TRANSACTIONTYPE CHECK (upper(TRANSACTIONTYPE)='P' OR upper(TRANSACTIONTYPE)='S' OR upper(TRANSACTIONTYPE)='W');

ALTER TABLE PRODUCTION_TRANSACTIONHISTORYARCHIVE ADD CONSTRAINT CK_TRANSACTIONHISTORYARCHIVE_TRANSACTIONTYPE CHECK (upper(TRANSACTIONTYPE)='P' OR upper(TRANSACTIONTYPE)='S' OR upper(TRANSACTIONTYPE)='W');

ALTER TABLE PRODUCTION_WORKORDER ADD CONSTRAINT CK_WORKORDER_ENDDATE CHECK (ENDDATE>=STARTDATE OR ENDDATE IS NULL);

ALTER TABLE PRODUCTION_WORKORDER ADD CONSTRAINT CK_WORKORDER_ORDERQTY CHECK (ORDERQTY>(0));

ALTER TABLE PRODUCTION_WORKORDER ADD CONSTRAINT CK_WORKORDER_SCRAPPEDQTY CHECK (SCRAPPEDQTY>=(0));

ALTER TABLE PRODUCTION_WORKORDERROUTING ADD CONSTRAINT CK_WORKORDERROUTING_ACTUALCOST CHECK (ACTUALCOST>(0.00));

ALTER TABLE PRODUCTION_WORKORDERROUTING ADD CONSTRAINT CK_WORKORDERROUTING_ACTUALENDDATE CHECK (ACTUALENDDATE>=ACTUALSTARTDATE OR ACTUALENDDATE IS NULL OR ACTUALSTARTDATE IS NULL);

ALTER TABLE PRODUCTION_WORKORDERROUTING ADD CONSTRAINT CK_WORKORDERROUTING_ACTUALRESOURCEHRS CHECK (ACTUALRESOURCEHRS>=(0.0000));

ALTER TABLE PRODUCTION_WORKORDERROUTING ADD CONSTRAINT CK_WORKORDERROUTING_PLANNEDCOST CHECK (PLANNEDCOST>(0.00));

ALTER TABLE PRODUCTION_WORKORDERROUTING ADD CONSTRAINT CK_WORKORDERROUTING_SCHEDULEDENDDATE CHECK (SCHEDULEDENDDATE>=SCHEDULEDSTARTDATE);

ALTER TABLE PURCHASING_PRODUCTVENDOR ADD CONSTRAINT CK_PRODUCTVENDOR_AVERAGELEADTIME CHECK (AVERAGELEADTIME>=(1));

ALTER TABLE PURCHASING_PRODUCTVENDOR ADD CONSTRAINT CK_PRODUCTVENDOR_LASTRECEIPTCOST CHECK (LASTRECEIPTCOST>(0.00));

ALTER TABLE PURCHASING_PRODUCTVENDOR ADD CONSTRAINT CK_PRODUCTVENDOR_MAXORDERQTY CHECK (MAXORDERQTY>=(1));

ALTER TABLE PURCHASING_PRODUCTVENDOR ADD CONSTRAINT CK_PRODUCTVENDOR_MINORDERQTY CHECK (MINORDERQTY>=(1));

ALTER TABLE PURCHASING_PRODUCTVENDOR ADD CONSTRAINT CK_PRODUCTVENDOR_ONORDERQTY CHECK (ONORDERQTY>=(0));

ALTER TABLE PURCHASING_PRODUCTVENDOR ADD CONSTRAINT CK_PRODUCTVENDOR_STANDARDPRICE CHECK (STANDARDPRICE>(0.00));

ALTER TABLE PURCHASING_PURCHASEORDERDETAIL ADD CONSTRAINT CK_PURCHASEORDERDETAIL_ORDERQTY CHECK (ORDERQTY>(0));

ALTER TABLE PURCHASING_PURCHASEORDERDETAIL ADD CONSTRAINT CK_PURCHASEORDERDETAIL_RECEIVEDQTY CHECK (RECEIVEDQTY>=(0.00));

ALTER TABLE PURCHASING_PURCHASEORDERDETAIL ADD CONSTRAINT CK_PURCHASEORDERDETAIL_REJECTEDQTY CHECK (REJECTEDQTY>=(0.00));

ALTER TABLE PURCHASING_PURCHASEORDERDETAIL ADD CONSTRAINT CK_PURCHASEORDERDETAIL_UNITPRICE CHECK (UNITPRICE>=(0.00));

ALTER TABLE PURCHASING_PURCHASEORDERHEADER ADD CONSTRAINT CK_PURCHASEORDERHEADER_FREIGHT CHECK (FREIGHT>=(0.00));

ALTER TABLE PURCHASING_PURCHASEORDERHEADER ADD CONSTRAINT CK_PURCHASEORDERHEADER_SHIPDATE CHECK (SHIPDATE>=ORDERDATE OR SHIPDATE IS NULL);

ALTER TABLE PURCHASING_PURCHASEORDERHEADER ADD CONSTRAINT CK_PURCHASEORDERHEADER_STATUS CHECK (STATUS>=(1) AND STATUS<=(4));

ALTER TABLE PURCHASING_PURCHASEORDERHEADER ADD CONSTRAINT CK_PURCHASEORDERHEADER_SUBTOTAL CHECK (SUBTOTAL>=(0.00));

ALTER TABLE PURCHASING_PURCHASEORDERHEADER ADD CONSTRAINT CK_PURCHASEORDERHEADER_TAXAMT CHECK (TAXAMT>=(0.00));

ALTER TABLE PURCHASING_SHIPMETHOD ADD CONSTRAINT CK_SHIPMETHOD_SHIPBASE CHECK (SHIPBASE>(0.00));

ALTER TABLE PURCHASING_SHIPMETHOD ADD CONSTRAINT CK_SHIPMETHOD_SHIPRATE CHECK (SHIPRATE>(0.00));

ALTER TABLE PURCHASING_VENDOR ADD CONSTRAINT CK_VENDOR_CREDITRATING CHECK (CREDITRATING>=(1) AND CREDITRATING<=(5));

ALTER TABLE SALES_SALESORDERDETAIL ADD CONSTRAINT CK_SALESORDERDETAIL_ORDERQTY CHECK (ORDERQTY>(0));

ALTER TABLE SALES_SALESORDERDETAIL ADD CONSTRAINT CK_SALESORDERDETAIL_UNITPRICE CHECK (UNITPRICE>=(0.00));

ALTER TABLE SALES_SALESORDERDETAIL ADD CONSTRAINT CK_SALESORDERDETAIL_UNITPRICEDISCOUNT CHECK (UNITPRICEDISCOUNT>=(0.00));

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT CK_SALESORDERHEADER_DUEDATE CHECK (DUEDATE>=ORDERDATE);

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT CK_SALESORDERHEADER_FREIGHT CHECK (FREIGHT>=(0.00));

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT CK_SALESORDERHEADER_SHIPDATE CHECK (SHIPDATE>=ORDERDATE OR SHIPDATE IS NULL);

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT CK_SALESORDERHEADER_STATUS CHECK (STATUS>=(0) AND STATUS<=(8));

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT CK_SALESORDERHEADER_SUBTOTAL CHECK (SUBTOTAL>=(0.00));

ALTER TABLE SALES_SALESORDERHEADER ADD CONSTRAINT CK_SALESORDERHEADER_TAXAMT CHECK (TAXAMT>=(0.00));

ALTER TABLE SALES_SALESPERSON ADD CONSTRAINT CK_SALESPERSON_BONUS CHECK (BONUS>=(0.00));

ALTER TABLE SALES_SALESPERSON ADD CONSTRAINT CK_SALESPERSON_COMMISSIONPCT CHECK (COMMISSIONPCT>=(0.00));

ALTER TABLE SALES_SALESPERSON ADD CONSTRAINT CK_SALESPERSON_SALESLASTYEAR CHECK (SALESLASTYEAR>=(0.00));

ALTER TABLE SALES_SALESPERSON ADD CONSTRAINT CK_SALESPERSON_SALESQUOTA CHECK (SALESQUOTA>(0.00));

ALTER TABLE SALES_SALESPERSON ADD CONSTRAINT CK_SALESPERSON_SALESYTD CHECK (SALESYTD>=(0.00));

ALTER TABLE SALES_SALESPERSONQUOTAHISTORY ADD CONSTRAINT CK_SALESPERSONQUOTAHISTORY_SALESQUOTA CHECK (SALESQUOTA>(0.00));

ALTER TABLE SALES_SALESTAXRATE ADD CONSTRAINT CK_SALESTAXRATE_TAXTYPE CHECK (TAXTYPE>=(1) AND TAXTYPE<=(3));

ALTER TABLE SALES_SALESTERRITORY ADD CONSTRAINT CK_SALESTERRITORY_COSTLASTYEAR CHECK (COSTLASTYEAR>=(0.00));

ALTER TABLE SALES_SALESTERRITORY ADD CONSTRAINT CK_SALESTERRITORY_COSTYTD CHECK (COSTYTD>=(0.00));

ALTER TABLE SALES_SALESTERRITORY ADD CONSTRAINT CK_SALESTERRITORY_SALESLASTYEAR CHECK (SALESLASTYEAR>=(0.00));

ALTER TABLE SALES_SALESTERRITORY ADD CONSTRAINT CK_SALESTERRITORY_SALESYTD CHECK (SALESYTD>=(0.00));

ALTER TABLE SALES_SALESTERRITORYHISTORY ADD CONSTRAINT CK_SALESTERRITORYHISTORY_ENDDATE CHECK (ENDDATE>=STARTDATE OR ENDDATE IS NULL);

ALTER TABLE SALES_SHOPPINGCARTITEM ADD CONSTRAINT CK_SHOPPINGCARTITEM_QUANTITY CHECK (QUANTITY>=(1));

ALTER TABLE SALES_SPECIALOFFER ADD CONSTRAINT CK_SPECIALOFFER_DISCOUNTPCT CHECK (DISCOUNTPCT>=(0.00));

ALTER TABLE SALES_SPECIALOFFER ADD CONSTRAINT CK_SPECIALOFFER_ENDDATE CHECK (ENDDATE>=STARTDATE);

ALTER TABLE SALES_SPECIALOFFER ADD CONSTRAINT CK_SPECIALOFFER_MAXQTY CHECK (MAXQTY>=(0));

ALTER TABLE SALES_SPECIALOFFER ADD CONSTRAINT CK_SPECIALOFFER_MINQTY CHECK (MINQTY>=(0));


-- Skipped checks: SQL Server expressions using CONVERT, DATEPART, hierarchyid methods,
-- or other engine-specific semantics. Primary keys are created with their tables.
