-- =============================================================================
-- Purpose          : Create portable relational views used by the
--                    AdventureWorks2022 source simulation.
-- Execution order  : 07 of 07; run after 06_create_procedures.sql.
-- Connection user  : SYSTEM; CURRENT_SCHEMA is set to ADVENTUREWORKS2022.
-- Objects affected : Geography, product-description, employee, customer, and
--                    salesperson views.
-- Notes            : SQL Server XML, PIVOT, and hierarchyid-dependent views are
--                    omitted when an Oracle translation would change meaning.
-- =============================================================================

ALTER SESSION SET CURRENT_SCHEMA = ADVENTUREWORKS2022;

-- Geography reference view
CREATE OR REPLACE VIEW PERSON_VSTATEPROVINCECOUNTRYREGION AS
SELECT SP.STATEPROVINCEID,
       SP.STATEPROVINCECODE,
       SP.ISONLYSTATEPROVINCEFLAG,
       SP.NAME AS STATEPROVINCENAME,
       SP.TERRITORYID,
       CR.COUNTRYREGIONCODE,
       CR.NAME AS COUNTRYREGIONNAME
FROM PERSON_STATEPROVINCE SP
JOIN PERSON_COUNTRYREGION CR
  ON CR.COUNTRYREGIONCODE = SP.COUNTRYREGIONCODE;

-- Product-description view
CREATE OR REPLACE VIEW PRODUCTION_VPRODUCTANDDESCRIPTION AS
SELECT P.PRODUCTID,
       P.NAME AS PRODUCTNAME,
       PM.NAME AS PRODUCTMODEL,
       C.CULTUREID,
       PD.DESCRIPTION
FROM PRODUCTION_PRODUCT P
JOIN PRODUCTION_PRODUCTMODEL PM
  ON PM.PRODUCTMODELID = P.PRODUCTMODELID
JOIN PRODUCTION_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE PMPDC
  ON PMPDC.PRODUCTMODELID = PM.PRODUCTMODELID
JOIN PRODUCTION_PRODUCTDESCRIPTION PD
  ON PD.PRODUCTDESCRIPTIONID = PMPDC.PRODUCTDESCRIPTIONID
JOIN PRODUCTION_CULTURE C
  ON C.CULTUREID = PMPDC.CULTUREID;

-- Human Resources and Sales presentation views
CREATE OR REPLACE VIEW HUMANRESOURCES_VEMPLOYEE AS
SELECT E.BUSINESSENTITYID,
       P.TITLE,
       P.FIRSTNAME,
       P.MIDDLENAME,
       P.LASTNAME,
       P.SUFFIX,
       E.JOBTITLE,
       E.BIRTHDATE,
       E.HIREDATE,
       E.CURRENTFLAG
FROM HUMANRESOURCES_EMPLOYEE E
JOIN PERSON_PERSON P
  ON P.BUSINESSENTITYID = E.BUSINESSENTITYID;

CREATE OR REPLACE VIEW SALES_VINDIVIDUALCUSTOMER AS
SELECT C.CUSTOMERID,
       C.ACCOUNTNUMBER,
       P.BUSINESSENTITYID,
       P.TITLE,
       P.FIRSTNAME,
       P.MIDDLENAME,
       P.LASTNAME,
       P.SUFFIX,
       P.EMAILPROMOTION,
       C.TERRITORYID
FROM SALES_CUSTOMER C
JOIN PERSON_PERSON P
  ON P.BUSINESSENTITYID = C.PERSONID;

CREATE OR REPLACE VIEW SALES_VSALESPERSON AS
SELECT SP.BUSINESSENTITYID,
       P.TITLE,
       P.FIRSTNAME,
       P.MIDDLENAME,
       P.LASTNAME,
       P.SUFFIX,
       E.JOBTITLE,
       SP.TERRITORYID,
       T.NAME AS TERRITORYNAME,
       SP.SALESQUOTA,
       SP.SALESYTD,
       SP.SALESLASTYEAR
FROM SALES_SALESPERSON SP
JOIN HUMANRESOURCES_EMPLOYEE E
  ON E.BUSINESSENTITYID = SP.BUSINESSENTITYID
JOIN PERSON_PERSON P
  ON P.BUSINESSENTITYID = SP.BUSINESSENTITYID
LEFT JOIN SALES_SALESTERRITORY T
  ON T.TERRITORYID = SP.TERRITORYID;

-- Deliberately omitted SQL Server views
-- XML shredding, demographic/catalog/resume, PIVOT fiscal-year, and hierarchyid-
-- dependent views are not replaced with translations that could change meaning.
