-- =============================================================================
-- Purpose          : Validate seeded row counts, relationships, joins, and sales
--                    reconciliation measures.
-- Execution order  : Validation entry point. Run before seeding for a baseline
--                    or after 06_seed_validation_scenarios.sql for final checks.
-- Connection user  : SYSTEM; CURRENT_SCHEMA is set to ADVENTUREWORKS2022.
-- Tables inspected : All source tables, with focused Person/Product/Sales checks.
-- Notes            : Returns result sets only; it does not modify source data.
--                    Row counts are exact and may take time on large tables.
-- =============================================================================

SET PAGESIZE 500
SET LINESIZE 220
ALTER SESSION SET CURRENT_SCHEMA = ADVENTUREWORKS2022;

COLUMN TABLE_NAME FORMAT A55
COLUMN ROW_COUNT FORMAT 999999999999999999

PROMPT ========================================================================
PROMPT ROW COUNTS FOR ALL ADVENTUREWORKS2022 TABLES
PROMPT ========================================================================

SELECT T.TABLE_NAME,
       XMLCAST(
         XMLQUERY(
           '/ROWSET/ROW/ROW_COUNT/text()'
           PASSING XMLTYPE(
             DBMS_XMLGEN.GETXML(
               'SELECT COUNT(*) AS ROW_COUNT FROM ADVENTUREWORKS2022.' ||
               DBMS_ASSERT.ENQUOTE_NAME(T.TABLE_NAME)
             )
           )
           RETURNING CONTENT
         ) AS NUMBER
       ) AS ROW_COUNT
FROM ALL_TABLES T
WHERE T.OWNER = 'ADVENTUREWORKS2022'
ORDER BY T.TABLE_NAME;

PROMPT ========================================================================
PROMPT IMPORTANT FOREIGN-KEY ORPHAN CHECKS - EACH RESULT SHOULD BE ZERO
PROMPT ========================================================================

SELECT 'SALES_DETAIL_TO_HEADER' AS CHECK_NAME, COUNT(*) AS ORPHAN_COUNT
FROM SALES_SALESORDERDETAIL D
LEFT JOIN SALES_SALESORDERHEADER H ON H.SALESORDERID = D.SALESORDERID
WHERE H.SALESORDERID IS NULL
UNION ALL
SELECT 'SALES_HEADER_TO_CUSTOMER', COUNT(*)
FROM SALES_SALESORDERHEADER H
LEFT JOIN SALES_CUSTOMER C ON C.CUSTOMERID = H.CUSTOMERID
WHERE C.CUSTOMERID IS NULL
UNION ALL
SELECT 'SALES_DETAIL_TO_PRODUCT', COUNT(*)
FROM SALES_SALESORDERDETAIL D
LEFT JOIN PRODUCTION_PRODUCT P ON P.PRODUCTID = D.PRODUCTID
WHERE P.PRODUCTID IS NULL
UNION ALL
SELECT 'ADDRESS_TO_STATEPROVINCE', COUNT(*)
FROM PERSON_ADDRESS A
LEFT JOIN PERSON_STATEPROVINCE S ON S.STATEPROVINCEID = A.STATEPROVINCEID
WHERE S.STATEPROVINCEID IS NULL
UNION ALL
SELECT 'PURCHASE_DETAIL_TO_HEADER', COUNT(*)
FROM PURCHASING_PURCHASEORDERDETAIL D
LEFT JOIN PURCHASING_PURCHASEORDERHEADER H
  ON H.PURCHASEORDERID = D.PURCHASEORDERID
WHERE H.PURCHASEORDERID IS NULL;

PROMPT ========================================================================
PROMPT CROSS-DOMAIN SAMPLE JOIN
PROMPT ========================================================================

SELECT H.SALESORDERID,
       H.ORDERDATE,
       C.ACCOUNTNUMBER,
       P.FIRSTNAME || ' ' || P.LASTNAME AS CUSTOMER_NAME,
       PR.NAME AS PRODUCT_NAME,
       D.ORDERQTY,
       D.UNITPRICE,
       D.UNITPRICEDISCOUNT
FROM SALES_SALESORDERHEADER H
JOIN SALES_CUSTOMER C ON C.CUSTOMERID = H.CUSTOMERID
LEFT JOIN PERSON_PERSON P ON P.BUSINESSENTITYID = C.PERSONID
JOIN SALES_SALESORDERDETAIL D ON D.SALESORDERID = H.SALESORDERID
JOIN PRODUCTION_PRODUCT PR ON PR.PRODUCTID = D.PRODUCTID
ORDER BY H.ORDERDATE, H.SALESORDERID, D.SALESORDERDETAILID;

PROMPT ========================================================================
PROMPT MONTHLY SALES ROW_COUNT AND SUM_TOTAL RECONCILIATION
PROMPT ========================================================================

SELECT TO_CHAR(H.ORDERDATE, 'YYYY-MM') AS ORDER_MONTH,
       COUNT(DISTINCT H.SALESORDERID) AS HEADER_ROW_COUNT,
       COUNT(*) AS DETAIL_ROW_COUNT,
       ROUND(SUM(D.ORDERQTY * D.UNITPRICE * (1 - D.UNITPRICEDISCOUNT)), 2)
         AS SUM_TOTAL
FROM SALES_SALESORDERHEADER H
JOIN SALES_SALESORDERDETAIL D ON D.SALESORDERID = H.SALESORDERID
GROUP BY TO_CHAR(H.ORDERDATE, 'YYYY-MM')
ORDER BY ORDER_MONTH;

PROMPT ========================================================================
PROMPT BUSINESS VALIDATION RULES - EACH RESULT SHOULD BE ZERO
PROMPT ========================================================================

SELECT 'EMPLOYEE_UNDER_18' AS CHECK_NAME, COUNT(*) AS FAILURE_COUNT
FROM HUMANRESOURCES_EMPLOYEE
WHERE BIRTHDATE > ADD_MONTHS(TRUNC(SYSDATE), -216)
UNION ALL
SELECT 'EMPLOYEE_FUTURE_HIRE_DATE', COUNT(*)
FROM HUMANRESOURCES_EMPLOYEE
WHERE HIREDATE > TRUNC(SYSDATE)
UNION ALL
SELECT 'ORDER_HEADER_WITHOUT_DETAIL', COUNT(*)
FROM SALES_SALESORDERHEADER H
WHERE NOT EXISTS (
  SELECT 1 FROM SALES_SALESORDERDETAIL D
  WHERE D.SALESORDERID = H.SALESORDERID
);
