-- =============================================================================
-- Purpose          : Seed stable reference and lookup data used by all domains.
-- Execution order  : 01 of 06; run after all ddl scripts.
-- Connection user  : SYSTEM; CURRENT_SCHEMA is set to ADVENTUREWORKS2022.
-- Tables populated : Country, geography, currency, HR, product, purchasing,
--                    sales-rule, and source-version reference tables.
-- Notes            : For reruns, execute cleanup/data scripts 01 through 05
--                    first. Explicit identity values keep relationships stable.
-- =============================================================================

SET DEFINE OFF
ALTER SESSION SET CURRENT_SCHEMA = ADVENTUREWORKS2022;

-- Geography and currency
INSERT ALL
  INTO PERSON_COUNTRYREGION (COUNTRYREGIONCODE, NAME) VALUES ('US', 'United States')
  INTO PERSON_COUNTRYREGION (COUNTRYREGIONCODE, NAME) VALUES ('CA', 'Canada')
  INTO PERSON_COUNTRYREGION (COUNTRYREGIONCODE, NAME) VALUES ('PE', 'Peru')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO SALES_CURRENCY (CURRENCYCODE, NAME) VALUES ('USD', 'US Dollar')
  INTO SALES_CURRENCY (CURRENCYCODE, NAME) VALUES ('CAD', 'Canadian Dollar')
  INTO SALES_CURRENCY (CURRENCYCODE, NAME) VALUES ('PEN', 'Peruvian Sol')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO SALES_COUNTRYREGIONCURRENCY (COUNTRYREGIONCODE, CURRENCYCODE) VALUES ('US', 'USD')
  INTO SALES_COUNTRYREGIONCURRENCY (COUNTRYREGIONCODE, CURRENCYCODE) VALUES ('CA', 'CAD')
  INTO SALES_COUNTRYREGIONCURRENCY (COUNTRYREGIONCODE, CURRENCYCODE) VALUES ('PE', 'PEN')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO SALES_SALESTERRITORY (TERRITORYID, NAME, COUNTRYREGIONCODE, TERRITORYGROUP, SALESYTD, SALESLASTYEAR, COSTYTD, COSTLASTYEAR)
    VALUES (1, 'Northwest', 'US', 'North America', 420000, 390000, 90000, 85000)
  INTO SALES_SALESTERRITORY (TERRITORYID, NAME, COUNTRYREGIONCODE, TERRITORYGROUP, SALESYTD, SALESLASTYEAR, COSTYTD, COSTLASTYEAR)
    VALUES (2, 'Canada', 'CA', 'North America', 210000, 195000, 46000, 42000)
  INTO SALES_SALESTERRITORY (TERRITORYID, NAME, COUNTRYREGIONCODE, TERRITORYGROUP, SALESYTD, SALESLASTYEAR, COSTYTD, COSTLASTYEAR)
    VALUES (3, 'Peru', 'PE', 'South America', 175000, 150000, 37000, 32000)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PERSON_STATEPROVINCE (STATEPROVINCEID, STATEPROVINCECODE, COUNTRYREGIONCODE, ISONLYSTATEPROVINCEFLAG, NAME, TERRITORYID)
    VALUES (1, 'WA', 'US', 0, 'Washington', 1)
  INTO PERSON_STATEPROVINCE (STATEPROVINCEID, STATEPROVINCECODE, COUNTRYREGIONCODE, ISONLYSTATEPROVINCEFLAG, NAME, TERRITORYID)
    VALUES (2, 'BC', 'CA', 0, 'British Columbia', 2)
  INTO PERSON_STATEPROVINCE (STATEPROVINCEID, STATEPROVINCECODE, COUNTRYREGIONCODE, ISONLYSTATEPROVINCEFLAG, NAME, TERRITORYID)
    VALUES (3, 'LIM', 'PE', 0, 'Lima', 3)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO SALES_CURRENCYRATE (CURRENCYRATEID, CURRENCYRATEDATE, FROMCURRENCYCODE, TOCURRENCYCODE, AVERAGERATE, ENDOFDAYRATE)
    VALUES (1, DATE '2023-01-01', 'USD', 'CAD', 1.35, 1.36)
  INTO SALES_CURRENCYRATE (CURRENCYRATEID, CURRENCYRATEDATE, FROMCURRENCYCODE, TOCURRENCYCODE, AVERAGERATE, ENDOFDAYRATE)
    VALUES (2, DATE '2024-01-01', 'USD', 'PEN', 3.72, 3.74)
SELECT 1 FROM DUAL;

-- Person and Human Resources lookups
INSERT ALL
  INTO PERSON_PHONENUMBERTYPE (PHONENUMBERTYPEID, NAME) VALUES (1, 'Cell')
  INTO PERSON_PHONENUMBERTYPE (PHONENUMBERTYPEID, NAME) VALUES (2, 'Home')
  INTO PERSON_PHONENUMBERTYPE (PHONENUMBERTYPEID, NAME) VALUES (3, 'Work')
  INTO PERSON_ADDRESSTYPE (ADDRESSTYPEID, NAME) VALUES (1, 'Home')
  INTO PERSON_ADDRESSTYPE (ADDRESSTYPEID, NAME) VALUES (2, 'Main Office')
  INTO PERSON_ADDRESSTYPE (ADDRESSTYPEID, NAME) VALUES (3, 'Shipping')
  INTO PERSON_CONTACTTYPE (CONTACTTYPEID, NAME) VALUES (1, 'Owner')
  INTO PERSON_CONTACTTYPE (CONTACTTYPEID, NAME) VALUES (2, 'Purchasing Manager')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO HUMANRESOURCES_DEPARTMENT (DEPARTMENTID, NAME, GROUPNAME) VALUES (1, 'Sales', 'Sales and Marketing')
  INTO HUMANRESOURCES_DEPARTMENT (DEPARTMENTID, NAME, GROUPNAME) VALUES (2, 'Production', 'Manufacturing')
  INTO HUMANRESOURCES_DEPARTMENT (DEPARTMENTID, NAME, GROUPNAME) VALUES (3, 'Purchasing', 'Inventory Management')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO HUMANRESOURCES_SHIFT (SHIFTID, NAME, STARTTIME, ENDTIME)
    VALUES (1, 'Day', TIMESTAMP '2000-01-01 07:00:00', TIMESTAMP '2000-01-01 15:00:00')
  INTO HUMANRESOURCES_SHIFT (SHIFTID, NAME, STARTTIME, ENDTIME)
    VALUES (2, 'Evening', TIMESTAMP '2000-01-01 15:00:00', TIMESTAMP '2000-01-01 23:00:00')
SELECT 1 FROM DUAL;

-- Production and purchasing lookups
INSERT ALL
  INTO PRODUCTION_CULTURE (CULTUREID, NAME) VALUES ('en-US', 'English')
  INTO PRODUCTION_CULTURE (CULTUREID, NAME) VALUES ('es-PE', 'Spanish')
  INTO PRODUCTION_UNITMEASURE (UNITMEASURECODE, NAME) VALUES ('EA', 'Each')
  INTO PRODUCTION_UNITMEASURE (UNITMEASURECODE, NAME) VALUES ('CM', 'Centimeter')
  INTO PRODUCTION_UNITMEASURE (UNITMEASURECODE, NAME) VALUES ('KG', 'Kilogram')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PRODUCTION_LOCATION (LOCATIONID, NAME, COSTRATE, AVAILABILITY) VALUES (1, 'Frame Assembly', 22.50, 120)
  INTO PRODUCTION_LOCATION (LOCATIONID, NAME, COSTRATE, AVAILABILITY) VALUES (6, 'Miscellaneous Storage', 5.00, 300)
  INTO PRODUCTION_PRODUCTCATEGORY (PRODUCTCATEGORYID, NAME) VALUES (1, 'Bikes')
  INTO PRODUCTION_PRODUCTCATEGORY (PRODUCTCATEGORYID, NAME) VALUES (2, 'Components')
  INTO PRODUCTION_PRODUCTSUBCATEGORY (PRODUCTSUBCATEGORYID, PRODUCTCATEGORYID, NAME) VALUES (1, 1, 'Mountain Bikes')
  INTO PRODUCTION_PRODUCTSUBCATEGORY (PRODUCTSUBCATEGORYID, PRODUCTCATEGORYID, NAME) VALUES (2, 2, 'Frames')
  INTO PRODUCTION_SCRAPREASON (SCRAPREASONID, NAME) VALUES (1, 'Paint defect')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PURCHASING_SHIPMETHOD (SHIPMETHODID, NAME, SHIPBASE, SHIPRATE) VALUES (1, 'GROUND', 5.00, 0.75)
  INTO PURCHASING_SHIPMETHOD (SHIPMETHODID, NAME, SHIPBASE, SHIPRATE) VALUES (2, 'EXPRESS', 12.00, 1.50)
SELECT 1 FROM DUAL;

-- Sales rules and classifications
INSERT ALL
  INTO SALES_SALESREASON (SALESREASONID, NAME, REASONTYPE) VALUES (1, 'Price', 'Marketing')
  INTO SALES_SALESREASON (SALESREASONID, NAME, REASONTYPE) VALUES (2, 'Quality', 'Promotion')
  INTO SALES_SALESTAXRATE (SALESTAXRATEID, STATEPROVINCEID, TAXTYPE, TAXRATE, NAME) VALUES (1, 1, 1, 8.50, 'Washington Sales Tax')
  INTO SALES_SALESTAXRATE (SALESTAXRATEID, STATEPROVINCEID, TAXTYPE, TAXRATE, NAME) VALUES (2, 3, 1, 18.00, 'Peru IGV')
  INTO SALES_SPECIALOFFER (SPECIALOFFERID, DESCRIPTION, DISCOUNTPCT, TYPE, CATEGORY, STARTDATE, ENDDATE, MINQTY, MAXQTY)
    VALUES (1, 'No Discount', 0, 'No Discount', 'No Discount', DATE '2020-01-01', DATE '2030-12-31', 0, NULL)
  INTO SALES_SPECIALOFFER (SPECIALOFFERID, DESCRIPTION, DISCOUNTPCT, TYPE, CATEGORY, STARTDATE, ENDDATE, MINQTY, MAXQTY)
    VALUES (2, 'Seasonal 10 Percent', 0.10, 'Seasonal Discount', 'Customer', DATE '2023-01-01', DATE '2025-12-31', 1, 50)
SELECT 1 FROM DUAL;

-- Source-build metadata
INSERT INTO DBO_AWBUILDVERSION (SYSTEMINFORMATIONID, DATABASEVERSION, VERSIONDATE)
VALUES (1, 'Oracle-XE-21c-Sim-1', DATE '2026-08-11');

COMMIT;

PROMPT [01] Reference data seeded.
