-- =============================================================================
-- Purpose          : Seed business entities, people, addresses, and HR records.
-- Execution order  : 02 of 06; run after 01_seed_reference_data.sql.
-- Connection user  : SYSTEM; CURRENT_SCHEMA is set to ADVENTUREWORKS2022.
-- Tables populated : Person/business-entity tables and Human Resources tables.
-- Notes            : Entity 1 is the salesperson used by Purchasing and Sales;
--                    entities 6 and 7 become a store and vendor later.
-- =============================================================================

SET DEFINE OFF
ALTER SESSION SET CURRENT_SCHEMA = ADVENTUREWORKS2022;

-- Shared business-entity identities
INSERT ALL
  INTO PERSON_BUSINESSENTITY (BUSINESSENTITYID) VALUES (1)
  INTO PERSON_BUSINESSENTITY (BUSINESSENTITYID) VALUES (2)
  INTO PERSON_BUSINESSENTITY (BUSINESSENTITYID) VALUES (3)
  INTO PERSON_BUSINESSENTITY (BUSINESSENTITYID) VALUES (4)
  INTO PERSON_BUSINESSENTITY (BUSINESSENTITYID) VALUES (5)
  INTO PERSON_BUSINESSENTITY (BUSINESSENTITYID) VALUES (6)
  INTO PERSON_BUSINESSENTITY (BUSINESSENTITYID) VALUES (7)
  INTO PERSON_BUSINESSENTITY (BUSINESSENTITYID) VALUES (8)
SELECT 1 FROM DUAL;

-- People include active employees, customers, and an inactive historical person
INSERT ALL
  INTO PERSON_PERSON (BUSINESSENTITYID, PERSONTYPE, FIRSTNAME, LASTNAME, EMAILPROMOTION, ADDITIONALCONTACTINFO, DEMOGRAPHICS)
    VALUES (1, 'EM', 'Alex', 'Morgan', 1, '<ContactInfo><PreferredChannel>Email</PreferredChannel></ContactInfo>', '<Survey><Household>3</Household></Survey>')
  INTO PERSON_PERSON (BUSINESSENTITYID, PERSONTYPE, FIRSTNAME, LASTNAME, EMAILPROMOTION)
    VALUES (2, 'EM', 'Jordan', 'Lee', 0)
  INTO PERSON_PERSON (BUSINESSENTITYID, PERSONTYPE, FIRSTNAME, LASTNAME, EMAILPROMOTION)
    VALUES (3, 'I', 'Casey', 'Rivera', 2)
  INTO PERSON_PERSON (BUSINESSENTITYID, PERSONTYPE, FIRSTNAME, LASTNAME, EMAILPROMOTION)
    VALUES (4, 'I', 'Taylor', 'Chen', 0)
  INTO PERSON_PERSON (BUSINESSENTITYID, PERSONTYPE, FIRSTNAME, LASTNAME, EMAILPROMOTION)
    VALUES (5, 'I', 'Robin', 'Patel', 0)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PERSON_EMAILADDRESS (BUSINESSENTITYID, EMAILADDRESSID, EMAILADDRESS) VALUES (1, 1, 'alex.morgan@example.test')
  INTO PERSON_EMAILADDRESS (BUSINESSENTITYID, EMAILADDRESSID, EMAILADDRESS) VALUES (2, 2, 'jordan.lee@example.test')
  INTO PERSON_EMAILADDRESS (BUSINESSENTITYID, EMAILADDRESSID, EMAILADDRESS) VALUES (3, 3, 'casey.rivera@example.test')
  INTO PERSON_EMAILADDRESS (BUSINESSENTITYID, EMAILADDRESSID, EMAILADDRESS) VALUES (4, 4, 'taylor.chen@example.test')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PERSON_PERSONPHONE (BUSINESSENTITYID, PHONENUMBER, PHONENUMBERTYPEID) VALUES (1, '555-0101', 3)
  INTO PERSON_PERSONPHONE (BUSINESSENTITYID, PHONENUMBER, PHONENUMBERTYPEID) VALUES (2, '555-0102', 3)
  INTO PERSON_PERSONPHONE (BUSINESSENTITYID, PHONENUMBER, PHONENUMBERTYPEID) VALUES (3, '555-0201', 1)
  INTO PERSON_PERSONPHONE (BUSINESSENTITYID, PHONENUMBER, PHONENUMBERTYPEID) VALUES (4, '555-0202', 1)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PERSON_PASSWORD (BUSINESSENTITYID, PASSWORDHASH, PASSWORDSALT) VALUES (1, 'SYNTHETIC_HASH_0001', 'SALT0001')
  INTO PERSON_PASSWORD (BUSINESSENTITYID, PASSWORDHASH, PASSWORDSALT) VALUES (2, 'SYNTHETIC_HASH_0002', 'SALT0002')
  INTO PERSON_PASSWORD (BUSINESSENTITYID, PASSWORDHASH, PASSWORDSALT) VALUES (3, 'SYNTHETIC_HASH_0003', 'SALT0003')
  INTO PERSON_PASSWORD (BUSINESSENTITYID, PASSWORDHASH, PASSWORDSALT) VALUES (4, 'SYNTHETIC_HASH_0004', 'SALT0004')
SELECT 1 FROM DUAL;

-- Addresses cover billing, shipping, vendor, and store joins
INSERT ALL
  INTO PERSON_ADDRESS (ADDRESSID, ADDRESSLINE1, CITY, STATEPROVINCEID, POSTALCODE, SPATIALLOCATION)
    VALUES (1, '100 Pine Street', 'Seattle', 1, '98101', 'POINT(-122.335167 47.608013)')
  INTO PERSON_ADDRESS (ADDRESSID, ADDRESSLINE1, CITY, STATEPROVINCEID, POSTALCODE)
    VALUES (2, '200 Harbor Avenue', 'Vancouver', 2, 'V6B1A1')
  INTO PERSON_ADDRESS (ADDRESSID, ADDRESSLINE1, CITY, STATEPROVINCEID, POSTALCODE, SPATIALLOCATION)
    VALUES (3, '300 Avenida Central', 'Lima', 3, '15001', 'POINT(-77.042793 -12.046374)')
  INTO PERSON_ADDRESS (ADDRESSID, ADDRESSLINE1, CITY, STATEPROVINCEID, POSTALCODE)
    VALUES (4, '400 Industrial Way', 'Seattle', 1, '98108')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PERSON_BUSINESSENTITYADDRESS (BUSINESSENTITYID, ADDRESSID, ADDRESSTYPEID) VALUES (1, 1, 1)
  INTO PERSON_BUSINESSENTITYADDRESS (BUSINESSENTITYID, ADDRESSID, ADDRESSTYPEID) VALUES (2, 2, 1)
  INTO PERSON_BUSINESSENTITYADDRESS (BUSINESSENTITYID, ADDRESSID, ADDRESSTYPEID) VALUES (3, 1, 1)
  INTO PERSON_BUSINESSENTITYADDRESS (BUSINESSENTITYID, ADDRESSID, ADDRESSTYPEID) VALUES (4, 3, 1)
  INTO PERSON_BUSINESSENTITYADDRESS (BUSINESSENTITYID, ADDRESSID, ADDRESSTYPEID) VALUES (6, 4, 2)
  INTO PERSON_BUSINESSENTITYADDRESS (BUSINESSENTITYID, ADDRESSID, ADDRESSTYPEID) VALUES (7, 4, 2)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PERSON_BUSINESSENTITYCONTACT (BUSINESSENTITYID, PERSONID, CONTACTTYPEID) VALUES (6, 3, 1)
  INTO PERSON_BUSINESSENTITYCONTACT (BUSINESSENTITYID, PERSONID, CONTACTTYPEID) VALUES (7, 4, 2)
SELECT 1 FROM DUAL;

-- Employee master and history
INSERT ALL
  INTO HUMANRESOURCES_EMPLOYEE (BUSINESSENTITYID, NATIONALIDNUMBER, LOGINID, ORGANIZATIONNODE, JOBTITLE, BIRTHDATE, MARITALSTATUS, GENDER, HIREDATE, SALARIEDFLAG, VACATIONHOURS, SICKLEAVEHOURS, CURRENTFLAG)
    VALUES (1, 'NID000001', 'adventureworks\alex', '/1/', 'Sales Representative', DATE '1985-04-12', 'M', 'F', DATE '2015-02-02', 1, 80, 20, 1)
  INTO HUMANRESOURCES_EMPLOYEE (BUSINESSENTITYID, NATIONALIDNUMBER, LOGINID, ORGANIZATIONNODE, JOBTITLE, BIRTHDATE, MARITALSTATUS, GENDER, HIREDATE, SALARIEDFLAG, VACATIONHOURS, SICKLEAVEHOURS, CURRENTFLAG)
    VALUES (2, 'NID000002', 'adventureworks\jordan', '/2/', 'Production Technician', DATE '1990-09-03', 'S', 'M', DATE '2018-06-11', 0, 40, 12, 1)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO HUMANRESOURCES_EMPLOYEEDEPARTMENTHISTORY (BUSINESSENTITYID, DEPARTMENTID, SHIFTID, STARTDATE, ENDDATE)
    VALUES (1, 1, 1, DATE '2015-02-02', NULL)
  INTO HUMANRESOURCES_EMPLOYEEDEPARTMENTHISTORY (BUSINESSENTITYID, DEPARTMENTID, SHIFTID, STARTDATE, ENDDATE)
    VALUES (2, 2, 1, DATE '2018-06-11', DATE '2022-12-31')
  INTO HUMANRESOURCES_EMPLOYEEDEPARTMENTHISTORY (BUSINESSENTITYID, DEPARTMENTID, SHIFTID, STARTDATE, ENDDATE)
    VALUES (2, 2, 2, DATE '2023-01-01', NULL)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO HUMANRESOURCES_EMPLOYEEPAYHISTORY (BUSINESSENTITYID, RATECHANGEDATE, RATE, PAYFREQUENCY)
    VALUES (1, DATE '2022-01-01', 45.00, 2)
  INTO HUMANRESOURCES_EMPLOYEEPAYHISTORY (BUSINESSENTITYID, RATECHANGEDATE, RATE, PAYFREQUENCY)
    VALUES (1, DATE '2024-01-01', 48.50, 2)
  INTO HUMANRESOURCES_EMPLOYEEPAYHISTORY (BUSINESSENTITYID, RATECHANGEDATE, RATE, PAYFREQUENCY)
    VALUES (2, DATE '2023-01-01', 29.75, 2)
SELECT 1 FROM DUAL;

INSERT INTO HUMANRESOURCES_JOBCANDIDATE (JOBCANDIDATEID, BUSINESSENTITYID, RESUME)
VALUES (1, 2, '<Resume><Skill>Assembly</Skill><Years>6</Years></Resume>');

-- Salesperson is seeded here because purchasing orders reference the employee
INSERT INTO SALES_SALESPERSON (
  BUSINESSENTITYID, TERRITORYID, SALESQUOTA, BONUS, COMMISSIONPCT,
  SALESYTD, SALESLASTYEAR
) VALUES (1, 1, 250000, 5000, 0.015, 230000, 210000);

COMMIT;

PROMPT [02] Person and Human Resources data seeded.
