-- =============================================================================
-- Purpose          : Seed products and supporting production history.
-- Execution order  : 03 of 06; run after 02_seed_person_hr_data.sql.
-- Connection user  : SYSTEM; CURRENT_SCHEMA is set to ADVENTUREWORKS2022.
-- Tables populated : Product models/descriptions, products, BOM, documents,
--                    media, inventory, cost/price history, work, transactions.
-- Notes            : Products 101-103 are reused by Purchasing and Sales.
-- =============================================================================

SET DEFINE OFF
ALTER SESSION SET CURRENT_SCHEMA = ADVENTUREWORKS2022;

-- Product catalog
INSERT ALL
  INTO PRODUCTION_PRODUCTDESCRIPTION (PRODUCTDESCRIPTIONID, DESCRIPTION)
    VALUES (1, 'All-purpose synthetic mountain bike for local migration tests.')
  INTO PRODUCTION_PRODUCTDESCRIPTION (PRODUCTDESCRIPTIONID, DESCRIPTION)
    VALUES (2, 'Lightweight aluminum replacement frame.')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PRODUCTION_PRODUCTMODEL (PRODUCTMODELID, NAME, CATALOGDESCRIPTION, INSTRUCTIONS)
    VALUES (1, 'Trail Explorer', '<Catalog><Segment>Trail</Segment></Catalog>', '<Instructions><Step>Inspect before use</Step></Instructions>')
  INTO PRODUCTION_PRODUCTMODEL (PRODUCTMODELID, NAME, CATALOGDESCRIPTION)
    VALUES (2, 'Universal Frame', '<Catalog><Material>Aluminum</Material></Catalog>')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PRODUCTION_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE (PRODUCTMODELID, PRODUCTDESCRIPTIONID, CULTUREID)
    VALUES (1, 1, 'en-US')
  INTO PRODUCTION_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE (PRODUCTMODELID, PRODUCTDESCRIPTIONID, CULTUREID)
    VALUES (2, 2, 'en-US')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PRODUCTION_PRODUCT (PRODUCTID, NAME, PRODUCTNUMBER, MAKEFLAG, FINISHEDGOODSFLAG, COLOR, SAFETYSTOCKLEVEL, REORDERPOINT, STANDARDCOST, LISTPRICE, PRODUCTSIZE, SIZEUNITMEASURECODE, WEIGHTUNITMEASURECODE, WEIGHT, DAYSTOMANUFACTURE, PRODUCTLINE, CLASS, STYLE, PRODUCTSUBCATEGORYID, PRODUCTMODELID, SELLSTARTDATE)
    VALUES (101, 'Trail Explorer 100', 'BK-TR-100', 1, 1, 'Red', 20, 10, 650, 999.99, 'M', 'CM', 'KG', 14.50, 3, 'M', 'M', 'U', 1, 1, DATE '2021-01-01')
  INTO PRODUCTION_PRODUCT (PRODUCTID, NAME, PRODUCTNUMBER, MAKEFLAG, FINISHEDGOODSFLAG, COLOR, SAFETYSTOCKLEVEL, REORDERPOINT, STANDARDCOST, LISTPRICE, PRODUCTSIZE, SIZEUNITMEASURECODE, WEIGHTUNITMEASURECODE, WEIGHT, DAYSTOMANUFACTURE, PRODUCTLINE, CLASS, STYLE, PRODUCTSUBCATEGORYID, PRODUCTMODELID, SELLSTARTDATE)
    VALUES (102, 'Universal Frame M', 'FR-UN-M', 1, 0, 'Black', 30, 15, 220, 349.99, 'M', 'CM', 'KG', 2.80, 2, 'M', 'H', 'U', 2, 2, DATE '2021-01-01')
  INTO PRODUCTION_PRODUCT (PRODUCTID, NAME, PRODUCTNUMBER, MAKEFLAG, FINISHEDGOODSFLAG, COLOR, SAFETYSTOCKLEVEL, REORDERPOINT, STANDARDCOST, LISTPRICE, DAYSTOMANUFACTURE, PRODUCTLINE, CLASS, STYLE, PRODUCTSUBCATEGORYID, PRODUCTMODELID, SELLSTARTDATE, SELLENDDATE, DISCONTINUEDDATE)
    VALUES (103, 'Legacy Trail Explorer', 'BK-TR-OLD', 1, 1, 'Blue', 10, 5, 500, 749.99, 3, 'M', 'L', 'U', 1, 1, DATE '2019-01-01', DATE '2022-12-31', DATE '2023-01-01')
SELECT 1 FROM DUAL;

-- Design documentation and media
INSERT INTO PRODUCTION_DOCUMENT (
  DOCUMENTNODE, TITLE, OWNER, FOLDERFLAG, FILENAME, FILEEXTENSION,
  REVISION, CHANGENUMBER, STATUS, DOCUMENTSUMMARY, DOCUMENT
) VALUES (
  '/1/', 'Trail Explorer Assembly', 2, 0, 'trail-explorer-assembly.pdf', '.pdf',
  '1.0', 1, 2, 'Synthetic assembly document.', UTL_RAW.CAST_TO_RAW('SYNTHETIC PDF')
);

INSERT INTO PRODUCTION_ILLUSTRATION (ILLUSTRATIONID, DIAGRAM)
VALUES (1, '<Diagram><Component>Frame</Component></Diagram>');

INSERT INTO PRODUCTION_PRODUCTPHOTO (
  PRODUCTPHOTOID, THUMBNAILPHOTO, THUMBNAILPHOTOFILENAME,
  LARGEPHOTO, LARGEPHOTOFILENAME
) VALUES (
  1, UTL_RAW.CAST_TO_RAW('THUMBNAIL'), 'trail-thumb.jpg',
  UTL_RAW.CAST_TO_RAW('LARGE PHOTO'), 'trail-large.jpg'
);

INSERT ALL
  INTO PRODUCTION_PRODUCTDOCUMENT (PRODUCTID, DOCUMENTNODE) VALUES (101, '/1/')
  INTO PRODUCTION_PRODUCTMODELILLUSTRATION (PRODUCTMODELID, ILLUSTRATIONID) VALUES (1, 1)
  INTO PRODUCTION_PRODUCTPRODUCTPHOTO (PRODUCTID, PRODUCTPHOTOID, ISPRIMARY) VALUES (101, 1, 1)
SELECT 1 FROM DUAL;

-- Bill of materials, inventory, and catalog history
INSERT INTO PRODUCTION_BILLOFMATERIALS (
  BILLOFMATERIALSID, PRODUCTASSEMBLYID, COMPONENTID, STARTDATE,
  UNITMEASURECODE, BOMLEVEL, PERASSEMBLYQTY
) VALUES (1, 101, 102, DATE '2021-01-01', 'EA', 1, 1);

INSERT ALL
  INTO PRODUCTION_PRODUCTINVENTORY (PRODUCTID, LOCATIONID, SHELF, BIN, QUANTITY) VALUES (101, 6, 'A', 1, 25)
  INTO PRODUCTION_PRODUCTINVENTORY (PRODUCTID, LOCATIONID, SHELF, BIN, QUANTITY) VALUES (102, 1, 'B', 2, 60)
  INTO PRODUCTION_PRODUCTINVENTORY (PRODUCTID, LOCATIONID, SHELF, BIN, QUANTITY) VALUES (103, 6, 'N/A', 0, 3)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PRODUCTION_PRODUCTCOSTHISTORY (PRODUCTID, STARTDATE, ENDDATE, STANDARDCOST) VALUES (101, DATE '2021-01-01', DATE '2022-12-31', 600)
  INTO PRODUCTION_PRODUCTCOSTHISTORY (PRODUCTID, STARTDATE, STANDARDCOST) VALUES (101, DATE '2023-01-01', 650)
  INTO PRODUCTION_PRODUCTCOSTHISTORY (PRODUCTID, STARTDATE, STANDARDCOST) VALUES (102, DATE '2021-01-01', 220)
  INTO PRODUCTION_PRODUCTLISTPRICEHISTORY (PRODUCTID, STARTDATE, ENDDATE, LISTPRICE) VALUES (101, DATE '2021-01-01', DATE '2022-12-31', 899.99)
  INTO PRODUCTION_PRODUCTLISTPRICEHISTORY (PRODUCTID, STARTDATE, LISTPRICE) VALUES (101, DATE '2023-01-01', 999.99)
  INTO PRODUCTION_PRODUCTLISTPRICEHISTORY (PRODUCTID, STARTDATE, LISTPRICE) VALUES (102, DATE '2021-01-01', 349.99)
SELECT 1 FROM DUAL;

INSERT INTO PRODUCTION_PRODUCTREVIEW (
  PRODUCTREVIEWID, PRODUCTID, REVIEWERNAME, REVIEWDATE,
  EMAILADDRESS, RATING, COMMENTS
) VALUES (
  1, 101, 'Synthetic Reviewer', DATE '2024-02-15',
  'reviewer@example.test', 5, 'Reliable product used for local test joins.'
);

-- Production transactions and work history
INSERT ALL
  INTO PRODUCTION_TRANSACTIONHISTORY (TRANSACTIONID, PRODUCTID, REFERENCEORDERID, REFERENCEORDERLINEID, TRANSACTIONDATE, TRANSACTIONTYPE, QUANTITY, ACTUALCOST)
    VALUES (1, 101, 1, 1, DATE '2024-01-10', 'W', 5, 650)
  INTO PRODUCTION_TRANSACTIONHISTORY (TRANSACTIONID, PRODUCTID, REFERENCEORDERID, REFERENCEORDERLINEID, TRANSACTIONDATE, TRANSACTIONTYPE, QUANTITY, ACTUALCOST)
    VALUES (2, 102, 1, 1, DATE '2024-01-09', 'P', 10, 220)
  INTO PRODUCTION_TRANSACTIONHISTORYARCHIVE (TRANSACTIONID, PRODUCTID, REFERENCEORDERID, REFERENCEORDERLINEID, TRANSACTIONDATE, TRANSACTIONTYPE, QUANTITY, ACTUALCOST)
    VALUES (9001, 103, 900, 1, DATE '2021-06-15', 'S', 2, 500)
SELECT 1 FROM DUAL;

INSERT INTO PRODUCTION_WORKORDER (
  WORKORDERID, PRODUCTID, ORDERQTY, SCRAPPEDQTY, STARTDATE,
  ENDDATE, DUEDATE, SCRAPREASONID
) VALUES (
  1, 101, 10, 1, DATE '2024-01-02', DATE '2024-01-08', DATE '2024-01-10', 1
);

INSERT INTO PRODUCTION_WORKORDERROUTING (
  WORKORDERID, PRODUCTID, OPERATIONSEQUENCE, LOCATIONID,
  SCHEDULEDSTARTDATE, SCHEDULEDENDDATE, ACTUALSTARTDATE, ACTUALENDDATE,
  ACTUALRESOURCEHRS, PLANNEDCOST, ACTUALCOST
) VALUES (
  1, 101, 10, 1,
  DATE '2024-01-02', DATE '2024-01-05', DATE '2024-01-02', DATE '2024-01-05',
  16, 1200, 1250
);

COMMIT;

PROMPT [03] Production data seeded.
