-- =============================================================================
-- Purpose          : Seed vendors, product sourcing, and purchase-order history.
-- Execution order  : 04 of 06; run after 03_seed_production_data.sql.
-- Connection user  : SYSTEM; CURRENT_SCHEMA is set to ADVENTUREWORKS2022.
-- Tables populated : PURCHASING_VENDOR, PURCHASING_PRODUCTVENDOR,
--                    PURCHASING_PURCHASEORDERHEADER and detail.
-- Notes            : Includes active/inactive vendors and open/complete orders.
-- =============================================================================

SET DEFINE OFF
ALTER SESSION SET CURRENT_SCHEMA = ADVENTUREWORKS2022;

INSERT ALL
  INTO PURCHASING_VENDOR (BUSINESSENTITYID, ACCOUNTNUMBER, NAME, CREDITRATING, PREFERREDVENDORSTATUS, ACTIVEFLAG, PURCHASINGWEBSERVICEURL)
    VALUES (7, 'VENDOR-0001', 'Synthetic Cycles Supply', 1, 1, 1, 'https://vendor.example.test/orders')
  INTO PURCHASING_VENDOR (BUSINESSENTITYID, ACCOUNTNUMBER, NAME, CREDITRATING, PREFERREDVENDORSTATUS, ACTIVEFLAG)
    VALUES (8, 'VENDOR-0002', 'Legacy Parts Archive', 4, 0, 0)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PURCHASING_PRODUCTVENDOR (PRODUCTID, BUSINESSENTITYID, AVERAGELEADTIME, STANDARDPRICE, LASTRECEIPTCOST, LASTRECEIPTDATE, MINORDERQTY, MAXORDERQTY, ONORDERQTY, UNITMEASURECODE)
    VALUES (101, 7, 7, 640, 635, DATE '2024-02-01', 1, 100, 10, 'EA')
  INTO PURCHASING_PRODUCTVENDOR (PRODUCTID, BUSINESSENTITYID, AVERAGELEADTIME, STANDARDPRICE, LASTRECEIPTCOST, LASTRECEIPTDATE, MINORDERQTY, MAXORDERQTY, ONORDERQTY, UNITMEASURECODE)
    VALUES (102, 7, 5, 210, 205, DATE '2024-02-01', 5, 200, 25, 'EA')
  INTO PURCHASING_PRODUCTVENDOR (PRODUCTID, BUSINESSENTITYID, AVERAGELEADTIME, STANDARDPRICE, LASTRECEIPTCOST, LASTRECEIPTDATE, MINORDERQTY, MAXORDERQTY, ONORDERQTY, UNITMEASURECODE)
    VALUES (103, 8, 14, 480, 475, DATE '2021-12-01', 1, 20, 0, 'EA')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PURCHASING_PURCHASEORDERHEADER (PURCHASEORDERID, STATUS, EMPLOYEEID, VENDORID, SHIPMETHODID, ORDERDATE, SHIPDATE, SUBTOTAL, TAXAMT, FREIGHT)
    VALUES (1, 4, 1, 7, 1, DATE '2023-12-15', DATE '2023-12-20', 4300, 365.50, 75)
  INTO PURCHASING_PURCHASEORDERHEADER (PURCHASEORDERID, STATUS, EMPLOYEEID, VENDORID, SHIPMETHODID, ORDERDATE, SHIPDATE, SUBTOTAL, TAXAMT, FREIGHT)
    VALUES (2, 2, 2, 7, 2, DATE '2024-03-01', NULL, 2100, 178.50, 45)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO PURCHASING_PURCHASEORDERDETAIL (PURCHASEORDERID, PURCHASEORDERDETAILID, DUEDATE, ORDERQTY, PRODUCTID, UNITPRICE, RECEIVEDQTY, REJECTEDQTY)
    VALUES (1, 1, DATE '2023-12-22', 5, 101, 650, 5, 0)
  INTO PURCHASING_PURCHASEORDERDETAIL (PURCHASEORDERID, PURCHASEORDERDETAILID, DUEDATE, ORDERQTY, PRODUCTID, UNITPRICE, RECEIVEDQTY, REJECTEDQTY)
    VALUES (1, 2, DATE '2023-12-22', 5, 102, 210, 5, 0)
  INTO PURCHASING_PURCHASEORDERDETAIL (PURCHASEORDERID, PURCHASEORDERDETAILID, DUEDATE, ORDERQTY, PRODUCTID, UNITPRICE, RECEIVEDQTY, REJECTEDQTY)
    VALUES (2, 3, DATE '2024-03-10', 10, 102, 210, 0, 0)
SELECT 1 FROM DUAL;

COMMIT;

PROMPT [04] Purchasing data seeded.
