-- =============================================================================
-- Purpose          : Seed customers, stores, payment links, and monthly sales.
-- Execution order  : 05 of 06; run after 04_seed_purchasing_data.sql.
-- Connection user  : SYSTEM; CURRENT_SCHEMA is set to ADVENTUREWORKS2022.
-- Tables populated : Sales master, bridge, history, order-header/detail, and
--                    shopping-cart tables.
-- Notes            : Orders span 2022-2024 and include multiple statuses for
--                    monthly batch, ROW_COUNT, and SUM_TOTAL testing.
-- =============================================================================

SET DEFINE OFF
ALTER SESSION SET CURRENT_SCHEMA = ADVENTUREWORKS2022;

-- Sales master and payment relationships
INSERT INTO SALES_STORE (
  BUSINESSENTITYID, NAME, SALESPERSONID, DEMOGRAPHICS
) VALUES (
  6, 'Synthetic Outdoor Store', 1,
  '<StoreSurvey><AnnualSales>250000</AnnualSales><YearOpened>2020</YearOpened></StoreSurvey>'
);

INSERT ALL
  INTO SALES_CUSTOMER (CUSTOMERID, PERSONID, TERRITORYID) VALUES (1, 3, 1)
  INTO SALES_CUSTOMER (CUSTOMERID, PERSONID, TERRITORYID) VALUES (2, 4, 3)
  INTO SALES_CUSTOMER (CUSTOMERID, STOREID, TERRITORYID) VALUES (3, 6, 1)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO SALES_CREDITCARD (CREDITCARDID, CARDTYPE, CARDNUMBER, EXPMONTH, EXPYEAR)
    VALUES (1, 'Test Visa', '4111111111111111', 12, 2028)
  INTO SALES_CREDITCARD (CREDITCARDID, CARDTYPE, CARDNUMBER, EXPMONTH, EXPYEAR)
    VALUES (2, 'Test MasterCard', '5555555555554444', 6, 2027)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO SALES_PERSONCREDITCARD (BUSINESSENTITYID, CREDITCARDID) VALUES (3, 1)
  INTO SALES_PERSONCREDITCARD (BUSINESSENTITYID, CREDITCARDID) VALUES (4, 2)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO SALES_SPECIALOFFERPRODUCT (SPECIALOFFERID, PRODUCTID) VALUES (1, 101)
  INTO SALES_SPECIALOFFERPRODUCT (SPECIALOFFERID, PRODUCTID) VALUES (1, 102)
  INTO SALES_SPECIALOFFERPRODUCT (SPECIALOFFERID, PRODUCTID) VALUES (1, 103)
  INTO SALES_SPECIALOFFERPRODUCT (SPECIALOFFERID, PRODUCTID) VALUES (2, 101)
SELECT 1 FROM DUAL;

-- Salesperson planning and territory history
INSERT ALL
  INTO SALES_SALESPERSONQUOTAHISTORY (BUSINESSENTITYID, QUOTADATE, SALESQUOTA)
    VALUES (1, DATE '2023-01-01', 200000)
  INTO SALES_SALESPERSONQUOTAHISTORY (BUSINESSENTITYID, QUOTADATE, SALESQUOTA)
    VALUES (1, DATE '2024-01-01', 250000)
  INTO SALES_SALESTERRITORYHISTORY (BUSINESSENTITYID, TERRITORYID, STARTDATE, ENDDATE)
    VALUES (1, 3, DATE '2021-01-01', DATE '2022-12-31')
  INTO SALES_SALESTERRITORYHISTORY (BUSINESSENTITYID, TERRITORYID, STARTDATE, ENDDATE)
    VALUES (1, 1, DATE '2023-01-01', NULL)
SELECT 1 FROM DUAL;

-- Order headers are the batch-driving rows by ORDERDATE
INSERT ALL
  INTO SALES_SALESORDERHEADER (SALESORDERID, ORDERDATE, DUEDATE, SHIPDATE, STATUS, ONLINEORDERFLAG, CUSTOMERID, SALESPERSONID, TERRITORYID, BILLTOADDRESSID, SHIPTOADDRESSID, SHIPMETHODID, CREDITCARDID, CREDITCARDAPPROVALCODE, SUBTOTAL, TAXAMT, FREIGHT, ORDERCOMMENT)
    VALUES (1001, DATE '2022-01-15', DATE '2022-01-25', DATE '2022-01-18', 5, 1, 1, 1, 1, 1, 1, 1, 1, 'APP-1001', 1699.97, 144.50, 20, 'Historical completed order')
  INTO SALES_SALESORDERHEADER (SALESORDERID, ORDERDATE, DUEDATE, SHIPDATE, STATUS, ONLINEORDERFLAG, CUSTOMERID, SALESPERSONID, TERRITORYID, BILLTOADDRESSID, SHIPTOADDRESSID, SHIPMETHODID, CREDITCARDID, CREDITCARDAPPROVALCODE, SUBTOTAL, TAXAMT, FREIGHT)
    VALUES (1002, DATE '2023-01-10', DATE '2023-01-20', DATE '2023-01-12', 5, 1, 2, 1, 3, 3, 3, 2, 2, 'APP-1002', 749.99, 135.00, 25)
  INTO SALES_SALESORDERHEADER (SALESORDERID, ORDERDATE, DUEDATE, SHIPDATE, STATUS, ONLINEORDERFLAG, CUSTOMERID, SALESPERSONID, TERRITORYID, BILLTOADDRESSID, SHIPTOADDRESSID, SHIPMETHODID, CREDITCARDID, CREDITCARDAPPROVALCODE, SUBTOTAL, TAXAMT, FREIGHT)
    VALUES (1003, DATE '2023-02-08', DATE '2023-02-18', DATE '2023-02-10', 5, 1, 1, 1, 1, 1, 1, 1, 1, 'APP-1003', 1799.98, 153.00, 20)
  INTO SALES_SALESORDERHEADER (SALESORDERID, ORDERDATE, DUEDATE, SHIPDATE, STATUS, ONLINEORDERFLAG, CUSTOMERID, SALESPERSONID, TERRITORYID, BILLTOADDRESSID, SHIPTOADDRESSID, SHIPMETHODID, SUBTOTAL, TAXAMT, FREIGHT)
    VALUES (1004, DATE '2024-01-05', DATE '2024-01-15', DATE '2024-01-08', 5, 0, 3, 1, 1, 4, 4, 1, 1049.97, 89.25, 30)
  INTO SALES_SALESORDERHEADER (SALESORDERID, ORDERDATE, DUEDATE, STATUS, ONLINEORDERFLAG, CUSTOMERID, SALESPERSONID, TERRITORYID, BILLTOADDRESSID, SHIPTOADDRESSID, SHIPMETHODID, CREDITCARDID, CREDITCARDAPPROVALCODE, CURRENCYRATEID, SUBTOTAL, TAXAMT, FREIGHT, ORDERCOMMENT)
    VALUES (1005, DATE '2024-03-20', DATE '2024-03-30', 1, 1, 2, 1, 3, 3, 3, 2, 2, 'APP-1005', 2, 1349.98, 243.00, 25, 'Open validation order')
  INTO SALES_SALESORDERHEADER (SALESORDERID, ORDERDATE, DUEDATE, STATUS, ONLINEORDERFLAG, CUSTOMERID, SALESPERSONID, TERRITORYID, BILLTOADDRESSID, SHIPTOADDRESSID, SHIPMETHODID, CREDITCARDID, CREDITCARDAPPROVALCODE, SUBTOTAL, TAXAMT, FREIGHT)
    VALUES (1006, DATE '2024-04-11', DATE '2024-04-21', 2, 1, 1, 1, 1, 1, 1, 1, 1, 'APP-1006', 1999.98, 170.00, 20)
SELECT 1 FROM DUAL;

-- Order details provide line-grain reconciliation measures
INSERT ALL
  INTO SALES_SALESORDERDETAIL (SALESORDERID, SALESORDERDETAILID, ORDERQTY, PRODUCTID, SPECIALOFFERID, UNITPRICE, UNITPRICEDISCOUNT) VALUES (1001, 1, 1, 101, 1, 999.99, 0)
  INTO SALES_SALESORDERDETAIL (SALESORDERID, SALESORDERDETAILID, ORDERQTY, PRODUCTID, SPECIALOFFERID, UNITPRICE, UNITPRICEDISCOUNT) VALUES (1001, 2, 2, 102, 1, 349.99, 0)
  INTO SALES_SALESORDERDETAIL (SALESORDERID, SALESORDERDETAILID, ORDERQTY, PRODUCTID, SPECIALOFFERID, UNITPRICE, UNITPRICEDISCOUNT) VALUES (1002, 3, 1, 103, 1, 749.99, 0)
  INTO SALES_SALESORDERDETAIL (SALESORDERID, SALESORDERDETAILID, ORDERQTY, PRODUCTID, SPECIALOFFERID, UNITPRICE, UNITPRICEDISCOUNT) VALUES (1003, 4, 2, 101, 2, 999.99, 0.10)
  INTO SALES_SALESORDERDETAIL (SALESORDERID, SALESORDERDETAILID, ORDERQTY, PRODUCTID, SPECIALOFFERID, UNITPRICE, UNITPRICEDISCOUNT) VALUES (1004, 5, 3, 102, 1, 349.99, 0)
  INTO SALES_SALESORDERDETAIL (SALESORDERID, SALESORDERDETAILID, ORDERQTY, PRODUCTID, SPECIALOFFERID, UNITPRICE, UNITPRICEDISCOUNT) VALUES (1005, 6, 1, 101, 1, 999.99, 0)
  INTO SALES_SALESORDERDETAIL (SALESORDERID, SALESORDERDETAILID, ORDERQTY, PRODUCTID, SPECIALOFFERID, UNITPRICE, UNITPRICEDISCOUNT) VALUES (1005, 7, 1, 102, 1, 349.99, 0)
  INTO SALES_SALESORDERDETAIL (SALESORDERID, SALESORDERDETAILID, ORDERQTY, PRODUCTID, SPECIALOFFERID, UNITPRICE, UNITPRICEDISCOUNT) VALUES (1006, 8, 2, 101, 1, 999.99, 0)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO SALES_SALESORDERHEADERSALESREASON (SALESORDERID, SALESREASONID) VALUES (1001, 2)
  INTO SALES_SALESORDERHEADERSALESREASON (SALESORDERID, SALESREASONID) VALUES (1003, 1)
  INTO SALES_SALESORDERHEADERSALESREASON (SALESORDERID, SALESREASONID) VALUES (1005, 1)
SELECT 1 FROM DUAL;

INSERT ALL
  INTO SALES_SHOPPINGCARTITEM (SHOPPINGCARTITEMID, SHOPPINGCARTID, QUANTITY, PRODUCTID, DATECREATED)
    VALUES (1, 'CART-ACTIVE-001', 1, 101, DATE '2024-04-15')
  INTO SALES_SHOPPINGCARTITEM (SHOPPINGCARTITEMID, SHOPPINGCARTID, QUANTITY, PRODUCTID, DATECREATED)
    VALUES (2, 'CART-ACTIVE-001', 2, 102, DATE '2024-04-15')
SELECT 1 FROM DUAL;

COMMIT;

PROMPT [05] Sales data seeded.
