/* Purpose: Seed Analytics staging from Sales_Operational.prod. Order: 01.
   Precondition: Sales_Operational seed/03_seed_prod.sql has completed. */
USE [Sales_Analytics];
GO
INSERT staging.AddressType(SourceAddressTypeID,Name) SELECT AddressTypeKey,Name FROM Sales_Operational.prod.AddressType s WHERE SourceAddressTypeID=1 AND NOT EXISTS(SELECT 1 FROM staging.AddressType t WHERE t.SourceAddressTypeID=s.AddressTypeKey);
INSERT staging.ProductCategory(SourceProductCategoryID,Name) SELECT ProductCategoryKey,Name FROM Sales_Operational.prod.ProductCategory s WHERE SourceProductCategoryID=1 AND NOT EXISTS(SELECT 1 FROM staging.ProductCategory t WHERE t.SourceProductCategoryID=s.ProductCategoryKey);
INSERT staging.ShipMethod(SourceShipMethodID,Name,ShipBase,ShipRate) SELECT ShipMethodKey,Name,ShipBase,ShipRate FROM Sales_Operational.prod.ShipMethod s WHERE SourceShipMethodID=1 AND NOT EXISTS(SELECT 1 FROM staging.ShipMethod t WHERE t.SourceShipMethodID=s.ShipMethodKey);
INSERT staging.CountryRegion(SourceCountryRegionID,CountryRegionCode,Name) SELECT CountryRegionKey,SourceCountryRegionCode,Name FROM Sales_Operational.prod.CountryRegion s WHERE SourceCountryRegionCode='US' AND NOT EXISTS(SELECT 1 FROM staging.CountryRegion t WHERE t.SourceCountryRegionID=s.CountryRegionKey);
INSERT staging.SalesTerritory(SourceSalesTerritoryID,Name,TerritoryGroup,SourceCountryRegionID) SELECT SalesTerritoryKey,Name,TerritoryGroup,CountryRegionKey FROM Sales_Operational.prod.SalesTerritory s WHERE SourceTerritoryID=1 AND NOT EXISTS(SELECT 1 FROM staging.SalesTerritory t WHERE t.SourceSalesTerritoryID=s.SalesTerritoryKey);
INSERT staging.StateProvince(SourceStateProvinceID,StateProvinceCode,Name,SourceCountryRegionID,SourceSalesTerritoryID) SELECT StateProvinceKey,StateProvinceCode,Name,CountryRegionKey,SalesTerritoryKey FROM Sales_Operational.prod.StateProvince s WHERE SourceStateProvinceID=1 AND NOT EXISTS(SELECT 1 FROM staging.StateProvince t WHERE t.SourceStateProvinceID=s.StateProvinceKey);
INSERT staging.SpecialOffer(SourceSpecialOfferID,Description,DiscountPct,OfferType,Category,StartDate,EndDate,MinQty,MaxQty) SELECT SpecialOfferKey,Description,DiscountPct,OfferType,Category,StartDate,EndDate,MinQty,MaxQty FROM Sales_Operational.prod.SpecialOffer s WHERE SourceSpecialOfferID=1 AND NOT EXISTS(SELECT 1 FROM staging.SpecialOffer t WHERE t.SourceSpecialOfferID=s.SpecialOfferKey);
INSERT staging.Currency(SourceCurrencyID,CurrencyCode,Name) SELECT CurrencyKey,SourceCurrencyCode,Name FROM Sales_Operational.prod.Currency s WHERE SourceCurrencyCode='USD' AND NOT EXISTS(SELECT 1 FROM staging.Currency t WHERE t.SourceCurrencyID=s.CurrencyKey);
INSERT staging.CurrencyRate(SourceCurrencyRateID,CurrencyRateDate,SourceFromCurrencyID,SourceToCurrencyID,AverageRate,EndOfDayRate) SELECT CurrencyRateKey,CurrencyRateDate,FromCurrencyKey,ToCurrencyKey,AverageRate,EndOfDayRate FROM Sales_Operational.prod.CurrencyRate s WHERE SourceCurrencyRateID=1 AND NOT EXISTS(SELECT 1 FROM staging.CurrencyRate t WHERE t.SourceCurrencyRateID=s.CurrencyRateKey);
INSERT staging.CreditCard(SourceCreditCardID,CardType,CardNumber,ExpMonth,ExpYear) SELECT CreditCardKey,CardType,CardNumber,ExpMonth,ExpYear FROM Sales_Operational.prod.CreditCard s WHERE SourceCreditCardID=1 AND NOT EXISTS(SELECT 1 FROM staging.CreditCard t WHERE t.SourceCreditCardID=s.CreditCardKey);
INSERT staging.Address(SourceAddressID,AddressLine1,AddressLine2,City,SourceStateProvinceID,PostalCode,SourceAddressTypeID) SELECT AddressKey,AddressLine1,AddressLine2,City,StateProvinceKey,PostalCode,AddressTypeKey FROM Sales_Operational.prod.Address s WHERE SourceAddressID=1 AND NOT EXISTS(SELECT 1 FROM staging.Address t WHERE t.SourceAddressID=s.AddressKey);
INSERT staging.Product(SourceProductID,ProductNumber,Name,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,Size,Weight,SourceProductCategoryID,SellStartDate,SellEndDate,DiscontinuedDate) SELECT ProductKey,ProductNumber,Name,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,Size,Weight,ProductCategoryKey,SellStartDate,SellEndDate,DiscontinuedDate FROM Sales_Operational.prod.Product s WHERE SourceProductID=1 AND NOT EXISTS(SELECT 1 FROM staging.Product t WHERE t.SourceProductID=s.ProductKey);
INSERT staging.SalesPerson(SourceSalesPersonID,SourceSalesTerritoryID,Title,FirstName,MiddleName,LastName,JobTitle,Gender,HireDate,SalesQuota,Bonus,CommissionPct,SalesYTD,SalesLastYear) SELECT SalesPersonKey,SalesTerritoryKey,Title,FirstName,MiddleName,LastName,JobTitle,Gender,HireDate,SalesQuota,Bonus,CommissionPct,SalesYTD,SalesLastYear FROM Sales_Operational.prod.SalesPerson s WHERE SourceSalesPersonID=1 AND NOT EXISTS(SELECT 1 FROM staging.SalesPerson t WHERE t.SourceSalesPersonID=s.SalesPersonKey);
INSERT staging.Customer(SourceCustomerID,SourceSalesTerritoryID,PersonType,Title,FirstName,MiddleName,LastName,AccountNumber) SELECT CustomerKey,SalesTerritoryKey,PersonType,Title,FirstName,MiddleName,LastName,AccountNumber FROM Sales_Operational.prod.Customer s WHERE SourceCustomerID=1 AND NOT EXISTS(SELECT 1 FROM staging.Customer t WHERE t.SourceCustomerID=s.CustomerKey);
INSERT staging.SalesOrderHeader(SourceSalesOrderID,RevisionNumber,OrderDate,DueDate,ShipDate,Status,SalesOrderNumber,PurchaseOrderNumber,AccountNumber,SourceCustomerID,SourceSalesPersonID,SourceSalesTerritoryID,SourceBillToAddressID,SourceShipToAddressID,SourceShipMethodID,SourceCreditCardID,SourceCurrencyRateID,SubTotal,TaxAmt,Freight,TotalDue,Comment) SELECT SalesOrderHeaderKey,RevisionNumber,OrderDate,DueDate,ShipDate,Status,SalesOrderNumber,PurchaseOrderNumber,AccountNumber,CustomerKey,SalesPersonKey,SalesTerritoryKey,BillToAddressKey,ShipToAddressKey,ShipMethodKey,CreditCardKey,CurrencyRateKey,SubTotal,TaxAmt,Freight,TotalDue,Comment FROM Sales_Operational.prod.SalesOrderHeader s WHERE SourceSalesOrderID=1 AND NOT EXISTS(SELECT 1 FROM staging.SalesOrderHeader t WHERE t.SourceSalesOrderID=s.SalesOrderHeaderKey);
INSERT staging.SalesOrderDetail(SourceSalesOrderID,SourceSalesOrderDetailID,SourceProductID,SourceSpecialOfferID,CarrierTrackingNumber,OrderQty,UnitPrice,UnitPriceDiscount,LineTotal) SELECT SalesOrderHeaderKey,SalesOrderDetailKey,ProductKey,SpecialOfferKey,CarrierTrackingNumber,OrderQty,UnitPrice,UnitPriceDiscount,LineTotal FROM Sales_Operational.prod.SalesOrderDetail s WHERE SourceSalesOrderDetailID=1 AND NOT EXISTS(SELECT 1 FROM staging.SalesOrderDetail t WHERE t.SourceSalesOrderDetailID=s.SalesOrderDetailKey);
GO
