/* Purpose: Seed analytical preparation rows derived from Analytics staging.
   Order: 02. Assumes empty/reseeded local tables for provisional dimension keys. */
USE [Sales_Analytics];
GO
IF NOT EXISTS(SELECT 1 FROM work.DimDate WHERE FullDate='2023-01-15') INSERT work.DimDate(DimDateKey,FullDate,DayNumberOfWeek,DayName,DayNumberOfMonth,DayNumberOfYear,WeekNumberOfYear,MonthNumber,MonthName,CalendarQuarter,CalendarYear) VALUES(20230115,'2023-01-15',1,N'Sunday',15,15,3,1,N'January',1,2023);
IF NOT EXISTS(SELECT 1 FROM work.DimDate WHERE FullDate='2023-01-22') INSERT work.DimDate(DimDateKey,FullDate,DayNumberOfWeek,DayName,DayNumberOfMonth,DayNumberOfYear,WeekNumberOfYear,MonthNumber,MonthName,CalendarQuarter,CalendarYear) VALUES(20230122,'2023-01-22',1,N'Sunday',22,22,4,1,N'January',1,2023);
IF NOT EXISTS(SELECT 1 FROM work.DimDate WHERE FullDate='2023-01-17') INSERT work.DimDate(DimDateKey,FullDate,DayNumberOfWeek,DayName,DayNumberOfMonth,DayNumberOfYear,WeekNumberOfYear,MonthNumber,MonthName,CalendarQuarter,CalendarYear) VALUES(20230117,'2023-01-17',3,N'Tuesday',17,17,3,1,N'January',1,2023);
INSERT work.DimCustomer(SourceCustomerID,AccountNumber,CustomerName,PersonType) SELECT SourceCustomerID,AccountNumber,CONCAT_WS(N' ',Title,FirstName,MiddleName,LastName),PersonType FROM staging.Customer s WHERE NOT EXISTS(SELECT 1 FROM work.DimCustomer t WHERE t.SourceCustomerID=s.SourceCustomerID);
INSERT work.DimSalesPerson(SourceSalesPersonID,SalesPersonName,JobTitle,Gender,HireDate) SELECT SourceSalesPersonID,CONCAT_WS(N' ',Title,FirstName,MiddleName,LastName),JobTitle,Gender,HireDate FROM staging.SalesPerson s WHERE NOT EXISTS(SELECT 1 FROM work.DimSalesPerson t WHERE t.SourceSalesPersonID=s.SourceSalesPersonID);
INSERT work.DimSalesTerritory(SourceSalesTerritoryID,TerritoryName,TerritoryGroup,CountryRegionCode,CountryRegionName) SELECT t.SourceSalesTerritoryID,t.Name,t.TerritoryGroup,c.CountryRegionCode,c.Name FROM staging.SalesTerritory t JOIN staging.CountryRegion c ON c.SourceCountryRegionID=t.SourceCountryRegionID WHERE NOT EXISTS(SELECT 1 FROM work.DimSalesTerritory w WHERE w.SourceSalesTerritoryID=t.SourceSalesTerritoryID);
INSERT work.DimProduct(SourceProductID,ProductNumber,ProductName,Color,Size,ProductCategoryName,StandardCost,ListPrice) SELECT p.SourceProductID,p.ProductNumber,p.Name,p.Color,p.Size,c.Name,p.StandardCost,p.ListPrice FROM staging.Product p LEFT JOIN staging.ProductCategory c ON c.SourceProductCategoryID=p.SourceProductCategoryID WHERE NOT EXISTS(SELECT 1 FROM work.DimProduct w WHERE w.SourceProductID=p.SourceProductID);
INSERT work.DimPaymentMethod(PaymentMethodCode,SourceCreditCardID,PaymentMethodType,CardType,CardNumberLast4) SELECT CONCAT('CARD-',SourceCreditCardID),SourceCreditCardID,N'Credit Card',CardType,RIGHT(CardNumber,4) FROM staging.CreditCard s WHERE NOT EXISTS(SELECT 1 FROM work.DimPaymentMethod w WHERE w.SourceCreditCardID=s.SourceCreditCardID);
INSERT work.DimShipMethod(SourceShipMethodID,ShipMethodName,ShipBase,ShipRate) SELECT SourceShipMethodID,Name,ShipBase,ShipRate FROM staging.ShipMethod s WHERE NOT EXISTS(SELECT 1 FROM work.DimShipMethod w WHERE w.SourceShipMethodID=s.SourceShipMethodID);
IF NOT EXISTS(SELECT 1 FROM work.FactSales)
 INSERT work.FactSales(SourceSalesOrderID,SourceSalesOrderDetailID,OrderDimDateKey,DueDimDateKey,ShipDimDateKey,DimCustomerKey,DimSalesPersonKey,DimSalesTerritoryKey,DimProductKey,DimPaymentMethodKey,DimShipMethodKey,OrderQty,UnitPrice,UnitPriceDiscount,LineTotal,SubTotal,TaxAmt,Freight,TotalDue,SalesAmountUSD)
 SELECT h.SourceSalesOrderID,d.SourceSalesOrderDetailID,1,2,3,1,1,1,1,1,1,d.OrderQty,d.UnitPrice,d.UnitPriceDiscount,d.LineTotal,h.SubTotal,h.TaxAmt,h.Freight,h.TotalDue,d.LineTotal
 FROM staging.SalesOrderHeader h JOIN staging.SalesOrderDetail d ON d.SourceSalesOrderID=h.SourceSalesOrderID;
GO
