/*
    Script name
        01_seed_adventureworks2022_sales_domain.sql

    Purpose
        Feeds the Oracle AdventureWorks2022 source schema with a complete
        Sales-domain dataset for migration development, reconciliation, batch
        processing, and performance testing.

    Design
        - Self-contained: no other seed script is required.
        - Set-based: generates high-volume transactional rows without row-by-row
          PL/SQL loops.
        - Rollback-friendly: no COMMIT appears until the end of the script.
        - Repeatable: deletes only deterministic ID/code ranges owned by this
          seed script before inserting fresh data.

    Default volume
        - 5,000 generated customers.
        - 100,000 generated sales order headers.
        - 500,000 generated sales order details.

    Scale controls
        Change the DEFINE values below before execution to increase or reduce
        source volume.

    Important
        If the script fails before the final COMMIT, execute ROLLBACK to undo all
        changes made by this script in the current session.
*/

SET DEFINE ON;
SET AUTOCOMMIT OFF;

DEFINE customer_count = 5000;
DEFINE order_count = 100000;
DEFINE details_per_order = 5;

DEFINE base_business_entity_id = 1000000;
DEFINE base_customer_id = 2000000;
DEFINE base_address_id = 3000000;
DEFINE base_sales_order_id = 4000000;

PROMPT Cleaning deterministic Sales-domain seed ranges.

DELETE FROM ADVENTUREWORKS2022.SALES_SALESORDERDETAIL
WHERE SALESORDERID >= &base_sales_order_id
   OR SALESORDERID IN (1000, 1001);

DELETE FROM ADVENTUREWORKS2022.SALES_SALESORDERHEADER
WHERE SALESORDERID >= &base_sales_order_id
   OR SALESORDERID IN (1000, 1001);

DELETE FROM ADVENTUREWORKS2022.SALES_SPECIALOFFERPRODUCT
WHERE (SPECIALOFFERID IN (1, 2) AND PRODUCTID IN (500, 501, 502));

DELETE FROM ADVENTUREWORKS2022.SALES_SPECIALOFFER
WHERE SPECIALOFFERID IN (1, 2);

DELETE FROM ADVENTUREWORKS2022.SALES_CURRENCYRATE
WHERE CURRENCYRATEID IN (700, 701);

DELETE FROM ADVENTUREWORKS2022.SALES_CURRENCY
WHERE CURRENCYCODE IN ('USD', 'EUR');

DELETE FROM ADVENTUREWORKS2022.SALES_CREDITCARD
WHERE CREDITCARDID IN (600, 601);

DELETE FROM ADVENTUREWORKS2022.PURCHASING_SHIPMETHOD
WHERE SHIPMETHODID IN (5, 6);

DELETE FROM ADVENTUREWORKS2022.SALES_CUSTOMER
WHERE CUSTOMERID >= &base_customer_id
   OR CUSTOMERID IN (300, 301);

DELETE FROM ADVENTUREWORKS2022.SALES_STORE
WHERE BUSINESSENTITYID IN (900);

DELETE FROM ADVENTUREWORKS2022.SALES_SALESPERSON
WHERE BUSINESSENTITYID IN (200, 201);

DELETE FROM ADVENTUREWORKS2022.HUMANRESOURCES_EMPLOYEE
WHERE BUSINESSENTITYID IN (200, 201);

DELETE FROM ADVENTUREWORKS2022.PERSON_BUSINESSENTITYADDRESS
WHERE BUSINESSENTITYID >= &base_business_entity_id
   OR BUSINESSENTITYID IN (100, 101, 900);

DELETE FROM ADVENTUREWORKS2022.PERSON_ADDRESS
WHERE ADDRESSID >= &base_address_id
   OR ADDRESSID IN (400, 401);

DELETE FROM ADVENTUREWORKS2022.PERSON_PERSON
WHERE BUSINESSENTITYID >= &base_business_entity_id
   OR BUSINESSENTITYID IN (100, 101, 200, 201);

DELETE FROM ADVENTUREWORKS2022.PERSON_BUSINESSENTITY
WHERE BUSINESSENTITYID >= &base_business_entity_id
   OR BUSINESSENTITYID IN (100, 101, 200, 201, 900);

DELETE FROM ADVENTUREWORKS2022.PRODUCTION_PRODUCT
WHERE PRODUCTID IN (500, 501, 502);

DELETE FROM ADVENTUREWORKS2022.PRODUCTION_PRODUCTSUBCATEGORY
WHERE PRODUCTSUBCATEGORYID IN (20, 21);

DELETE FROM ADVENTUREWORKS2022.PRODUCTION_PRODUCTCATEGORY
WHERE PRODUCTCATEGORYID IN (10);

DELETE FROM ADVENTUREWORKS2022.PERSON_ADDRESSTYPE
WHERE ADDRESSTYPEID IN (1, 2);

DELETE FROM ADVENTUREWORKS2022.PERSON_STATEPROVINCE
WHERE STATEPROVINCEID IN (79, 80);

DELETE FROM ADVENTUREWORKS2022.SALES_SALESTERRITORY
WHERE TERRITORYID IN (1, 2);

DELETE FROM ADVENTUREWORKS2022.PERSON_COUNTRYREGION
WHERE COUNTRYREGIONCODE IN ('US', 'CA');

PROMPT Seeding reference data.

INSERT INTO ADVENTUREWORKS2022.PERSON_COUNTRYREGION
    (COUNTRYREGIONCODE, NAME)
SELECT 'US', 'United States' FROM DUAL
UNION ALL
SELECT 'CA', 'Canada' FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.SALES_SALESTERRITORY
    (TERRITORYID, NAME, COUNTRYREGIONCODE, "GROUP", SALESYTD, SALESLASTYEAR, COSTYTD, COSTLASTYEAR)
SELECT 1, 'Northwest', 'US', 'North America', 1200000.0000, 1100000.0000, 450000.0000, 420000.0000 FROM DUAL
UNION ALL
SELECT 2, 'Canada', 'CA', 'North America', 980000.0000, 910000.0000, 390000.0000, 360000.0000 FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.PERSON_STATEPROVINCE
    (STATEPROVINCEID, STATEPROVINCECODE, COUNTRYREGIONCODE, ISONLYSTATEPROVINCEFLAG, NAME, TERRITORYID)
SELECT 79, 'WA', 'US', 1, 'Washington', 1 FROM DUAL
UNION ALL
SELECT 80, 'BC', 'CA', 1, 'British Columbia', 2 FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.PERSON_ADDRESSTYPE
    (ADDRESSTYPEID, NAME)
SELECT 1, 'Billing' FROM DUAL
UNION ALL
SELECT 2, 'Shipping' FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.PRODUCTION_PRODUCTCATEGORY
    (PRODUCTCATEGORYID, NAME)
VALUES
    (10, 'Bikes');

INSERT INTO ADVENTUREWORKS2022.PRODUCTION_PRODUCTSUBCATEGORY
    (PRODUCTSUBCATEGORYID, PRODUCTCATEGORYID, NAME)
SELECT 20, 10, 'Road Bikes' FROM DUAL
UNION ALL
SELECT 21, 10, 'Mountain Bikes' FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.PRODUCTION_PRODUCT
(
    PRODUCTID,
    NAMEC,
    PRODUCTNUMBER,
    MAKEFLAG,
    FINISHEDGOODSFLAG,
    COLOR,
    SAFETYSTOCKLEVEL,
    REORDERPOINT,
    STANDARDCOST,
    LISTPRICE,
    SIZEC,
    WEIGHT,
    DAYSTOMANUFACTURE,
    PRODUCTSUBCATEGORYID,
    SELLSTARTDATE
)
SELECT 500, 'Road-150 Red, 48', 'BK-R93R-48', 1, 1, 'Red', 100, 75, 2171.2942, 3578.2700, '48', 15.42, 4, 20, DATE '2011-05-01' FROM DUAL
UNION ALL
SELECT 501, 'Road-250 Black, 52', 'BK-R89B-52', 1, 1, 'Black', 100, 75, 1518.7864, 2443.3500, '52', 16.20, 4, 20, DATE '2011-05-01' FROM DUAL
UNION ALL
SELECT 502, 'Mountain-200 Silver, 46', 'BK-M68S-46', 1, 1, 'Silver', 100, 75, 1265.6195, 2319.9900, '46', 18.90, 4, 21, DATE '2011-05-01' FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.PURCHASING_SHIPMETHOD
    (SHIPMETHODID, NAME, SHIPBASE, SHIPRATE)
SELECT 5, 'CARGO TRANSPORT 5', 8.9900, 1.4900 FROM DUAL
UNION ALL
SELECT 6, 'OVERNIGHT J-FAST', 21.9900, 2.9900 FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.SALES_CREDITCARD
    (CREDITCARDID, CARDTYPE, CARDNUMBER, EXPMONTH, EXPYEAR)
SELECT 600, 'Vista', '1111222233334444', 12, 2028 FROM DUAL
UNION ALL
SELECT 601, 'SuperiorCard', '5555666677778888', 6, 2029 FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.SALES_CURRENCY
    (CURRENCYCODE, NAME)
SELECT 'USD', 'US Dollar' FROM DUAL
UNION ALL
SELECT 'EUR', 'Euro' FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.SALES_CURRENCYRATE
    (CURRENCYRATEID, CURRENCYRATEDATE, FROMCURRENCYCODE, TOCURRENCYCODE, AVERAGERATE, ENDOFDAYRATE)
SELECT 700, TIMESTAMP '2011-05-31 00:00:00', 'USD', 'USD', 1.0000, 1.0000 FROM DUAL
UNION ALL
SELECT 701, TIMESTAMP '2011-05-31 00:00:00', 'EUR', 'USD', 1.4100, 1.4125 FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.SALES_SPECIALOFFER
    (SPECIALOFFERID, DESCRIPTION, DISCOUNTPCT, TYPE, CATEGORY, STARTDATE, ENDDATE, MINQTY, MAXQTY)
SELECT 1, 'No Discount', 0.0000, 'No Discount', 'No Discount', DATE '2011-01-01', DATE '2014-12-31', 0, NULL FROM DUAL
UNION ALL
SELECT 2, 'Volume Discount 5%', 0.0500, 'Volume Discount', 'Customer', DATE '2011-01-01', DATE '2014-12-31', 10, NULL FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.SALES_SPECIALOFFERPRODUCT
    (SPECIALOFFERID, PRODUCTID)
SELECT 1, 500 FROM DUAL
UNION ALL
SELECT 1, 501 FROM DUAL
UNION ALL
SELECT 1, 502 FROM DUAL
UNION ALL
SELECT 2, 500 FROM DUAL
UNION ALL
SELECT 2, 501 FROM DUAL
UNION ALL
SELECT 2, 502 FROM DUAL;

PROMPT Seeding baseline people, store, salespeople, customers, and addresses.

INSERT INTO ADVENTUREWORKS2022.PERSON_BUSINESSENTITY
    (BUSINESSENTITYID)
SELECT 100 FROM DUAL
UNION ALL SELECT 101 FROM DUAL
UNION ALL SELECT 200 FROM DUAL
UNION ALL SELECT 201 FROM DUAL
UNION ALL SELECT 900 FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.PERSON_PERSON
    (BUSINESSENTITYID, PERSONTYPE, TITLE, FIRSTNAME, MIDDLENAME, LASTNAME, EMAILPROMOTION)
SELECT 100, 'IN', NULL, 'Sofia', NULL, 'Martinez', 0 FROM DUAL
UNION ALL
SELECT 101, 'IN', NULL, 'Noah', NULL, 'Wilson', 1 FROM DUAL
UNION ALL
SELECT 200, 'SP', 'Ms.', 'Alicia', NULL, 'Nguyen', 1 FROM DUAL
UNION ALL
SELECT 201, 'SP', 'Mr.', 'Daniel', NULL, 'Brooks', 1 FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.HUMANRESOURCES_EMPLOYEE
    (BUSINESSENTITYID, NATIONALIDNUMBER, LOGINID, JOBTITLE, BIRTHDATE, MARITALSTATUS, GENDER, HIREDATE)
SELECT 200, '987654321', 'adventureworks\alicia0', 'Sales Representative', DATE '1986-04-12', 'S', 'F', DATE '2010-03-01' FROM DUAL
UNION ALL
SELECT 201, '987654322', 'adventureworks\daniel0', 'Sales Representative', DATE '1982-09-20', 'M', 'M', DATE '2009-07-15' FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.SALES_SALESPERSON
    (BUSINESSENTITYID, TERRITORYID, SALESQUOTA, BONUS, COMMISSIONPCT, SALESYTD, SALESLASTYEAR)
SELECT 200, 1, 250000.0000, 5000.0000, 0.0150, 900000.0000, 850000.0000 FROM DUAL
UNION ALL
SELECT 201, 2, 225000.0000, 4500.0000, 0.0125, 780000.0000, 720000.0000 FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.SALES_STORE
    (BUSINESSENTITYID, NAME, SALESPERSONID, DEMOGRAPHICS)
VALUES
    (900, 'Generated Retail Store', 200, NULL);

INSERT INTO ADVENTUREWORKS2022.PERSON_ADDRESS
    (ADDRESSID, ADDRESSLINE1, CITY, STATEPROVINCEID, POSTALCODE)
SELECT 400, '100 Market Street', 'Seattle', 79, '98101' FROM DUAL
UNION ALL
SELECT 401, '200 Harbor Road', 'Vancouver', 80, 'V6B1A1' FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.PERSON_BUSINESSENTITYADDRESS
    (BUSINESSENTITYID, ADDRESSID, ADDRESSTYPEID)
SELECT 100, 400, 1 FROM DUAL
UNION ALL
SELECT 101, 401, 2 FROM DUAL
UNION ALL
SELECT 900, 400, 1 FROM DUAL;

INSERT INTO ADVENTUREWORKS2022.SALES_CUSTOMER
    (CUSTOMERID, PERSONID, STOREID, TERRITORYID, ACCOUNTNUMBER)
SELECT 300, 100, NULL, 1, 'AW00000300' FROM DUAL
UNION ALL
SELECT 301, 101, 900, 2, 'AW00000301' FROM DUAL;

PROMPT Generating high-volume customer master data.

INSERT INTO ADVENTUREWORKS2022.PERSON_BUSINESSENTITY
    (BUSINESSENTITYID)
SELECT
    &base_business_entity_id + LEVEL - 1 AS BUSINESSENTITYID
FROM DUAL
CONNECT BY LEVEL <= &customer_count;

INSERT INTO ADVENTUREWORKS2022.PERSON_PERSON
    (BUSINESSENTITYID, PERSONTYPE, FIRSTNAME, MIDDLENAME, LASTNAME, EMAILPROMOTION)
SELECT
    &base_business_entity_id + LEVEL - 1 AS BUSINESSENTITYID,
    'IN' AS PERSONTYPE,
    'Customer' AS FIRSTNAME,
    NULL AS MIDDLENAME,
    'Generated ' || TO_CHAR(LEVEL) AS LASTNAME,
    MOD(LEVEL, 3) AS EMAILPROMOTION
FROM DUAL
CONNECT BY LEVEL <= &customer_count;

INSERT INTO ADVENTUREWORKS2022.PERSON_ADDRESS
    (ADDRESSID, ADDRESSLINE1, CITY, STATEPROVINCEID, POSTALCODE)
SELECT
    &base_address_id + LEVEL - 1 AS ADDRESSID,
    TO_CHAR(LEVEL) || ' Generated Sales Avenue' AS ADDRESSLINE1,
    CASE MOD(LEVEL, 6)
        WHEN 0 THEN 'Seattle'
        WHEN 1 THEN 'Bellevue'
        WHEN 2 THEN 'Tacoma'
        WHEN 3 THEN 'Redmond'
        WHEN 4 THEN 'Everett'
        ELSE 'Vancouver'
    END AS CITY,
    CASE WHEN MOD(LEVEL, 6) = 5 THEN 80 ELSE 79 END AS STATEPROVINCEID,
    LPAD(TO_CHAR(98000 + MOD(LEVEL, 900)), 5, '0') AS POSTALCODE
FROM DUAL
CONNECT BY LEVEL <= &customer_count;

INSERT INTO ADVENTUREWORKS2022.PERSON_BUSINESSENTITYADDRESS
    (BUSINESSENTITYID, ADDRESSID, ADDRESSTYPEID)
SELECT
    &base_business_entity_id + LEVEL - 1 AS BUSINESSENTITYID,
    &base_address_id + LEVEL - 1 AS ADDRESSID,
    CASE WHEN MOD(LEVEL, 2) = 0 THEN 1 ELSE 2 END AS ADDRESSTYPEID
FROM DUAL
CONNECT BY LEVEL <= &customer_count;

INSERT INTO ADVENTUREWORKS2022.SALES_CUSTOMER
    (CUSTOMERID, PERSONID, STOREID, TERRITORYID, ACCOUNTNUMBER)
SELECT
    &base_customer_id + LEVEL - 1 AS CUSTOMERID,
    &base_business_entity_id + LEVEL - 1 AS PERSONID,
    CASE WHEN MOD(LEVEL, 20) = 0 THEN 900 ELSE NULL END AS STOREID,
    CASE WHEN MOD(LEVEL, 6) = 5 THEN 2 ELSE 1 END AS TERRITORYID,
    'AW' || LPAD(TO_CHAR(&base_customer_id + LEVEL - 1), 10, '0') AS ACCOUNTNUMBER
FROM DUAL
CONNECT BY LEVEL <= &customer_count;

PROMPT Creating generated sales order headers.

INSERT INTO ADVENTUREWORKS2022.SALES_SALESORDERHEADER
(
    SALESORDERID,
    REVISIONNUMBER,
    ORDERDATE,
    DUEDATE,
    SHIPDATE,
    STATUS,
    ONLINEORDERFLAG,
    PURCHASEORDERNUMBER,
    ACCOUNTNUMBER,
    CUSTOMERID,
    SALESPERSONID,
    TERRITORYID,
    BILLTOADDRESSID,
    SHIPTOADDRESSID,
    SHIPMETHODID,
    CREDITCARDID,
    CREDITCARDAPPROVALCODE,
    CURRENCYRATEID,
    SUBTOTAL,
    TAXAMT,
    FREIGHT,
    "COMMENT"
)
SELECT
    &base_sales_order_id + order_n - 1 AS SALESORDERID,
    0 AS REVISIONNUMBER,
    DATE '2011-05-01' + MOD(order_n - 1, 1095) AS ORDERDATE,
    DATE '2011-05-01' + MOD(order_n - 1, 1095) + 12 AS DUEDATE,
    DATE '2011-05-01' + MOD(order_n - 1, 1095) + 7 AS SHIPDATE,
    5 AS STATUS,
    CASE WHEN MOD(order_n, 4) = 0 THEN 0 ELSE 1 END AS ONLINEORDERFLAG,
    'PO-' || TO_CHAR(&base_sales_order_id + order_n - 1) AS PURCHASEORDERNUMBER,
    '10-' || LPAD(TO_CHAR(&base_customer_id + MOD(order_n - 1, &customer_count)), 10, '0') AS ACCOUNTNUMBER,
    &base_customer_id + MOD(order_n - 1, &customer_count) AS CUSTOMERID,
    CASE WHEN MOD(order_n, 6) = 5 THEN 201 ELSE 200 END AS SALESPERSONID,
    CASE WHEN MOD(order_n, 6) = 5 THEN 2 ELSE 1 END AS TERRITORYID,
    &base_address_id + MOD(order_n - 1, &customer_count) AS BILLTOADDRESSID,
    &base_address_id + MOD(order_n - 1, &customer_count) AS SHIPTOADDRESSID,
    CASE WHEN MOD(order_n, 10) = 0 THEN 6 ELSE 5 END AS SHIPMETHODID,
    CASE WHEN MOD(order_n, 2) = 0 THEN 601 ELSE 600 END AS CREDITCARDID,
    'APPROVED' AS CREDITCARDAPPROVALCODE,
    CASE WHEN MOD(order_n, 6) = 5 THEN 701 ELSE 700 END AS CURRENCYRATEID,
    &details_per_order * (100 + MOD(order_n, 50)) AS SUBTOTAL,
    ROUND((&details_per_order * (100 + MOD(order_n, 50))) * 0.08, 4) AS TAXAMT,
    ROUND((&details_per_order * (100 + MOD(order_n, 50))) * 0.025, 4) AS FREIGHT,
    'Generated high-volume migration test order' AS "COMMENT"
FROM
(
    SELECT LEVEL AS order_n
    FROM DUAL
    CONNECT BY LEVEL <= &order_count
);

PROMPT Creating generated sales order details.

INSERT INTO ADVENTUREWORKS2022.SALES_SALESORDERDETAIL
(
    SALESORDERID,
    SALESORDERDETAILID,
    CARRIERTRACKINGNUMBER,
    ORDERQTY,
    PRODUCTID,
    SPECIALOFFERID,
    UNITPRICE,
    UNITPRICEDISCOUNT
)
SELECT
    &base_sales_order_id + o.order_n - 1 AS SALESORDERID,
    d.detail_n AS SALESORDERDETAILID,
    'TRK-' || TO_CHAR(&base_sales_order_id + o.order_n - 1) || '-' || TO_CHAR(d.detail_n) AS CARRIERTRACKINGNUMBER,
    1 + MOD(o.order_n + d.detail_n, 4) AS ORDERQTY,
    500 + MOD(d.detail_n - 1, 3) AS PRODUCTID,
    CASE WHEN MOD(o.order_n, 20) = 0 THEN 2 ELSE 1 END AS SPECIALOFFERID,
    100 + MOD(o.order_n, 50) AS UNITPRICE,
    CASE WHEN MOD(o.order_n, 20) = 0 THEN 0.0500 ELSE 0.0000 END AS UNITPRICEDISCOUNT
FROM
(
    SELECT LEVEL AS order_n
    FROM DUAL
    CONNECT BY LEVEL <= &order_count
) o
CROSS JOIN
(
    SELECT LEVEL AS detail_n
    FROM DUAL
    CONNECT BY LEVEL <= &details_per_order
) d;

PROMPT Seed metrics.

SELECT 'Generated customers' AS metric_name, COUNT(*) AS metric_value
FROM ADVENTUREWORKS2022.SALES_CUSTOMER
WHERE CUSTOMERID >= &base_customer_id
  AND CUSTOMERID <  &base_customer_id + &customer_count
UNION ALL
SELECT 'Generated sales order headers' AS metric_name, COUNT(*) AS metric_value
FROM ADVENTUREWORKS2022.SALES_SALESORDERHEADER
WHERE SALESORDERID >= &base_sales_order_id
  AND SALESORDERID <  &base_sales_order_id + &order_count
UNION ALL
SELECT 'Generated sales order details' AS metric_name, COUNT(*) AS metric_value
FROM ADVENTUREWORKS2022.SALES_SALESORDERDETAIL
WHERE SALESORDERID >= &base_sales_order_id
  AND SALESORDERID <  &base_sales_order_id + &order_count;

COMMIT;

PROMPT Sales-domain source seed completed and committed.
