/*
    Script name
        03_create_staging_tables.sql

    Purpose
        Creates staging tables that mirror the Sales_Operational.prod source
        contract used by the Sales_Analytics pipeline.

    Scope
        Each table has a generated staging key. Source*ID columns retain keys
        generated by Sales_Operational.prod, not original Oracle IDs. Business
        columns are staged without analytical derivation. Audit columns are
        excluded because staging is transient and controlled by ETL metadata.
*/

USE [Sales_Analytics];
GO

CREATE TABLE [staging].[AddressType] (
    [StagingAddressTypeKey] INT IDENTITY(1,1) NOT NULL,
    [SourceAddressTypeID] INT NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,

    CONSTRAINT [pk_staging_AddressType] PRIMARY KEY CLUSTERED ([StagingAddressTypeKey]),
    CONSTRAINT [uk_staging_AddressType_SourceAddressTypeID] UNIQUE ([SourceAddressTypeID])
);
GO

CREATE TABLE [staging].[ProductCategory] (
    [StagingProductCategoryKey] INT IDENTITY(1,1) NOT NULL,
    [SourceProductCategoryID] INT NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,

    CONSTRAINT [pk_staging_ProductCategory] PRIMARY KEY CLUSTERED ([StagingProductCategoryKey]),
    CONSTRAINT [uk_staging_ProductCategory_SourceProductCategoryID] UNIQUE ([SourceProductCategoryID])
);
GO

CREATE TABLE [staging].[ShipMethod] (
    [StagingShipMethodKey] INT IDENTITY(1,1) NOT NULL,
    [SourceShipMethodID] INT NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,
    [ShipBase] DECIMAL(19,4) NOT NULL,
    [ShipRate] DECIMAL(19,4) NOT NULL,
    
    CONSTRAINT [pk_staging_ShipMethod] PRIMARY KEY CLUSTERED ([StagingShipMethodKey]),
    CONSTRAINT [uk_staging_ShipMethod_SourceShipMethodID] UNIQUE ([SourceShipMethodID])
);
GO

CREATE TABLE [staging].[CountryRegion] (
    [StagingCountryRegionKey] INT IDENTITY(1,1) NOT NULL,
    [SourceCountryRegionID] INT NOT NULL,
    [CountryRegionCode] VARCHAR(3) NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,

    CONSTRAINT [pk_staging_CountryRegion] PRIMARY KEY CLUSTERED ([StagingCountryRegionKey]),
    CONSTRAINT [uk_staging_CountryRegion_SourceCountryRegionID] UNIQUE ([SourceCountryRegionID])
);
GO

CREATE TABLE [staging].[SalesTerritory] (
    [StagingSalesTerritoryKey] INT IDENTITY(1,1) NOT NULL,
    [SourceSalesTerritoryID] INT NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,
    [TerritoryGroup] NVARCHAR(50) NOT NULL,
    [SourceCountryRegionID] INT NOT NULL,

    CONSTRAINT [pk_staging_SalesTerritory] PRIMARY KEY CLUSTERED ([StagingSalesTerritoryKey]),
    CONSTRAINT [uk_staging_SalesTerritory_SourceSalesTerritoryID] UNIQUE ([SourceSalesTerritoryID])
);
GO

CREATE TABLE [staging].[StateProvince] (
    [StagingStateProvinceKey] INT IDENTITY(1,1) NOT NULL,
    [SourceStateProvinceID] INT NOT NULL,
    [StateProvinceCode] CHAR(3) NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,
    [SourceCountryRegionID] INT NOT NULL,
    [SourceSalesTerritoryID] INT NOT NULL,

    CONSTRAINT [pk_staging_StateProvince] PRIMARY KEY CLUSTERED ([StagingStateProvinceKey]),
    CONSTRAINT [uk_staging_StateProvince_SourceStateProvinceID] UNIQUE ([SourceStateProvinceID])
);
GO

CREATE TABLE [staging].[SpecialOffer] (
    [StagingSpecialOfferKey] INT IDENTITY(1,1) NOT NULL,
    [SourceSpecialOfferID] INT NOT NULL,
    [Description] NVARCHAR(255) NOT NULL,
    [DiscountPct] DECIMAL(10,4) NOT NULL,
    [OfferType] NVARCHAR(50) NOT NULL,
    [Category] NVARCHAR(50) NOT NULL,
    [StartDate] DATE NOT NULL,
    [EndDate] DATE NOT NULL,
    [MinQty] INT NOT NULL,
    [MaxQty] INT NULL,

    CONSTRAINT [pk_staging_SpecialOffer] PRIMARY KEY CLUSTERED ([StagingSpecialOfferKey]),
    CONSTRAINT [uk_staging_SpecialOffer_SourceSpecialOfferID] UNIQUE ([SourceSpecialOfferID])
);
GO

CREATE TABLE [staging].[Currency] (
    [StagingCurrencyKey] INT IDENTITY(1,1) NOT NULL,
    [SourceCurrencyID] INT NOT NULL,
    [CurrencyCode] CHAR(3) NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,

    CONSTRAINT [pk_staging_Currency] PRIMARY KEY CLUSTERED ([StagingCurrencyKey]),
    CONSTRAINT [uk_staging_Currency_SourceCurrencyID] UNIQUE ([SourceCurrencyID])
);
GO

CREATE TABLE [staging].[CurrencyRate] (
    [StagingCurrencyRateKey] INT IDENTITY(1,1) NOT NULL,
    [SourceCurrencyRateID] INT NOT NULL,
    [CurrencyRateDate] DATETIME2(7) NOT NULL,
    [SourceFromCurrencyID] INT NOT NULL,
    [SourceToCurrencyID] INT NOT NULL,
    [AverageRate] DECIMAL(19,4) NOT NULL,
    [EndOfDayRate] DECIMAL(19,4) NOT NULL,

    CONSTRAINT [pk_staging_CurrencyRate] PRIMARY KEY CLUSTERED ([StagingCurrencyRateKey]),
    CONSTRAINT [uk_staging_CurrencyRate_SourceCurrencyRateID] UNIQUE ([SourceCurrencyRateID])
);
GO

CREATE TABLE [staging].[CreditCard] (
    [StagingCreditCardKey] INT IDENTITY(1,1) NOT NULL,
    [SourceCreditCardID] INT NOT NULL,
    [CardType] NVARCHAR(50) NOT NULL,
    [CardNumber] VARCHAR(25) NOT NULL,
    [ExpMonth] TINYINT NOT NULL,
    [ExpYear] SMALLINT NOT NULL,

    CONSTRAINT [pk_staging_CreditCard] PRIMARY KEY CLUSTERED ([StagingCreditCardKey]),
    CONSTRAINT [uk_staging_CreditCard_SourceCreditCardID] UNIQUE ([SourceCreditCardID])
);
GO

CREATE TABLE [staging].[Address] (
    [StagingAddressKey] INT IDENTITY(1,1) NOT NULL,
    [SourceAddressID] INT NOT NULL,
    [AddressLine1] NVARCHAR(60) NOT NULL,
    [AddressLine2] NVARCHAR(60) NULL,
    [City] NVARCHAR(30) NOT NULL,
    [SourceStateProvinceID] INT NOT NULL,
    [PostalCode] VARCHAR(15) NOT NULL,
    [SourceAddressTypeID] INT NULL,

    CONSTRAINT [pk_staging_Address] PRIMARY KEY CLUSTERED ([StagingAddressKey]),
    CONSTRAINT [uk_staging_Address_SourceAddressID] UNIQUE ([SourceAddressID])
);
GO

CREATE TABLE [staging].[Product] (
    [StagingProductKey] INT IDENTITY(1,1) NOT NULL,
    [SourceProductID] INT NOT NULL,
    [ProductNumber] VARCHAR(25) NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,
    [Color] NVARCHAR(15) NULL,
    [SafetyStockLevel] SMALLINT NOT NULL,
    [ReorderPoint] SMALLINT NOT NULL,
    [StandardCost] DECIMAL(19,4) NOT NULL,
    [ListPrice] DECIMAL(19,4) NOT NULL,
    [Size] NVARCHAR(5) NULL,
    [Weight] DECIMAL(8,2) NULL,
    [SourceProductCategoryID] INT NULL,
    [SellStartDate] DATE NOT NULL,
    [SellEndDate] DATE NULL,
    [DiscontinuedDate] DATE NULL,

    CONSTRAINT [pk_staging_Product] PRIMARY KEY CLUSTERED ([StagingProductKey]),
    CONSTRAINT [uk_staging_Product_SourceProductID] UNIQUE ([SourceProductID])
);
GO

CREATE TABLE [staging].[SalesPerson] (
    [StagingSalesPersonKey] INT IDENTITY(1,1) NOT NULL,
    [SourceSalesPersonID] INT NOT NULL,
    [SourceSalesTerritoryID] INT NULL,
    [Title] NVARCHAR(8) NULL,
    [FirstName] NVARCHAR(50) NOT NULL,
    [MiddleName] NVARCHAR(50) NULL,
    [LastName] NVARCHAR(50) NOT NULL,
    [JobTitle] NVARCHAR(50) NOT NULL,
    [Gender] CHAR(1) NOT NULL,
    [HireDate] DATE NOT NULL,
    [SalesQuota] DECIMAL(19,4) NULL,
    [Bonus] DECIMAL(19,4) NOT NULL,
    [CommissionPct] DECIMAL(10,4) NOT NULL,
    [SalesYTD] DECIMAL(19,4) NOT NULL,
    [SalesLastYear] DECIMAL(19,4) NOT NULL,
    
    CONSTRAINT [pk_staging_SalesPerson] PRIMARY KEY CLUSTERED ([StagingSalesPersonKey]),
    CONSTRAINT [uk_staging_SalesPerson_SourceSalesPersonID] UNIQUE ([SourceSalesPersonID])
);
GO

CREATE TABLE [staging].[Customer] (
    [StagingCustomerKey] INT IDENTITY(1,1) NOT NULL,
    [SourceCustomerID] INT NOT NULL,
    [SourceSalesTerritoryID] INT NULL,
    [PersonType] CHAR(2) NULL,
    [Title] NVARCHAR(8) NULL,
    [FirstName] NVARCHAR(50) NULL,
    [MiddleName] NVARCHAR(50) NULL,
    [LastName] NVARCHAR(50) NULL,
    [AccountNumber] VARCHAR(20) NULL,
    
    CONSTRAINT [pk_staging_Customer] PRIMARY KEY CLUSTERED ([StagingCustomerKey]),
    CONSTRAINT [uk_staging_Customer_SourceCustomerID] UNIQUE ([SourceCustomerID])
);
GO

CREATE TABLE [staging].[SalesOrderHeader] (
    [StagingSalesOrderHeaderKey] BIGINT IDENTITY(1,1) NOT NULL,
    [SourceSalesOrderID] BIGINT NOT NULL,
    [RevisionNumber] TINYINT NOT NULL,
    [OrderDate] DATETIME2(7) NOT NULL,
    [DueDate] DATETIME2(7) NOT NULL,
    [ShipDate] DATETIME2(7) NULL,
    [Status] TINYINT NOT NULL,
    [SalesOrderNumber] VARCHAR(25) NOT NULL,
    [PurchaseOrderNumber] VARCHAR(25) NULL,
    [AccountNumber] VARCHAR(20) NULL,
    [SourceCustomerID] INT NOT NULL,
    [SourceSalesPersonID] INT NULL,
    [SourceSalesTerritoryID] INT NULL,
    [SourceBillToAddressID] INT NOT NULL,
    [SourceShipToAddressID] INT NOT NULL,
    [SourceShipMethodID] INT NOT NULL,
    [SourceCreditCardID] INT NULL,
    [SourceCurrencyRateID] INT NULL,
    [SubTotal] DECIMAL(19,4) NOT NULL,
    [TaxAmt] DECIMAL(19,4) NOT NULL,
    [Freight] DECIMAL(19,4) NOT NULL,
    [TotalDue] DECIMAL(19,4) NOT NULL,
    [Comment] NVARCHAR(128) NULL,

    CONSTRAINT [pk_staging_SalesOrderHeader] PRIMARY KEY CLUSTERED ([StagingSalesOrderHeaderKey]),
    CONSTRAINT [uk_staging_SalesOrderHeader_SourceSalesOrderID] UNIQUE ([SourceSalesOrderID])
);
GO

CREATE TABLE [staging].[SalesOrderDetail] (
    [StagingSalesOrderDetailKey] BIGINT IDENTITY(1,1) NOT NULL,
    [SourceSalesOrderID] BIGINT NOT NULL,
    [SourceSalesOrderDetailID] BIGINT NOT NULL,
    [SourceProductID] INT NOT NULL,
    [SourceSpecialOfferID] INT NOT NULL,
    [CarrierTrackingNumber] VARCHAR(25) NULL,
    [OrderQty] SMALLINT NOT NULL,
    [UnitPrice] DECIMAL(19,4) NOT NULL,
    [UnitPriceDiscount] DECIMAL(19,4) NOT NULL,
    [LineTotal] DECIMAL(19,4) NOT NULL,

    CONSTRAINT [pk_staging_SalesOrderDetail] PRIMARY KEY CLUSTERED ([StagingSalesOrderDetailKey]),
    CONSTRAINT [uk_staging_SalesOrderDetail_SourceOrderDetail] UNIQUE ([SourceSalesOrderID], [SourceSalesOrderDetailID])
);
GO
