/*============================================================================
  DataOps_Control Runtime Test Cleanup
  Scenario: Sales_Analytics_Migration - Successful Full Flow

  Purpose:
  - Removes runtime and observability data generated by the scenario marker:
    SALES_ANALYTICS_SUCCESS_FULL_FLOW

  Notes:
  - Metadata and reference seed data are not removed.
============================================================================*/

USE [DataOps_Control];
GO

SET NOCOUNT ON;

DECLARE @scenario_name VARCHAR(100) = 'SALES_ANALYTICS_SUCCESS_FULL_FLOW';

;WITH scenario_runs AS
(
    SELECT [id] AS [execution_run_id]
    FROM [runtime].[execution_runs]
    WHERE [created_by] = @scenario_name
),
scenario_steps AS
(
    SELECT es.[id] AS [execution_step_id]
    FROM [runtime].[execution_steps] es
    INNER JOIN scenario_runs sr
        ON sr.[execution_run_id] = es.[execution_run_id]
)
DELETE mr
FROM [observability].[monitoring_results] mr
INNER JOIN scenario_steps ss
    ON ss.[execution_step_id] = mr.[execution_step_id];

;WITH scenario_runs AS
(
    SELECT [id] AS [execution_run_id]
    FROM [runtime].[execution_runs]
    WHERE [created_by] = @scenario_name
),
scenario_steps AS
(
    SELECT es.[id] AS [execution_step_id]
    FROM [runtime].[execution_steps] es
    INNER JOIN scenario_runs sr
        ON sr.[execution_run_id] = es.[execution_run_id]
)
DELETE rr
FROM [observability].[reconciliation_results] rr
INNER JOIN scenario_steps ss
    ON ss.[execution_step_id] = rr.[execution_step_id];

;WITH scenario_runs AS
(
    SELECT [id] AS [execution_run_id]
    FROM [runtime].[execution_runs]
    WHERE [created_by] = @scenario_name
),
scenario_steps AS
(
    SELECT es.[id] AS [execution_step_id]
    FROM [runtime].[execution_steps] es
    INNER JOIN scenario_runs sr
        ON sr.[execution_run_id] = es.[execution_run_id]
)
DELETE vr
FROM [observability].[validation_results] vr
INNER JOIN scenario_steps ss
    ON ss.[execution_step_id] = vr.[execution_step_id];

;WITH scenario_runs AS
(
    SELECT [id] AS [execution_run_id]
    FROM [runtime].[execution_runs]
    WHERE [created_by] = @scenario_name
),
scenario_steps AS
(
    SELECT es.[id] AS [execution_step_id]
    FROM [runtime].[execution_steps] es
    INNER JOIN scenario_runs sr
        ON sr.[execution_run_id] = es.[execution_run_id]
)
DELETE el
FROM [observability].[error_logs] el
INNER JOIN scenario_steps ss
    ON ss.[execution_step_id] = el.[execution_step_id];

;WITH scenario_runs AS
(
    SELECT [id] AS [execution_run_id]
    FROM [runtime].[execution_runs]
    WHERE [created_by] = @scenario_name
)
DELETE es
FROM [runtime].[execution_steps] es
INNER JOIN scenario_runs sr
    ON sr.[execution_run_id] = es.[execution_run_id];

DELETE FROM [runtime].[execution_runs]
WHERE [created_by] = @scenario_name;

SELECT
    @scenario_name AS [scenario_name],
    'Cleanup completed' AS [cleanup_status];
GO
