/*============================================================================
  DataOps_Control
  Cleanup Script: Sales Domain Metadata

  Purpose:
  - Removes seeded metadata for the Oracle to SQL Server Migration - Sales Domain.
  - Removes v2 dependency and process-action metadata before parent metadata.
  - Supports the simplified v2 hierarchy where Sales_Operational_Migration and
    Sales_Analytics_Migration are root orchestration processes.

  Important execution order:
  - Run this script before 02_cleanup_seed_reference_data.sql.
  - Runtime and observability rows generated by tests are removed first because
    they may reference seeded project/process metadata.
============================================================================*/

USE [DataOps_Control];
GO

/*============================================================================
  1. Runtime and Observability Test Data
============================================================================*/

IF OBJECT_ID('[observability].[monitoring_results]', 'U') IS NOT NULL
BEGIN
    DELETE mr
    FROM [observability].[monitoring_results] mr
    INNER JOIN [runtime].[execution_steps] es
        ON es.[id] = mr.[execution_step_id]
    INNER JOIN [runtime].[execution_runs] er
        ON er.[id] = es.[execution_run_id]
    WHERE er.[project_id] = 1;
END;
GO

IF OBJECT_ID('[observability].[error_logs]', 'U') IS NOT NULL
BEGIN
    DELETE el
    FROM [observability].[error_logs] el
    INNER JOIN [runtime].[execution_steps] es
        ON es.[id] = el.[execution_step_id]
    INNER JOIN [runtime].[execution_runs] er
        ON er.[id] = es.[execution_run_id]
    WHERE er.[project_id] = 1;
END;
GO

IF OBJECT_ID('[observability].[validation_results]', 'U') IS NOT NULL
BEGIN
    DELETE vr
    FROM [observability].[validation_results] vr
    INNER JOIN [runtime].[execution_steps] es
        ON es.[id] = vr.[execution_step_id]
    INNER JOIN [runtime].[execution_runs] er
        ON er.[id] = es.[execution_run_id]
    WHERE er.[project_id] = 1;
END;
GO

IF OBJECT_ID('[observability].[reconciliation_results]', 'U') IS NOT NULL
BEGIN
    DELETE rr
    FROM [observability].[reconciliation_results] rr
    INNER JOIN [runtime].[execution_steps] es
        ON es.[id] = rr.[execution_step_id]
    INNER JOIN [runtime].[execution_runs] er
        ON er.[id] = es.[execution_run_id]
    WHERE er.[project_id] = 1;
END;
GO

IF OBJECT_ID('[runtime].[execution_steps]', 'U') IS NOT NULL
BEGIN
    DELETE es
    FROM [runtime].[execution_steps] es
    INNER JOIN [runtime].[execution_runs] er
        ON er.[id] = es.[execution_run_id]
    WHERE er.[project_id] = 1;
END;
GO

IF OBJECT_ID('[runtime].[execution_runs]', 'U') IS NOT NULL
BEGIN
    DELETE FROM [runtime].[execution_runs]
    WHERE [project_id] = 1;
END;
GO

/*============================================================================
  2. v2 Process Metadata
============================================================================*/

IF OBJECT_ID('[metadata].[project_process_actions]', 'U') IS NOT NULL
BEGIN
    DELETE a
    FROM [metadata].[project_process_actions] a
    INNER JOIN [metadata].[project_processes] p
        ON p.[id] = a.[project_process_id]
    WHERE p.[project_id] = 1;
END;
GO

IF OBJECT_ID('[metadata].[project_process_monitoring_metrics]', 'U') IS NOT NULL
BEGIN
    DELETE m
    FROM [metadata].[project_process_monitoring_metrics] m
    INNER JOIN [metadata].[project_processes] p
        ON p.[id] = m.[project_process_id]
    WHERE p.[project_id] = 1;
END;
GO

IF OBJECT_ID('[metadata].[project_process_dependencies]', 'U') IS NOT NULL
BEGIN
    DELETE d
    FROM [metadata].[project_process_dependencies] d
    INNER JOIN [metadata].[project_processes] p
        ON p.[id] = d.[project_process_id]
    WHERE p.[project_id] = 1;
END;
GO

/*============================================================================
  3. Batch Metadata
============================================================================*/

DELETE ptb
FROM [metadata].[project_process_table_batches] ptb
INNER JOIN [metadata].[project_processes] p
    ON p.[id] = ptb.[process_id]
WHERE p.[project_id] = 1;
GO

DELETE b
FROM [metadata].[project_table_batches] b
INNER JOIN [metadata].[project_tables] t
    ON t.[id] = b.[batch_source_table_id]
WHERE t.[database_id] IN
(
    SELECT [id]
    FROM [metadata].[project_databases]
    WHERE [project_id] = 1
);
GO

/*============================================================================
  4. Process, Table, and Database Metadata
============================================================================*/

DELETE pt
FROM [metadata].[project_process_tables] pt
INNER JOIN [metadata].[project_processes] p
    ON p.[id] = pt.[process_id]
WHERE p.[project_id] = 1;
GO

DELETE tm
FROM [metadata].[project_table_mappings] tm
INNER JOIN [metadata].[project_tables] src
    ON src.[id] = tm.[table_source_id]
INNER JOIN [metadata].[project_databases] db
    ON db.[id] = src.[database_id]
WHERE db.[project_id] = 1;
GO

IF OBJECT_ID('[metadata].[project_columns]', 'U') IS NOT NULL
BEGIN
    DELETE c
    FROM [metadata].[project_columns] c
    INNER JOIN [metadata].[project_tables] t
        ON t.[id] = c.[table_id]
    INNER JOIN [metadata].[project_databases] db
        ON db.[id] = t.[database_id]
    WHERE db.[project_id] = 1;
END;
GO

DELETE t
FROM [metadata].[project_tables] t
INNER JOIN [metadata].[project_databases] db
    ON db.[id] = t.[database_id]
WHERE db.[project_id] = 1;
GO

DELETE FROM [metadata].[project_processes]
WHERE [project_id] = 1;
GO

DELETE FROM [metadata].[project_database_mappings]
WHERE [database_source_id] IN
(
    SELECT [id]
    FROM [metadata].[project_databases]
    WHERE [project_id] = 1
)
OR [database_target_id] IN
(
    SELECT [id]
    FROM [metadata].[project_databases]
    WHERE [project_id] = 1
);
GO

DELETE FROM [metadata].[project_databases]
WHERE [project_id] = 1;
GO

DELETE FROM [metadata].[projects]
WHERE [id] = 1;
GO
