-- WARNING:
-- This script is destructive and intended only for the local Oracle XE Docker environment.
-- Do not execute against shared, UAT, certification, or production databases.
-- =============================================================================
-- Purpose          : Delete only base-seed bridge, relationship, and history rows.
-- Execution order  : 02 of 05; run after transactional cleanup.
-- Connection user  : SYSTEM; CURRENT_SCHEMA is set to ADVENTUREWORKS2022.
-- Tables affected  : Cross-domain bridges and parent-child history tables.
-- Notes            : Run before master and reference cleanup.
-- =============================================================================

ALTER SESSION SET CURRENT_SCHEMA = ADVENTUREWORKS2022;

DELETE FROM SALES_SPECIALOFFERPRODUCT
WHERE (SPECIALOFFERID = 1 AND PRODUCTID IN (101, 102, 103))
   OR (SPECIALOFFERID = 2 AND PRODUCTID = 101);
DELETE FROM SALES_PERSONCREDITCARD WHERE BUSINESSENTITYID IN (3, 4);
DELETE FROM SALES_SALESPERSONQUOTAHISTORY WHERE BUSINESSENTITYID = 1;
DELETE FROM SALES_SALESTERRITORYHISTORY WHERE BUSINESSENTITYID = 1;

DELETE FROM PURCHASING_PRODUCTVENDOR
WHERE PRODUCTID IN (101, 102, 103) AND BUSINESSENTITYID IN (7, 8);

DELETE FROM PRODUCTION_BILLOFMATERIALS WHERE BILLOFMATERIALSID = 1;
DELETE FROM PRODUCTION_PRODUCTDOCUMENT WHERE PRODUCTID = 101 AND DOCUMENTNODE = '/1/';
DELETE FROM PRODUCTION_PRODUCTPRODUCTPHOTO WHERE PRODUCTID = 101 AND PRODUCTPHOTOID = 1;
DELETE FROM PRODUCTION_PRODUCTMODELILLUSTRATION WHERE PRODUCTMODELID = 1 AND ILLUSTRATIONID = 1;
DELETE FROM PRODUCTION_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE
WHERE PRODUCTMODELID IN (1, 2) AND PRODUCTDESCRIPTIONID IN (1, 2);

DELETE FROM HUMANRESOURCES_EMPLOYEEDEPARTMENTHISTORY
WHERE BUSINESSENTITYID IN (1, 2);

DELETE FROM PERSON_BUSINESSENTITYCONTACT
WHERE BUSINESSENTITYID IN (6, 7) AND PERSONID IN (3, 4);
DELETE FROM PERSON_BUSINESSENTITYADDRESS
WHERE BUSINESSENTITYID IN (1, 2, 3, 4, 6, 7);

DELETE FROM SALES_COUNTRYREGIONCURRENCY
WHERE (COUNTRYREGIONCODE, CURRENCYCODE) IN (
  ('US', 'USD'), ('CA', 'CAD'), ('PE', 'PEN')
);

COMMIT;

PROMPT [02] Seeded bridge and relationship data removed.
