-- WARNING:
-- This script is destructive and intended only for the local Oracle XE Docker environment.
-- Do not execute against shared, UAT, certification, or production databases.
-- =============================================================================
-- Purpose          : Delete only base-seed master and domain-parent rows.
-- Execution order  : 03 of 05; run after bridge cleanup.
-- Connection user  : SYSTEM; CURRENT_SCHEMA is set to ADVENTUREWORKS2022.
-- Tables affected  : Sales, Purchasing, Production, Person, and HR masters.
-- Notes            : Reference rows remain until script 04.
-- =============================================================================

ALTER SESSION SET CURRENT_SCHEMA = ADVENTUREWORKS2022;

-- Sales and purchasing masters
DELETE FROM SALES_CUSTOMER WHERE CUSTOMERID IN (1, 2, 3);
DELETE FROM SALES_STORE WHERE BUSINESSENTITYID = 6;
DELETE FROM SALES_SALESPERSON WHERE BUSINESSENTITYID = 1;
DELETE FROM SALES_CREDITCARD WHERE CREDITCARDID IN (1, 2);
DELETE FROM PURCHASING_VENDOR WHERE BUSINESSENTITYID IN (7, 8);

-- Production child/master rows
DELETE FROM PRODUCTION_PRODUCTREVIEW WHERE PRODUCTREVIEWID = 1;
DELETE FROM PRODUCTION_PRODUCTINVENTORY WHERE PRODUCTID IN (101, 102, 103);
DELETE FROM PRODUCTION_PRODUCTCOSTHISTORY WHERE PRODUCTID IN (101, 102);
DELETE FROM PRODUCTION_PRODUCTLISTPRICEHISTORY WHERE PRODUCTID IN (101, 102);
DELETE FROM PRODUCTION_PRODUCT WHERE PRODUCTID IN (101, 102, 103);
DELETE FROM PRODUCTION_PRODUCTPHOTO WHERE PRODUCTPHOTOID = 1;
DELETE FROM PRODUCTION_ILLUSTRATION WHERE ILLUSTRATIONID = 1;
DELETE FROM PRODUCTION_DOCUMENT WHERE DOCUMENTNODE = '/1/';
DELETE FROM PRODUCTION_PRODUCTMODEL WHERE PRODUCTMODELID IN (1, 2);
DELETE FROM PRODUCTION_PRODUCTDESCRIPTION WHERE PRODUCTDESCRIPTIONID IN (1, 2);

-- Human Resources and Person masters
DELETE FROM HUMANRESOURCES_JOBCANDIDATE WHERE JOBCANDIDATEID = 1;
DELETE FROM HUMANRESOURCES_EMPLOYEEPAYHISTORY WHERE BUSINESSENTITYID IN (1, 2);
DELETE FROM HUMANRESOURCES_EMPLOYEE WHERE BUSINESSENTITYID IN (1, 2);
DELETE FROM PERSON_PERSONPHONE WHERE BUSINESSENTITYID IN (1, 2, 3, 4);
DELETE FROM PERSON_EMAILADDRESS WHERE BUSINESSENTITYID IN (1, 2, 3, 4);
DELETE FROM PERSON_PASSWORD WHERE BUSINESSENTITYID IN (1, 2, 3, 4);
DELETE FROM PERSON_PERSON WHERE BUSINESSENTITYID IN (1, 2, 3, 4, 5);
DELETE FROM PERSON_ADDRESS WHERE ADDRESSID IN (1, 2, 3, 4);
DELETE FROM PERSON_BUSINESSENTITY WHERE BUSINESSENTITYID BETWEEN 1 AND 8;

COMMIT;

PROMPT [03] Seeded master data removed.
