-- WARNING:
-- This script is destructive and intended only for the local Oracle XE Docker environment.
-- Do not execute against shared, UAT, certification, or production databases.
-- =============================================================================
-- Purpose          : Delete only base-seed reference and lookup rows.
-- Execution order  : 04 of 05; run after master cleanup.
-- Connection user  : SYSTEM; CURRENT_SCHEMA is set to ADVENTUREWORKS2022.
-- Tables affected  : Reference tables across all source domains.
-- Notes            : Completes base-seed removal without dropping objects.
-- =============================================================================

ALTER SESSION SET CURRENT_SCHEMA = ADVENTUREWORKS2022;

DELETE FROM SALES_SALESTAXRATE WHERE SALESTAXRATEID IN (1, 2);
DELETE FROM SALES_CURRENCYRATE WHERE CURRENCYRATEID IN (1, 2);
DELETE FROM SALES_SPECIALOFFER WHERE SPECIALOFFERID IN (1, 2);
DELETE FROM SALES_SALESREASON WHERE SALESREASONID IN (1, 2);
DELETE FROM PERSON_STATEPROVINCE WHERE STATEPROVINCEID IN (1, 2, 3);
DELETE FROM SALES_SALESTERRITORY WHERE TERRITORYID IN (1, 2, 3);
DELETE FROM SALES_CURRENCY WHERE CURRENCYCODE IN ('USD', 'CAD', 'PEN');
DELETE FROM PERSON_COUNTRYREGION WHERE COUNTRYREGIONCODE IN ('US', 'CA', 'PE');

DELETE FROM PURCHASING_SHIPMETHOD WHERE SHIPMETHODID IN (1, 2);
DELETE FROM PRODUCTION_PRODUCTSUBCATEGORY WHERE PRODUCTSUBCATEGORYID IN (1, 2);
DELETE FROM PRODUCTION_PRODUCTCATEGORY WHERE PRODUCTCATEGORYID IN (1, 2);
DELETE FROM PRODUCTION_SCRAPREASON WHERE SCRAPREASONID = 1;
DELETE FROM PRODUCTION_LOCATION WHERE LOCATIONID IN (1, 6);
DELETE FROM PRODUCTION_UNITMEASURE WHERE UNITMEASURECODE IN ('EA', 'CM', 'KG');
DELETE FROM PRODUCTION_CULTURE WHERE CULTUREID IN ('en-US', 'es-PE');

DELETE FROM HUMANRESOURCES_DEPARTMENT WHERE DEPARTMENTID IN (1, 2, 3);
DELETE FROM HUMANRESOURCES_SHIFT WHERE SHIFTID IN (1, 2);
DELETE FROM PERSON_CONTACTTYPE WHERE CONTACTTYPEID IN (1, 2);
DELETE FROM PERSON_ADDRESSTYPE WHERE ADDRESSTYPEID IN (1, 2, 3);
DELETE FROM PERSON_PHONENUMBERTYPE WHERE PHONENUMBERTYPEID IN (1, 2, 3);
DELETE FROM DBO_AWBUILDVERSION WHERE SYSTEMINFORMATIONID = 1;

COMMIT;

PROMPT [04] Seeded reference data removed.
