/* Purpose: Seed validated work rows for the local scenario. Order: 02. */
USE [Sales_Operational];
GO
IF NOT EXISTS(SELECT 1 FROM work.AddressType WHERE SourceAddressTypeID=1) INSERT work.AddressType(SourceAddressTypeID,Name,IsNameNotBlank) VALUES(1,N'Home',1);
IF NOT EXISTS(SELECT 1 FROM work.ProductCategory WHERE SourceProductCategoryID=1) INSERT work.ProductCategory(SourceProductCategoryID,Name,IsNameNotBlank) VALUES(1,N'Road Bikes',1);
IF NOT EXISTS(SELECT 1 FROM work.SpecialOffer WHERE SourceSpecialOfferID=1) INSERT work.SpecialOffer(SourceSpecialOfferID,Description,DiscountPct,OfferType,Category,StartDate,EndDate,MinQty,MaxQty,IsDescriptionNotBlank,IsOfferTypeNotBlank,IsCategoryNotBlank) VALUES(1,N'Local seed offer',.1,N'Discount',N'Reseller','2023-01-01','2027-12-31',1,10,1,1,1);
IF NOT EXISTS(SELECT 1 FROM work.ShipMethod WHERE SourceShipMethodID=1) INSERT work.ShipMethod(SourceShipMethodID,Name,ShipBase,ShipRate,IsNameNotBlank) VALUES(1,N'Ground',5,1,1);
IF NOT EXISTS(SELECT 1 FROM work.CountryRegion WHERE SourceCountryRegionCode='US') INSERT work.CountryRegion(SourceCountryRegionCode,Name,IsCountryRegionCodeNotBlank,IsNameNotBlank) VALUES('US',N'United States',1,1);
IF NOT EXISTS(SELECT 1 FROM work.SalesTerritory WHERE SourceTerritoryID=1) INSERT work.SalesTerritory(SourceTerritoryID,Name,TerritoryGroup,SourceCountryRegionCode,IsNameNotBlank,IsTerritoryGroupNotBlank,IsCountryRegionValid) VALUES(1,N'Northwest',N'North America','US',1,1,1);
IF NOT EXISTS(SELECT 1 FROM work.StateProvince WHERE SourceStateProvinceID=1) INSERT work.StateProvince(SourceStateProvinceID,StateProvinceCode,Name,SourceCountryRegionCode,SourceTerritoryID,IsStateProvinceCodeNotBlank,IsNameNotBlank,IsCountryRegionValid,IsSalesTerritoryValid) VALUES(1,'WA',N'Washington','US',1,1,1,1,1);
IF NOT EXISTS(SELECT 1 FROM work.Currency WHERE SourceCurrencyCode='USD') INSERT work.Currency(SourceCurrencyCode,Name,IsCurrencyCodeNotBlank,IsNameNotBlank) VALUES('USD',N'US Dollar',1,1);
IF NOT EXISTS(SELECT 1 FROM work.CurrencyRate WHERE SourceCurrencyRateID=1) INSERT work.CurrencyRate(SourceCurrencyRateID,CurrencyRateDate,FromCurrencyCode,ToCurrencyCode,AverageRate,EndOfDayRate,IsFromCurrencyValid,IsToCurrencyValid) VALUES(1,'2023-01-01','USD','USD',1,1,1,1);
IF NOT EXISTS(SELECT 1 FROM work.CreditCard WHERE SourceCreditCardID=1) INSERT work.CreditCard(SourceCreditCardID,CardType,CardNumber,ExpMonth,ExpYear,IsCardTypeNotBlank,IsCardNumberUsable) VALUES(1,N'Visa','4111111111111111',12,2030,1,1);
IF NOT EXISTS(SELECT 1 FROM work.Address WHERE SourceAddressID=1) INSERT work.Address(SourceAddressID,AddressLine1,City,SourceStateProvinceID,PostalCode,SourceAddressTypeID,IsAddressLine1NotBlank,IsCityNotBlank,IsPostalCodeNotBlank,IsStateProvinceValid,IsAddressTypeValid) VALUES(1,N'1 Seed Street',N'Seattle',1,'98101',1,1,1,1,1,1);
IF NOT EXISTS(SELECT 1 FROM work.Product WHERE SourceProductID=1) INSERT work.Product(SourceProductID,ProductNumber,Name,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,Size,Weight,SourceProductCategoryID,SellStartDate,IsProductNumberNotBlank,IsNameNotBlank,IsProductCategoryValid) VALUES(1,'SEED-001',N'Seed Road Bike',N'Red',100,10,500,750,N'M',10,1,'2023-01-01',1,1,1);
IF NOT EXISTS(SELECT 1 FROM work.SalesPerson WHERE SourceSalesPersonID=1) INSERT work.SalesPerson(SourceSalesPersonID,SourceTerritoryID,Title,FirstName,LastName,JobTitle,Gender,HireDate,SalesQuota,Bonus,CommissionPct,SalesYTD,SalesLastYear,IsFirstNameNotBlank,IsLastNameNotBlank,IsJobTitleNotBlank,IsGenderNotBlank,IsSalesTerritoryValid) VALUES(1,1,N'Ms.',N'Alex',N'Rivera',N'Sales Representative','F','2020-01-01',100000,1000,.05,25000,20000,1,1,1,1,1);
IF NOT EXISTS(SELECT 1 FROM work.Customer WHERE SourceCustomerID=1) INSERT work.Customer(SourceCustomerID,SourceTerritoryID,PersonType,Title,FirstName,LastName,AccountNumber,IsPersonNameValid,IsSalesTerritoryValid) VALUES(1,1,'IN',N'Ms.',N'Jordan',N'Lee','AW00000001',1,1);
DECLARE @CustomerKey INT=(SELECT WorkCustomerKey FROM work.Customer WHERE SourceCustomerID=1), @SalesPersonKey INT=(SELECT WorkSalesPersonKey FROM work.SalesPerson WHERE SourceSalesPersonID=1), @TerritoryKey INT=(SELECT WorkSalesTerritoryKey FROM work.SalesTerritory WHERE SourceTerritoryID=1), @AddressKey INT=(SELECT WorkAddressKey FROM work.Address WHERE SourceAddressID=1), @ShipMethodKey INT=(SELECT WorkShipMethodKey FROM work.ShipMethod WHERE SourceShipMethodID=1), @CreditCardKey INT=(SELECT WorkCreditCardKey FROM work.CreditCard WHERE SourceCreditCardID=1), @CurrencyRateKey INT=(SELECT WorkCurrencyRateKey FROM work.CurrencyRate WHERE SourceCurrencyRateID=1);
IF NOT EXISTS(SELECT 1 FROM work.SalesOrderHeader WHERE SourceSalesOrderID=1) INSERT work.SalesOrderHeader(SourceSalesOrderID,RevisionNumber,OrderDate,DueDate,ShipDate,Status,SalesOrderNumber,PurchaseOrderNumber,AccountNumber,CustomerKey,SalesPersonKey,SalesTerritoryKey,BillToAddressKey,ShipToAddressKey,ShipMethodKey,CreditCardKey,CurrencyRateKey,SubTotal,TaxAmt,Freight,TotalDue,Comment,IsSalesOrderNumberNotBlank,IsCustomerValid,IsSalesPersonValid,IsSalesTerritoryValid,IsBillToAddressValid,IsShipToAddressValid,IsShipMethodValid,IsCreditCardValid,IsCurrencyRateValid) VALUES(1,1,'2023-01-15','2023-01-22','2023-01-17',5,'SO-SEED-001','PO-SEED-001','AW00000001',@CustomerKey,@SalesPersonKey,@TerritoryKey,@AddressKey,@AddressKey,@ShipMethodKey,@CreditCardKey,@CurrencyRateKey,750,60,15,825,N'Local seed order',1,1,1,1,1,1,1,1,1);
DECLARE @HeaderKey BIGINT=(SELECT WorkSalesOrderHeaderKey FROM work.SalesOrderHeader WHERE SourceSalesOrderID=1), @ProductKey INT=(SELECT WorkProductKey FROM work.Product WHERE SourceProductID=1), @OfferKey INT=(SELECT WorkSpecialOfferKey FROM work.SpecialOffer WHERE SourceSpecialOfferID=1);
IF NOT EXISTS(SELECT 1 FROM work.SalesOrderDetail WHERE SourceSalesOrderID=1 AND SourceSalesOrderDetailID=1) INSERT work.SalesOrderDetail(SalesOrderHeaderKey,SourceSalesOrderID,SourceSalesOrderDetailID,ProductKey,SpecialOfferKey,CarrierTrackingNumber,OrderQty,UnitPrice,UnitPriceDiscount,LineTotal,IsSalesOrderHeaderValid,IsProductValid,IsSpecialOfferValid) VALUES(@HeaderKey,1,1,@ProductKey,@OfferKey,'TRACK-SEED-001',1,750,0,750,1,1,1);
GO
