/* Purpose: Seed one coherent final operational scenario. Order: 03. */
USE [Sales_Operational];
GO
IF NOT EXISTS(SELECT 1 FROM prod.AddressType WHERE SourceAddressTypeID=1) INSERT prod.AddressType(SourceAddressTypeID,Name) VALUES(1,N'Home');
IF NOT EXISTS(SELECT 1 FROM prod.ProductCategory WHERE SourceProductCategoryID=1) INSERT prod.ProductCategory(SourceProductCategoryID,Name) VALUES(1,N'Road Bikes');
IF NOT EXISTS(SELECT 1 FROM prod.ShipMethod WHERE SourceShipMethodID=1) INSERT prod.ShipMethod(SourceShipMethodID,Name,ShipBase,ShipRate) VALUES(1,N'Ground',5,1);
IF NOT EXISTS(SELECT 1 FROM prod.CountryRegion WHERE SourceCountryRegionCode='US') INSERT prod.CountryRegion(SourceCountryRegionCode,Name) VALUES('US',N'United States');
DECLARE @CountryKey INT=(SELECT CountryRegionKey FROM prod.CountryRegion WHERE SourceCountryRegionCode='US');
IF NOT EXISTS(SELECT 1 FROM prod.SalesTerritory WHERE SourceTerritoryID=1) INSERT prod.SalesTerritory(SourceTerritoryID,Name,TerritoryGroup,CountryRegionKey) VALUES(1,N'Northwest',N'North America',@CountryKey);
DECLARE @TerritoryKey INT=(SELECT SalesTerritoryKey FROM prod.SalesTerritory WHERE SourceTerritoryID=1);
IF NOT EXISTS(SELECT 1 FROM prod.StateProvince WHERE SourceStateProvinceID=1) INSERT prod.StateProvince(SourceStateProvinceID,StateProvinceCode,Name,CountryRegionKey,SalesTerritoryKey) VALUES(1,'WA',N'Washington',@CountryKey,@TerritoryKey);
IF NOT EXISTS(SELECT 1 FROM prod.SpecialOffer WHERE SourceSpecialOfferID=1) INSERT prod.SpecialOffer(SourceSpecialOfferID,Description,DiscountPct,OfferType,Category,StartDate,EndDate,MinQty,MaxQty) VALUES(1,N'Local seed offer',.1,N'Discount',N'Reseller','2023-01-01','2027-12-31',1,10);
IF NOT EXISTS(SELECT 1 FROM prod.Currency WHERE SourceCurrencyCode='USD') INSERT prod.Currency(SourceCurrencyCode,Name) VALUES('USD',N'US Dollar');
DECLARE @CurrencyKey INT=(SELECT CurrencyKey FROM prod.Currency WHERE SourceCurrencyCode='USD');
IF NOT EXISTS(SELECT 1 FROM prod.CurrencyRate WHERE SourceCurrencyRateID=1) INSERT prod.CurrencyRate(SourceCurrencyRateID,CurrencyRateDate,FromCurrencyKey,ToCurrencyKey,AverageRate,EndOfDayRate) VALUES(1,'2023-01-01',@CurrencyKey,@CurrencyKey,1,1);
IF NOT EXISTS(SELECT 1 FROM prod.CreditCard WHERE SourceCreditCardID=1) INSERT prod.CreditCard(SourceCreditCardID,CardType,CardNumber,ExpMonth,ExpYear) VALUES(1,N'Visa','4111111111111111',12,2030);
DECLARE @StateKey INT=(SELECT StateProvinceKey FROM prod.StateProvince WHERE SourceStateProvinceID=1), @AddressTypeKey INT=(SELECT AddressTypeKey FROM prod.AddressType WHERE SourceAddressTypeID=1);
IF NOT EXISTS(SELECT 1 FROM prod.Address WHERE SourceAddressID=1) INSERT prod.Address(SourceAddressID,AddressLine1,City,StateProvinceKey,PostalCode,AddressTypeKey) VALUES(1,N'1 Seed Street',N'Seattle',@StateKey,'98101',@AddressTypeKey);
DECLARE @ProductCategoryKey INT=(SELECT ProductCategoryKey FROM prod.ProductCategory WHERE SourceProductCategoryID=1);
IF NOT EXISTS(SELECT 1 FROM prod.Product WHERE SourceProductID=1) INSERT prod.Product(SourceProductID,ProductNumber,Name,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,Size,Weight,ProductCategoryKey,SellStartDate) VALUES(1,'SEED-001',N'Seed Road Bike',N'Red',100,10,500,750,N'M',10,@ProductCategoryKey,'2023-01-01');
IF NOT EXISTS(SELECT 1 FROM prod.SalesPerson WHERE SourceSalesPersonID=1) INSERT prod.SalesPerson(SourceSalesPersonID,SalesTerritoryKey,Title,FirstName,LastName,JobTitle,Gender,HireDate,SalesQuota,Bonus,CommissionPct,SalesYTD,SalesLastYear) VALUES(1,@TerritoryKey,N'Ms.',N'Alex',N'Rivera',N'Sales Representative','F','2020-01-01',100000,1000,.05,25000,20000);
IF NOT EXISTS(SELECT 1 FROM prod.Customer WHERE SourceCustomerID=1) INSERT prod.Customer(SourceCustomerID,SalesTerritoryKey,PersonType,Title,FirstName,LastName,AccountNumber) VALUES(1,@TerritoryKey,'IN',N'Mr.',N'Jordan',N'Lee','AW00000001');
DECLARE @CustomerKey INT=(SELECT CustomerKey FROM prod.Customer WHERE SourceCustomerID=1), @SalesPersonKey INT=(SELECT SalesPersonKey FROM prod.SalesPerson WHERE SourceSalesPersonID=1), @AddressKey INT=(SELECT AddressKey FROM prod.Address WHERE SourceAddressID=1), @ShipMethodKey INT=(SELECT ShipMethodKey FROM prod.ShipMethod WHERE SourceShipMethodID=1), @CreditCardKey INT=(SELECT CreditCardKey FROM prod.CreditCard WHERE SourceCreditCardID=1), @CurrencyRateKey INT=(SELECT CurrencyRateKey FROM prod.CurrencyRate WHERE SourceCurrencyRateID=1);
IF NOT EXISTS(SELECT 1 FROM prod.SalesOrderHeader WHERE SourceSalesOrderID=1) INSERT prod.SalesOrderHeader(SourceSalesOrderID,RevisionNumber,OrderDate,DueDate,ShipDate,Status,SalesOrderNumber,PurchaseOrderNumber,AccountNumber,CustomerKey,SalesPersonKey,SalesTerritoryKey,BillToAddressKey,ShipToAddressKey,ShipMethodKey,CreditCardKey,CurrencyRateKey,SubTotal,TaxAmt,Freight,TotalDue,Comment) VALUES(1,1,'2023-01-15','2023-01-22','2023-01-17',5,'SO-SEED-001','PO-SEED-001','AW00000001',@CustomerKey,@SalesPersonKey,@TerritoryKey,@AddressKey,@AddressKey,@ShipMethodKey,@CreditCardKey,@CurrencyRateKey,750,60,15,825,N'Local seed order');
DECLARE @HeaderKey BIGINT=(SELECT SalesOrderHeaderKey FROM prod.SalesOrderHeader WHERE SourceSalesOrderID=1), @ProductKey INT=(SELECT ProductKey FROM prod.Product WHERE SourceProductID=1), @OfferKey INT=(SELECT SpecialOfferKey FROM prod.SpecialOffer WHERE SourceSpecialOfferID=1);
IF NOT EXISTS(SELECT 1 FROM prod.SalesOrderDetail WHERE SourceSalesOrderID=1 AND SourceSalesOrderDetailID=1) INSERT prod.SalesOrderDetail(SalesOrderHeaderKey,SourceSalesOrderID,SourceSalesOrderDetailID,ProductKey,SpecialOfferKey,CarrierTrackingNumber,OrderQty,UnitPrice,UnitPriceDiscount,LineTotal) VALUES(@HeaderKey,1,1,@ProductKey,@OfferKey,'TRACK-SEED-001',1,750,0,750);
GO
